### ISSUE TITLE
Provisioning fails

### ISSUE THREAD

**Issue by Jonfor** [geerlingguy/drupal-vm#1032]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.6
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.11.6)

### Full console output
https://gist.github.com/Jonfor/441efaf9d6d475c80449055eaa3d7340
### Summary
I updated to the latest and greatest Drupal VM version and I get this error during the provisioning step. Is the drupal directory supposed to be created by me beforehand?

**Comment by geerlingguy** [comment]
@Jonfor - Can you post your `vagrant_synced_folders` configuration in `config.yml`? It looks like you may be using a share in a different location and need to update the drupal core path... or it could be that Vagrant never created the synced folder.

**Comment by Jonfor** [comment]
Here it is:
```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  - local_path: ../../
    destination: /var/www
    type: nfs
    create: true
```

**Comment by oxyc** [comment]
`local_path: ../../` looks like it could be wrong. This path is relative from the directory where the `Vagrantfile` is located, so in most cases it's the same directory and therefore `.`.

What type of setup do you have? How does your project structure look?

**Comment by Jonfor** [comment]
My folder setup is as follows: 

project_name->tools->drupalvm->Vagrantfile
project_name->docroot

**Comment by Jonfor** [comment]
I think I fixed that issue. I needed to update my config.yml. I'm running into a new issue however where it seems to be trying to install Drupal 8 instead of Drupal 7. I've attached the logs.

https://gist.github.com/Jonfor/f87ff7e305e259987d602a54f9b13341

I have the following relevant settings in `config.yml`:
`drush_version: "8.x"`
`drupal_major_version: 7`

And my `drupal.make.yml`
```
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "7.x"

projects:

  # Core.
  drupal:
    version: "7.50"
    # Use this if you need a working git repository of Drupal core instead of
    # the latest stable.
    # type: "core"
    # download:
    #   # Drupal core branch (e.g. "6.x", "7.x", "8.0.x").
    #   branch: "7.x"
    #   working-copy: true

  # Other modules.
  devel: "1.x-dev"
```
