### ISSUE TITLE
Question: SSL with apache on vagrant for my Drupal VM

### ISSUE THREAD

**Issue by iefrati** [geerlingguy/drupal-vm#1074]
### Issue Type
 Support Request

### Your Environment
latest drupal-vm version

### Your OS
 **macOS** (10.11)

### Full console output

I am trying to use SSL with apache on vagrant for my Drupal VM
I used that page http://docs.drupalvm.com/en/latest/extras/ssl/

Added to the bottom of my config.yml the following code
```
apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

```
generated example.crt and example.key in /vagrant using `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout example.key -out example.crt`

```
vagrant@name:/vagrant$ ls |grep example
example.crt
example.key

```
I made sure that 443 is open, and I reloaded my machine, but I am still getting

ERR_SSL_PROTOCOL_ERROR

___EDIT___ 
config.yml file

---
```
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1404, geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1604
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: test.me
vagrant_machine_name: test-dev-vm
vagrant_ip: 192.168.88.89

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  - local_path: ../test
    destination: /var/www/test
    type: nfs
    create: true
    excluded_paths:
      - .git
      - .sass-cache
      - docs
      - db
      - migration_data
      - tmp
      - docroot/sites/default/files

# Memory and CPU to use for this VM.
vagrant_memory: 4096 # Or 1/4 of the total RAM available on your computer
vagrant_cpus: 2 # Note that if using this vm with VirtualBox, you should change this value to 1 to improve performance

drupal_composer_install_dir: "/var/www/test/docroot"
drupal_composer_dependencies: []

# Set this to false if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Settings for building a Drupal site from a makefile (if 'build_makefile:'
# is 'true').
drupal_major_version: 7
drupal_core_path: "/var/www/test/docroot"
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "test Dev Site"
drupal_install_profile: test
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: testing
drupal_db_user: testing
drupal_db_password: testing
drupal_db_name: test_init_testing

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - varnish
  - xdebug
  #- xhprof

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "3306"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "8889"

php_memory_limit: "256M"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"


```
Any ideas?

**Comment by iefrati** [comment]
Also looked at #798

**Comment by oxyc** [comment]
I'll try and reproduce this later today after work. I believe I've only ever tested Ubuntu's snakeoil certificate.

In case it makes a difference, which `vagrant_box` are you using?

**Comment by iefrati** [comment]
Vagrant 1.9.1

**Comment by iefrati** [comment]
If I am disabling the htaccess https redirect I can access the site, so I am sure it is something stupid as a path to the crt or something like this?

**Comment by oxyc** [comment]
Could you post your entire `config.yml` file?

**Comment by iefrati** [comment]
edited the original post

**Comment by oxyc** [comment]
Hmm that's odd. It works for me. I just get `ERR_CERT_AUTHORITY_INVALID`. Are the apache logs saying anything?

**Comment by iefrati** [comment]
Nothing

[Thu Dec 22 17:17:17.045217 2016] [core:notice] [pid 1152:tid 140369839064960] AH00094: Command line: '/usr/sbin/apache2'
[Thu Dec 22 18:17:25.498081 2016] [mpm_event:notice] [pid 1152:tid 140369839064960] AH00491: caught SIGTERM, shutting down
[Thu Dec 22 18:17:43.133022 2016] [ssl:warn] [pid 1157:tid 139826756695936] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu Dec 22 18:17:43.134933 2016] [mpm_event:notice] [pid 1157:tid 139826756695936] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Thu Dec 22 18:17:43.134947 2016] [core:notice] [pid 1157:tid 139826756695936] AH00094: Command line: '/usr/sbin/apache2'

**Comment by iefrati** [comment]
Did you configure anything in apache itself?

**Comment by oxyc** [comment]
I did not. I didn't use your `config.yml` though, I just tested the ssl vhost while testing another bug report. I'll try again with your exact copy later today. This is the one I used, that did work.

```
vagrant_hostname: drupalvm-project.dev
vagrant_machine_name: drupalvm_project
vagrant_ip: 192.168.99.88
vagrant_box: geerlingguy/ubuntu1604

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

php_version: "5.6"
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  - upload-progress
  - varnish
  - xdebug
  - xhprof
```

**Comment by iefrati** [comment]
so for 
/vagrant/example.key

did you do vagrant ssh
cd /vagrant
and ran the 
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout example.key -out example.crt

does it matter where you run it if you move the files somewhere else?

**Comment by oxyc** [comment]
I did it on my host computer. But it shouldn't make a difference I guess.

**Comment by iefrati** [comment]
Just tested from /vagrant/ not changing any thing also
sudo service apache2 restart, not helping

**Comment by oxyc** [comment]
I tested again with your `config.yml` and again, I only get `ERR_CERT_AUTHORITY_INVALID `.

**Comment by oxyc** [comment]
Could you try with the default Drupal VM directory structure and only add this to your `config.yml`:

```
vagrant_hostname: test.me
vagrant_machine_name: test-dev-vm
vagrant_ip: 192.168.88.89

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"
```

Also make sure you have the `example.crt` and `example.key` in the same directory as the `config.yml`.
