### ISSUE TITLE
chown not changing the ownership of directories

### ISSUE THREAD

**Issue by pandabrand** [geerlingguy/drupal-vm#1075]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.6r110634
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.1)

### Full console output

https://gist.github.com/pandabrand/118523ad621a1b46e1072f0bdc95b4a2.js

### Summary

I am trying to build a Drupal 7 environment, I am now trying to set up UpdateManager without the FTP, so I am trying to change the ownership of the drupal directory to www-data. I have turned off nfs on my vagrant synced folders. When I run `chown -R www-data:www-data drupal` no errors occur but the ownership doesn't change either, it's still owned by the vagrant user.

**Comment by oxyc** [comment]
What synced folder method are you using? This sounds familiar to https://github.com/geerlingguy/drupal-vm/issues/726#issuecomment-225996632 which happens with NFS. Do you get an error message if you run the chown with `sudo`?

**Comment by pandabrand** [comment]
I'll be honest I'm pretty green with vagrant this is my config that 
```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    # type: nfs
    create: true

```

I'm not sure what happens when you just comment that out. 
When I have NFS on I get `Operation not permitted`. When I run the chown with `sudo` same as without, no error but ownership doesn't change.
