### ISSUE TITLE
undefined symbol: zend_sort

### ISSUE THREAD

**Issue by sbubaron** [geerlingguy/drupal-vm#1076]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

VirtualBox: Version 5.0.30 r112061
```

### Your OS
 - **Windows** 10

### Full console output

N/A

### Summary
After switching from php7.0 to 5.6 and running vagrant provision the following error would pop up in the console randomly while running drush commands:

```
Failed loading /usr/lib/php5/modules/xdebug.so:  /usr/lib/php5/modules/xdebug.so: undefined symbol: zend_sort
```

vagrant destroy and vagrant up seemed to fix it -- but oxyc requested I open a new issue.

**Comment by oxyc** [comment]
Found the bug. It's because https://github.com/geerlingguy/ansible-role-php-xdebug/blob/master/tasks/main.yml#L33:L42 (and xhprof, uploadprogress) do not re-compile as there's no name change. It simply copies the old version in place.

> TASK [geerlingguy.php-xdebug : Build Xdebug.] **********************************
ok: [drupalvm_project] => (item=phpize)
ok: [drupalvm_project] => (item=./configure)
ok: [drupalvm_project] => (item=make)

For reference: https://github.com/geerlingguy/drupal-vm/pull/1043#issuecomment-268879545

**Comment by oxyc** [comment]
ping @thom8 @geerlingguy maybe fix this in the upstream roles by changing it to something like:

```yaml
- name: Build Xdebug.
  shell: >
    {{ item }}
    chdir={{ workspace }}/xdebug-{{ php_xdebug_version }}-php{{ php_version }}
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}-php{{ php_version }}/modules/xdebug.so
  with_items:
    - phpize
    - ./configure
    - make
  notify: restart webserver
```
