### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR in chrome and SSL_ERROR_RX_RECORD_TOO_LONG in firefox

### ISSUE THREAD

**Issue by nikathone** [geerlingguy/drupal-vm#1080]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.7
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.12.2)

### Full console output
From chrome:
This site can’t provide a secure connection
www.drupalvm.dev sent an invalid response.
Try running Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

### Summary
Using this config:
```
---
# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ../drupal7 
    destination: /var/www/drupalvm
    type: nfs
    create: true

# Settings for installing a Drupal site if 'install_site:' is 'true'.
drupal_major_version: 7
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: []
drupal_account_name: admin
drupal_account_pass: admin

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - upload-progress
  # - varnish
  # - xdebug
  # - xhprof

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1.
# See version-specific notes: http://docs.drupalvm.com/en/latest/other/php/
php_version: "5.6"

# Other configuration.
ssh_home: "{{ drupal_core_path }}"
```
Removed the part I didn't change from default.config.yml.
