### ISSUE TITLE
mbstring error on Drupal 7

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#1081]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (version)

### Full console output
Gist here: https://gist.github.com/minorscience/fce47cf5050f0d0a6cdb0cde61cf60f1

### Summary
Issue is similar to: https://github.com/geerlingguy/drupal-vm/issues/799. Getting an mbstring error when attempting to install latest Drupal 7 release. Configuration below. 

build_makefile: true
build_composer: false
build_composer_project: false
php_version: "7.1" 

```
---
api: 2
core: "7.x"

projects:
  drupal:
    version: "7.52"
  devel: "1.x-dev"
```
