### ISSUE TITLE
Question: How to run D7 and D8 in same DrupalVM instance?

### ISSUE THREAD

**Issue by caschbre** [geerlingguy/drupal-vm#1109]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

```
Linux xps15 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
```

### Summary

I'm in the process of upgrading some D7 sites to D8.  I'd like to run both the D7 site and (new) D8 site in the same DrupalVM instance.  Basically two completely separate sites. The D7 site is for reference while the D8 is the new / upgraded site.

I'm trying to figure out if there is a way in the config.yml file to have it create two databases and two host entries.  I don't care what the urls will be, whether each site is d8.mysite.loc or mysite.loc/d8. 

Below is a copy of my config.yml.

```
---
# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: dna.loc
vagrant_machine_name: dna
vagrant_ip: 192.168.88.126

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: "192.168.1.126"

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ~/projects/dna
    destination: /var/www/drupalvm
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: nginx

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
build_composer_project: false

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Required Drupal settings.
drupal_core_path: "/var/www/drupalvm/d8/web"
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: dna8_loc

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "{{ drupal_domain }} d7.{{ drupal_domain }}"
    root: "/var/www/drupalvm/d7/drupal"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"
    is_php: true

# MySQL databases and users.
mysql_databases:
  - name: "dna8_loc"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: "dna7_loc"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "dna8_loc.*:ALL"
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "dna7_loc.*:ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  - upload-progress
  # - varnish
  - xdebug
  # - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

# PHP Configuration. Currently-supported versions: 5.6, 7.0.
# To use 5.6, see: http://docs.drupalvm.com/en/latest/other/php-56/
php_memory_limit: "256M"

# Run specified scripts before or after VM is provisioned. Path is relative to
# the `provisioning/playbook.yml` file.
pre_provision_scripts: []
post_provision_scripts: []
  # - "../examples/scripts/configure-solr.sh"

# MySQL Configuration.
mysql_packages:
- mariadb-client
- mariadb-server
- python-mysqldb
```

Interestingly the dashboard shows two databases. I'm guessing because this is read from the config file. However Adminer only has a single database.

I realize I can just SSH into the VM and alter the nginx and databases, but I was just wondering if there is an easier way to get that initially setup with the config.yml file.

**Comment by oxyc** [comment]
```yaml
mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "dna8_loc.*:ALL"
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "dna7_loc.*:ALL"
```

Wont work, the second line will override the first one. I'm not sure what the syntax would be for two specific databases, but as this is a dev environment, the easy fix it to use:

```yaml
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "*.*:ALL"
```

As for the nginx vhost, you probably dont want both to have the `{{ drupal_domain }}` host.

```yaml
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true
  - server_name: "d7.{{ drupal_domain }}"
    root: "/var/www/drupalvm/d7/drupal"
    is_php: true
```

**Comment by oxyc** [comment]
Found [the syntax for multiple databases](http://docs.ansible.com/ansible/mysql_user_module.html):

```yaml
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "dna8_loc.*:ALL/dna7_loc.*:ALL"
```
