### ISSUE TITLE
Cannot run behat tests due to selenium error

### ISSUE THREAD

**Issue by iefrati** [geerlingguy/drupal-vm#1122]
### Issue Type
 - Bug Report / Support Request

### Your Environment
vagrant --version && echo "VirtualBox"
Vagrant 1.9.1
VirtualBox

### Your OS
macOS (10.11)

### Full console output
I have some behat tests that I would like to run.
If I do `vagrant ssh`, and go to 
`var/www/drupal` in which I run my `behat` with
` bin/behat tests/features/basic_page/create_page.feature
`

All the tests that are not using `@javascript` are running correctly, but the once that need `selenium` fail. with the following error
`      Failed to connect to localhost port 4444: Connection refused (Behat\Mink\Exception\DriverException)
`

I tried to add it to installed_extras:
but I am getting the following error during provision 

```
TASK [arknoll.selenium : Ensure selenium is running] ***************************
fatal: [test-dev-vm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'selenium'\": "}
	to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
test-dev-vm                : ok=163  changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

my behat yml file is:

```
default:
  extensions:
    Behat\MinkExtension:
      base_url: 'https://testing.test.me/'
      goutte:
        guzzle_parameters:
          verify: false
      show_cmd: open -a Safari %s
      browser_name: firefox #firefox  # Set to chrome if using the chromedriver
  suites:
    default:
      contexts:
        - FeatureContext:
            test_testing_hostname: 'testing.test.me'
            bootstrap_database_dump: 'test_init_testing.sql'
            codebase_root: '/var/www/drupal' 
            setup_script_dir: 'var/www/drupal/bin' #behat is here
            setup_script: 'devsite_vm'
            dbusername: 'testing'
            dbpassword: 'testing'
            dbname: 'test_init_testing'
```

Ideas?

**Comment by iefrati** [comment]
I also patched my code with
https://github.com/geerlingguy/drupal-vm/commit/d6c62acd175888f87b595c2aea6aac5889b36a4a

Now I am getting 
```
TASK [arknoll.selenium : Register systemd service status (for systemd systems)] 
fatal: [test-dev-vm]: FAILED! => {"changed": false, "cmd": "systemctl status selenium | grep \"active (running)\"", "delta": "0:00:00.004935", "end": "2017-01-13 14:35:07.276681", "failed": true, "rc": 1, "start": "2017-01-13 14:35:07.271746", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

```

but I am still seeing the following error when running tests

      Could not open connection: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
      Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
      System info: host: 'test', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-31-generic', java.version: '1.8.0_111'
      Driver info: driver.version: FirefoxDriver (Behat\Mink\Exception\DriverException)

**Comment by iefrati** [comment]
Also looking in the docs and changing the yml file to 
```
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://drupalvm.dev:4444/wd/hub
      base_url: http://drupalvm.dev

```

still results in the same error

**Comment by geerlingguy** [comment]
@iefrati - It looks like you have Selenium configured to use FireFox, but the default for that ansible role is now Chrome, so maybe it installed chromium instead of FireFox? See: https://github.com/arknoll/ansible-role-selenium#variables

Also, are you running the latest version of Drupal VM, or have you patched an older version? There were a few major issues with Selenium support on Ubuntu 16.04 and CentOS 7 with Ansible 2.2 up until 3.4.0 (or maybe even one of the 4.x releases?)...

**Comment by iefrati** [comment]
@geerlingguy 

1) where would you configure selenium? I don't mind using chrome. I used to use mamp and that is why I had it with firefox on my local machine. 

I don't mind also running selenium locally and only have drupal vm act as the server for the website.

2) just patched it with this commit d6c62ac

**Comment by geerlingguy** [comment]
@iefrati - That fix should make things work, but to configure anything selenium-related, you can override any of that role's variables in your `config.yml` file—see a full list here: https://github.com/arknoll/ansible-role-selenium#variables

**Comment by iefrati** [comment]
even when I remove the firefox section from behat, and just keep the default selenium configurations, and doing the following yml in behat , I am getting the same error

```
default:
  extensions:
    Behat\MinkExtension:
      base_url: 'https://testing.test.me/'
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://drupalvm.dev:4444/wd/hub
      base_url: http://drupalvm.dev
  suites:
    default:
      contexts:
        - FeatureContext:
            test_testing_hostname: 'testing.test.me'
            bootstrap_database_dump: 'test_init_testing.sql'
            codebase_root: '/var/www/test'
            setup_script_dir: 'var/www/cals/bin'
            setup_script: 'devsite_vm_ido'
            dbusername: 'testing'
            dbpassword: 'testing'
            dbname: 'test_init_testing'

```

Am I just being stupid, and missing something super obvious ?
