### ISSUE TITLE
Unable to install memcached php package

### ISSUE THREAD

**Issue by leonk** [geerlingguy/drupal-vm#1143]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.0
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.1)
### Full console output

My config.yml:
https://gist.github.com/leonk/7397cd112197ce42cb351ae32384bbc3

My console output
https://gist.github.com/leonk/fff2aff2ef68cd183c5cb41b23fc7527

### Summary

I'm trying to install memcache on an already provisioned VM.  All I did was uncomment the `- memcached` and ran `vagrant up --provision`.  I got the following error

```
TASK [geerlingguy.php-memcached : Install PHP Memcached extension (Debian).] ***
fatal: [uniper-drupalvm]: FAILED! => {"cache_update_time": 1485432659, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'php5-memcached'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n php5-memcached : Depends: phpapi-20090626\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " php5-memcached : Depends: phpapi-20090626"]}
```

**Comment by oxyc** [comment]
As of Drupal VM 4.0.0 you can delete this entire section:

```yaml
php_install_recommends: no
php_packages:
  - php5.6
  - php5.6-apcu
  - php5.6-mcrypt
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-sqlite3
  - php5.6-xml
  - php5.6-mbstring
  - libpcre3-dev
php_conf_paths:
  - /etc/php/5.6/fpm
  - /etc/php/5.6/apache2
  - /etc/php/5.6/cli
php_extension_conf_paths:
  - /etc/php/5.6/fpm/conf.d
  - /etc/php/5.6/apache2/conf.d
  - /etc/php/5.6/cli/conf.d
php_fpm_daemon: php5.6-fpm
php_fpm_conf_path: "/etc/php/5.6/fpm"
php_fpm_pool_conf_path: "/etc/php/5.6/fpm/pool.d/www.conf"
php_mysql_package: php5.6-mysql

php_memcached_package: php5-memcached

# Older version of XHProf.
xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
xhprof_download_folder_name: xhprof-master
```

and just leave it as:

```yaml
php_version: "5.6"
```
