### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by adamtyoung** [geerlingguy/drupal-vm#1178]
### Issue Type

 - Bug Report / Support Request
### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.10r112026
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (version)

### Summary

Adding SSL to my config.yml works fine, using this:

```
apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"
```

I am able to add the exception to my browser, but I am then presented with the Apache welcome screen. 

/etc/httpd/conf.d/vhosts.conf file:
```
DirectoryIndex index.php index.html


<VirtualHost *:80>
  ServerName d7dev.local
  ServerAlias www.d7dev.local
  DocumentRoot /var/www/drupalvm/drupal

  <Directory "/var/www/drupalvm/drupal">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName adminer.d7dev.local
  DocumentRoot /opt/adminer

  <Directory "/opt/adminer">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName xhprof.d7dev.local
  DocumentRoot /usr/share/php/xhprof_html

  <Directory "/usr/share/php/xhprof_html">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName pimpmylog.d7dev.local
  DocumentRoot /usr/share/php/pimpmylog

  <Directory "/usr/share/php/pimpmylog">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName 192.168.50.5
  ServerAlias dashboard.d7dev.local
  DocumentRoot /var/www/dashboard

  <Directory "/var/www/dashboard">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>


<VirtualHost *:443>
  ServerName d7dev.local
  DocumentRoot /var/www/drupalvm/drupal

  SSLEngine on
  SSLCipherSuite AES256+EECDH:AES256+EDH
  SSLProtocol All -SSLv2 -SSLv3
  SSLHonorCipherOrder On
  SSLCompression off
  SSLCertificateFile /vagrant/example.crt
  SSLCertificateKeyFile /vagrant/example.key

  <Directory "/var/www/drupalvm/drupal">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
 </Directory>
  ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/drupalvm/drupal"

</VirtualHost>
```

looks fine. What could this be?

**Comment by adamtyoung** [comment]
Just to be clear, my site **does not work under ssl** (even though the vhosts file looks fine). It works fine on port 80.

**Comment by oxyc** [comment]
I guess it shouldnt matter but you should update your config to match the new default setup.

```yaml
apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
```

This will use

```htaccess
<FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>
```

Rather than

```htaccess
ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/drupalvm/drupal"
```

like the other vhosts.

**Comment by oxyc** [comment]
@adamtyoung did you solve this or are you still having issues?

**Comment by geerlingguy** [comment]
Closing for now; please let me know if this is still an issue for you.

**Comment by pminf** [comment]
I'm struggeling with the same issue. Using CentOS 6 I followed your instructions on http://docs.drupalvm.com/en/latest/configurations/webservers-apache/#enable-ssl-support-with-apache by generating the certificate and adding the following lines to config.yml:
```
apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
```
After `vagrant reload --provision` I get redirected to the apache welcome screen, when I try to access the domain via HTTPS. It prompts me:
> You should add your website content to the directory /var/www/html/
Listing the vhosts gives me:
```
[vagrant@crm conf.d]$ httpd -S
AH00112: Warning: DocumentRoot [/usr/share/php/xhprof_html] does not exist
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server mydomain.dev (/etc/httpd/conf.d/vhosts.conf:4)
         port 80 namevhost mydomain.dev (/etc/httpd/conf.d/vhosts.conf:4)
                 alias www.mydomain.dev
         port 80 namevhost adminer.mydomain.dev (/etc/httpd/conf.d/vhosts.conf:20)
         port 80 namevhost xhprof.mydomain.dev (/etc/httpd/conf.d/vhosts.conf:35)
         port 80 namevhost pimpmylog.mydomain.dev (/etc/httpd/conf.d/vhosts.conf:50)
         port 80 namevhost 192.168.88.89 (/etc/httpd/conf.d/vhosts.conf:65)
                 alias dashboard.mydomain.dev
*:443                  is a NameVirtualHost
         default server mydomain.dev (/etc/httpd/conf.d/ssl.conf:56)
         port 443 namevhost mydomain.dev (/etc/httpd/conf.d/ssl.conf:56)
         port 443 namevhost mydomain.dev (/etc/httpd/conf.d/vhosts.conf:82)
ServerRoot: "/etc/httpd"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/etc/httpd/logs/error_log"
Mutex authdigest-opaque: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
Mutex authdigest-client: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
Mutex authn-socache: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/run/httpd/" mechanism=default
Mutex mpm-accept: using_defaults
PidFile: "/run/httpd/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="apache" id=48 not_used
Group: name="apache" id=48 not_used
```
Is it OK, that mydomain.dev is listed twice (/etc/httpd/conf.d/ssl.conf:56 and /etc/httpd/conf.d/vhosts.conf:82)?

I'm using the latest master (2b3f96fec10d790c098f78ac00f565e9f07b2d7d).
