### ISSUE TITLE
Feature Idea: PAReview.sh as installed extra

### ISSUE THREAD

**Issue by PieterDC** [geerlingguy/drupal-vm#1197]
### Issue Type
Feature Idea

### Summary
Support [PAReview.sh](https://github.com/klausi/pareviewsh) as optional extra because the [Drupal project application checklist](https://www.drupal.org/node/1587704) recommends it as a way to check coding standards and style. And it's better to be able to check those things before pushing Drupal code to a repo.

**Comment by geerlingguy** [comment]
@PieterDC - Definitely a valid request. I've considered adding a few workflow-specific tools to Drupal VM in the past (it is, after all, "Drupal" VM and not "generic PHP CMS VM"). However, since the tool would probably be used only by a small percentage of all Drupal VM users, I'd rather not maintain a separate role and/or functionality to grab the script, put it in place, etc.

However, I would like to document how it can be done quickly/easily in this ticket for those who want to use it—either via a post provision script or task file...

**Comment by geerlingguy** [comment]
Also, note that this script is a wrapper around some tooling that is usually best as part of a Drupal project itself (e.g. how Acquia BLT wraps up coding standards reviews, PHPUnit tests, and Behat tests in a Drupal project codebase)—therefore I've been shying away from adding things like that directly to Drupal VM.

**Comment by geerlingguy** [comment]
Working on this now... I think we can get a script in the example scripts dir that will do 99% of the work, and then you just copy and paste a few variables into your config.yml to get the rest done :)

Testing this on Honeypot now. Apparently I still have a master branch lurking in that project!

**Comment by geerlingguy** [comment]
Tested and working! Basically, you add the following to `config.yml`, and you're off to the races!

```yaml
post_provision_scripts:
  - "../examples/scripts/pareview.sh"

composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: drupal/coder, release: '^8.2' }

nodejs_version: "6.x"
nodejs_npm_global_packages:
  eslint
```
