### ISSUE TITLE
How to change owner or group when syncing with rsync?

### ISSUE THREAD

**Issue by pminf** [geerlingguy/drupal-vm#1199]
Currently I'm struggling with permission issues in my Drupal installation. I'm syncing with rsync which leads to owner and group `vagrant` of synced files and folders. Because apache is running with user `www-data` files cannot be written in `sites/default/files`. That's why I'm trying to change the group of synced files to `www-data`. How do I accomplish this?

### Issue Type
 - Support Request

### My Environment
```
Vagrant 1.9.1
sh.exe": vboxmanage: command not found
VirtualBox
sh.exe": ansible: command not found
```

### My OS

Microsoft Windows [Version 10.0.14393]

### Summary

I've already tried the following settings in `config.yml`:
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    destination: /var/www/myproject.dev
    type: rsync
    create: true
    options_override:
      group: www-data
```
or
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    destination: /var/www/myproject.dev
    type: rsync
    create: true
    group: www-data
```
These don't take effect after `vagrant reload`. When I check `.vagrant/machines/mydrupalvmbox/virtualbox/syncedfolders` `group` is still `vagrant`. Changing the group in this temp file and doing a `vagrant rsync` results the correct group for rsynced files and directories. But after `vagrant reload` those temp settings are gone and group `vagrant` is back again.

I've also tried to change the group via `rsync_args` with no success:
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    destination: /var/www/myproject.dev
    type: rsync
    create: true
   options_override:
     rsync__args: [
       "--verbose", "--archive", "--delete",
       "--chmod=gu=rwX,o=rX",
       "--group", # required for the following command
       "--groupmap=*:www-data"
     ]
```
I get an error: `Error: rsync: --groupmap=*:www-data: unknown option`.

**Comment by geerlingguy** [comment]
I'll leave this ticket open here for a time to let anyone else using rsync have a chance to chime in, but I wonder if this might be something better suited to a Vagrant issue queue or stack overflow, since it's not really Drupal-VM-specfic.

**Comment by geerlingguy** [comment]
Also, have you read through Vagrant's `rsync_chown` documentation? https://www.vagrantup.com/docs/synced-folders/rsync.html#rsync_chown

**Comment by pminf** [comment]
Yes, I've read this. As long `rsync__chown` is true (which is default), `owner` and `group` should take effect. 

I thought this is a Drupal-VM specific issue because my settings in config.yml regarding ownership don't reflect in `.vagrant/machines/mydrupalvmbox/virtualbox/syncedfolders`.

I will ask at SO anyway and will reply here, if I get an answer.

**Comment by geerlingguy** [comment]
@pminf - Thanks! And one other thing—what version of VirtualBox are you running? I know there are a few sticky issues with 5.1.16 on Windows at least (are you on Windows?).

**Comment by oxyc** [comment]
Afaik your first example should work, but for reference this is what I use and it does work.

```yaml
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupalvm
    type: rsync
    create: true
    excluded_paths: ['.git/', '.tmp/', 'node_modules/']
    options_override:
      rsync__chown: false
      rsync__args: [
        "--archive", "--delete", "--copy-links",
        "--owner", "--group", "--usermap=*:vagrant", "--groupmap=*:www-data",
      ]
```

**Comment by geerlingguy** [comment]
@oxyc good catch! That could be it.

**Comment by pminf** [comment]
I'm using the newest version of Virtual Box (5.1.16 r113841), Vagrant(1.9.2) and Drupal-VM. My rsync is kind of out-dated ([3.0.8](https://sourceforge.net/projects/mingw/files/MSYS/Extension/rsync/)), but it is the newest version I could find, which is not based on cygwin. With cwRsync I was not able to get vagrant syncing to work at all.

@oxyc Could you please tell me, which rsync you are using? I would really apprichiate a tutorial and/or download link.

@geerlingguy I've noticed, that the generated temp syncfolders json has a duplicate group key. The first has the value `www-data`, the second one has `vagrant`. I guess the last one is overwriting the first, so that in the end group is `vagrant`. If you think this is a general vagrant issue feel free to close this ticket. I will open a new one.
```
{
   "rsync":{
      "/var/www/myproject.dev":{
         "type":"rsync",
         "rsync__auto":"true",
         "rsync__exclude":[
            "vm",
            ".git",
            ".idea",
            ".sass-cache",
            "node_modules",
            "bower_components",
            "default/files"
         ],
         "rsync__args":[
            "--verbose",
            "--archive",
            "--delete",
            "-z",
            "--chmod=ugo=rwX"
         ],
         "rsync__chown":true,
         "id":null,
         "create":true,
         "mount_options":[

         ],
         "group":"www-data",
         "guestpath":"/var/www/myproject.dev",
         "hostpath":"C:/#/myproject",
         "disabled":false,
         "__vagrantfile":true,
         "auto":"true",
         "exclude":[
            "vm",
            ".git",
            ".idea",
            ".sass-cache",
            "node_modules",
            "bower_components",
            "default/files"
         ],
         "args":[
            "--verbose",
            "--archive",
            "--delete",
            "-z",
            "--chmod=ugo=rwX"
         ],
         "chown":true,
         "owner":"vagrant",
         "group":"vagrant"
      },
      "/vagrant":{
         "type":"rsync",
         "guestpath":"/vagrant",
         "hostpath":"C:/#/myproject/vm",
         "disabled":false,
         "__vagrantfile":true,
         "owner":"vagrant",
         "group":"vagrant"
      }
   }
}
```

**Comment by oxyc** [comment]
Does it work with:

```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    destination: /var/www/myproject.dev
    type: rsync
    create: true
    options_override:
      rsync__group: www-data
```

**Comment by pminf** [comment]
Jackpot! Thank you very much. So to sum up, the following **does work**:
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    // [...]
    options_override:
      rsync__group: www-data
```
and this **does not work**:
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    // [...]
    options_override:
      group: www-data
```
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    // [...]
    rsync__group: www-data
```
```
vagrant_synced_folders:
  - local_path: C:\#\myproject
    // [...]
    group: www-data
```

1. I guess it would be better, if the group key would map to `rsync_group`.
2. Why is `vagrant` the default group, while apache is run by user vagrant? This leads to permission issues in a drupal installation (files), if you don't change the group. Or I am wrong?
3. `rsync_group` is missing in the documentation.
