### ISSUE TITLE
4.3.0 Release tasks

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1200]
Working on the 4.3.0 release...

  - [x] Update CHANGELOG
  - [x] Cut a <s>rug</s> tag
  - [x] Add tag release notes
  - [x] Submit PR to update BLT
  - [ ] Blog post on Planet (talk about `geerlingguy.drupal` role and also pidramble updates)

**Comment by geerlingguy** [comment]
I need to fix the build failure first... looks like it's related to [a Firewall role update](https://github.com/geerlingguy/drupal-vm/commit/972a86b0ec72fb11f48f8b21ce06a0bd1e0cd341) I just pushed.

**Comment by geerlingguy** [comment]
So... the Firewall issue is something related to Travis or the Docker setup—it's not directly related to the Firewall role itself 😱

**Comment by geerlingguy** [comment]
Strange, it hangs for me locally too. But if I do a `docker stop` and `docker start`, then run the playbook again, it completes successfully. Something maybe wrong with the service file? It works when testing on the role's own Travis rig...

**Comment by geerlingguy** [comment]
Possibly related? https://github.com/ansible/ansible/issues/19763#issuecomment-285494166

**Comment by geerlingguy** [comment]
I've tracked it down to this task:

```yaml
- name: Get software for Python-based control.
  yum: "name={{ item }} state=installed"
  with_items:
    - "curl"
    - "python-pycurl"
    - "@development"
    - "unzip"
```

Using that, I can reproduce the hang in the Firewall role itself.
