### ISSUE TITLE
Composer timeouts and slowness due to default use of vboxsf on Windows

### ISSUE THREAD

**Issue by fb-multimedia** [geerlingguy/drupal-vm#1242]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
vagrant 1.9.2
Virtualbox 5.1.10

```

### Your OS

 - Windows 8.1

### Summary

Hello,
I know it's not the first report for this error, but I haven't find solution.
After many try I can't use composer to create a new drupal 8 project :
composer create-project drupal-composer/drupal-project:8.x-dev drupal8 --stability dev --no-interaction
I always have a composer timeout and the message "couldn't delete web/core"
I have try to install in another directory instead of the share folder but same problem.
I have change the COMPOSER_PROCESS_TIMEOUT: 1200
Can somebody confirm that this command actually work good with drupal vm under windows with default share folder ?
Thanks.

**Comment by geerlingguy** [comment]
@fb-multimedia - If you're on an older computer (especially if you don't have an SSD), or if you're using native shared folders, or if you have a slower Internet connection, or if your Internet connection is behind a firewall or proxy, you may have issues with the command.

Are you having trouble running that command manually, or does Drupal VM show a failure during `vagrant up` or `vagrant provision` when it builds a Drupal codebase as per its default configuration?

Did you set the timeout like: `COMPOSER_PROCESS_TIMEOUT=2000 composer create-project drupal-composer/drupal-project...` or some other way?

And does it do anything, or does it just hang after you run the command? If it's doing stuff, and failing at 1200 seconds, then maybe you need to increase the timeout to 2000, 3000, or even more (again, depends on your environment).

**Comment by fb-multimedia** [comment]
Thanks for your answer.
It fails on vagrant up or if I run the command under the VM. Finally the composer command work under /var but not in /var/www (my default shared folder)
So I think the problem come from the shared folder type. 
I have try to change for nfs but It doesn't work (can't see any winnfsd.exe process launch with vagrant-winnfsd installed). 
If I change type to smb vagrant up fails too. Should I install samba on the VM before changing the type on config.yml ? (I haven't found explainations for smb share)
Thanks

**Comment by geerlingguy** [comment]
@fb-multimedia - Ah, in that case it was definitely the shared folder type. The default `vboxsf` type is extremely slow in Windows 7/8 (and even in 10), and that will definitely lead to a Composer timeout.

The best option for speed is to use `rsync` as the type, but that has its own tradeoffs. Other than that, `smb` should 'just work' out of the box, but you have to use a terminal emulator like Cmder or Cygwin, and you have to run it as an administrator (otherwise the directory permissions get broken).

See these two guides for more information:

  - http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/
  - http://docs.drupalvm.com/en/latest/getting-started/installation-windows/#troubleshooting-vagrant-synced-folders

Another option—though it won't help with performance—is to extend Composer's timeout.

**Comment by oxyc** [comment]
The setup that I use is to have `rsync` for everything except the configuration sync directory

```yaml
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupal
    id: drupal
    type: rsync
    create: true
    excluded_paths: ['.git/', '.tmp/', 'node_modules/', 'sites/default/files/', 'config/drupal', 'config/salt.txt']
    options_override:
      owner: vagrant
      group: www-data
      rsync__args: [
        "--verbose", "--archive", "--delete",
      ]
  # Use slower but two-way NFS sync for configuration sync directory.
  - local_path: config/drupal
    destination: /var/www/drupal/config/drupal
    type: "" # On windows, on macOS "nfs"
    create: true
```
