### ISSUE TITLE
 both Drupal 7 and Drupal 8 

### ISSUE THREAD

**Issue by zetnet** [geerlingguy/drupal-vm#1266]
Is it possible to have both Drupal7 and 8, two different sites. on the same Drupal VM instance ?

**Comment by geerlingguy** [comment]
Yep! You'd do the same kind of setup as the [multisite docs](http://docs.drupalvm.com/en/latest/deployment/multisite/) mention. Instead of pointing each virtualhost to the same docroot, you'd point each virtualhost to a different docroot. And you can add multiple `vagrant_synced_folders` entries, one for each site.

For example:

```yaml
vagrant_synced_folders:
  - local_path: ~/Sites/mysite1-d8
    destination: /var/www/mysite1-d8
    type: nfs
  - local_path: ~/Sites/mysite2-d7
    destination: /var/www/mysite2-d7
    type: nfs

apache_vhosts:
  - servername: "local.mysite1.com"
    documentroot: "/var/www/mysite1-d8"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.mysite2.com"
    documentroot: "/var/www/mysite2-d7"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

mysql_databases:
  - name: mysite1
    encoding: utf8
    collation: utf8_general_ci
  - name: mysite2
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: mysite1
    host: "%"
    password: drupal
    priv: "mysite1.*:ALL"
  - name: mysite2
    host: "%"
    password: drupal
    priv: "mysite2.*:ALL"
```
