### ISSUE TITLE
There was an error when attempting to rsync a synced folder.

### ISSUE THREAD

**Issue by zetnet** [geerlingguy/drupal-vm#1270]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
c:\D\Sites\drupalvmz
λ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 1.9.2
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

Windows 10 with VirtualBox

### Full console output

https://gist.github.com/zetnet/4c5f5cc3b2a95e257d368b85666b902f
### Summary

After seeing vagrant up , reload , or provision is taking much too long on my windows machine after any small changes like php_memory_limit, I change nfs to rsync .
after Rsyncing folder: /c/D/Sites/drupalvmz/ => /var/www/drupalvm  for a while,  vagrant won't start and gives the error pasted in the gist above.

**Comment by geerlingguy** [comment]
@zetnet - It looks like the errors are:

```
Error: file has vanished: "/c/D/Sites/drupalvmz/drupal/vendor/drupal/console/bin/php-parse"
file has vanished: "/c/D/Sites/drupalvmz/drupal/vendor/drupal/console/bin/psysh"
```

Did you do any composer-related things or delete anything while `vagrant` commands were running?

Also, is this a BLT-built project, or something else? And what terminal emulator are you using? (Looks like Cmder, but I can't be sure).

**Comment by zetnet** [comment]
The error might have come from the fact that I was having twice the local_path and destination, while trying to use  both drupal 7 and 8 on the same VM,  and playing a bit with conf and the paths I did not payed attention.

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
```

Now the error is gone , but I'm also  back to nfs. I'll check it out at a later time to change again nfs to rsync .
