### ISSUE TITLE
Task "geerlingguy.drupal : Run database updates" fails when using multisite (deploying to production)

### ISSUE THREAD

**Issue by mglaman** [geerlingguy/drupal-vm#1284]
### Issue Type
 - Bug Report / Support Request

### Your Environment

This is when deploying to production. No Ansible.

### Your OS

Ubuntu 16.04.2 x64

### Full console output

https://gist.github.com/mglaman/94394f2d1095e7b9608b30c64967defb

### Summary

I ran the deploy to production provisioning command in a multisite setup

```
DRUPALVM_ENV=prod ansible-playbook -i vm/inventory \
  vendor/geerlingguy/drupal-vm/provisioning/playbook.yml \
  -e "config_dir=$(pwd)/vm" \
  --sudo --ask-sudo-pass \
  --tags=drupal
```

Ended up with following error

```
TASK [geerlingguy.drupal : Run database updates.] ******************************
fatal: [162.243.207.46]: FAILED! => {"changed": true, "cmd": ["drush", "updatedb", "-y"], "delta": "0:00:00.322783", "end": "2017-04-07 14:43:28.342426", "failed": true, "rc": 1, "start": "2017-04-07 14:43:28.019643", "stderr": "Command updatedb needs a higher bootstrap level to run - you will    \u001b[31;40m\u001b[1m[error]\u001b[0m\nneed to invoke drush from a more functional Drupal environment to run\nthis command.\nThe drush command 'updatedb' could not be executed.                  \u001b[31;40m\u001b[1m[error]\u001b[0m", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by mglaman** [comment]
When reviewing the Drupal role I see

```

- name: Define drupal_deploy_updated
  set_fact:
    drupal_deploy_updated: "{{ drupal_deploy_repo_updated.changed|default(false) }}"

# Run update tasks if Drupal was updated.
- include: tasks/update.yml
  when: drupal_deploy_updated and drupal_site_exists
  static: no
```

It seems there is no way to prevent this task from running. If the repo changes it will always run, and assumes there is a site at `default`. So not sure if this should be moved to the `geerlingguy/ansible-role-drupal` repo.
