### ISSUE TITLE
Way to set environment variables for the provisioned server? (out of the box?)

### ISSUE THREAD

**Issue by mglaman** [geerlingguy/drupal-vm#1299]
### Issue Type

 - Support Request

### Summary

I know there is a way to do this in Ansible overall, but is there a way within DrupalVM to define environment variables? Such as a way to flag the environment (VAGRANT, PROD, etc.) Or to keep API keys out of Drupal (Platform.sh style, stored via Ansible Vault!)

**Comment by oxyc** [comment]
For environment variables you could:
1. Add a [post-provision script](http://docs.drupalvm.com/en/latest/extending/scripts/#shell-scripts) that writes them to an autoloaded file in eg `/etc/profile.d`.
2. Use an Apache `SetEnv` directive for the virtual host like [beetbox does](https://github.com/beetboxvm/beetbox/blob/d103de4179bda10b1d0d043a14713230d36817d6/provisioning/ansible/config/default.config.yml#L46).

As for secrets and Ansible Vault, [Drupal VM reads a `secret.yml`](http://docs.drupalvm.com/en/latest/other/production/#ansible-vault-support) if available.

**Comment by mglaman** [comment]
So the `secrets.yml` will store random variables in Ansible. I'd have to get my own task to run and ready that.

OR do `apache_vhost_php_fpm_parameters` in my Vagrant/Prod/Blah `config.yml` variants and add my environment variables. OR have my main `config.yml` have that but in another variable and define it across the board.

I'll give it a try and do my best to report back, and maybe open a docs PR on this (it'd be a big win for using DrupalVM as way to manage local + stage + prod env vars.)

**Comment by geerlingguy** [comment]
@mglaman - Have you tried this yet? Any success? I missed you at your session earlier today, but hope it was good!

**Comment by oxyc** [comment]
Thought I'd comment for future reference on a somewhat related matter. But rather than environemnt variables, how to identify that it's a VM within a `.htaccess` file.

I wanted to disable expires headers in development while still tracking the `.htaccess` and found this https://serverfault.com/a/523169/144932.

So I added a post post provision task.

```yaml
---
- name: Define Apache development variable.
  lineinfile:
    path: /etc/apache2/envvars
    regexp: '^export APACHE_ARGUMENTS='
    line: 'export APACHE_ARGUMENTS=-DDEVELOPMENT'
  when: ansible_os_family == 'Debian' and drupalvm_webserver == 'apache'

- name: Define Apache development variable.
  lineinfile:
    path: /etc/sysconfig/httpd
    regexp: '^OPTIONS='
    line: 'OPTIONS=-DDEVELOPMENT'
  when: ansible_os_family == 'RedHat' and drupalvm_webserver == 'apache'
```

Then wrapped the expires section in an `IfDefine` block.

```apache
<IfDefine !DEVELOPMENT>
  <IfModule mod_expires.c>
    ExpiresActive On
    ExpiresDefault                                      "access plus 1 month"
    ExpiresByType text/css                              "access plus 1 year"
    ...
  </IfModule>
</IfDefine>
```

**Comment by heddn** [comment]
Setting apache's environment variables works fine, if you always run in Apache. I'm trying to set `SIMPLESAMLPHP_CONFIG_DIR` so I can re-position the location of the config dir for simple saml. Now all my drush commands fail because the environment variable doesn't exist.

**Comment by heddn** [comment]
How hard would it be to wire something like https://galaxy.ansible.com/franklinkim/environment/ in as a custom task to run after provision?

**Comment by heddn** [comment]
For those who want this now, here's how I did it with a post-provision ansible task.

```
# config.yml
post_provision_tasks_dir: "{{ config_dir }}/scripts/drupalvm/*.yml"
```

```
# scripts/drupalvm/environment.yml
---
- name: Add line to environment file to denote the location of the saml config.
  lineinfile:
    dest: /etc/environment
    line: "SIMPLESAMLPHP_CONFIG_DIR={{ drupal_composer_install_dir }}/config/saml"
    regexp: "^SIMPLESAMLPHP_CONFIG_DIR"
```
