### ISSUE TITLE
root:root still owns /var/www/drupalvm

### ISSUE THREAD

**Issue by nvahalik** [geerlingguy/drupal-vm#1303]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.18
```

### Your OS

 - **Windows** 7 Professional (Build 7601: Service Pack 1)

### Full console output

**Note that Vagrant provisioning runs correctly, but `/var/www/drupalvm` is `root:root`**

### Summary

Site with existing code base doesn't work because of the issue listed above. Here is my `config.yml`:

```
---
vagrant_box: geerlingguy/ubuntu1204
vagrant_hostname: mysite.dvm
vagrant_machine_name: mysite-dvm

vagrant_ip: 192.168.88.10
vagrant_cpus: 2
vagrant_memory: 4096
drupalvm_user: vagrant

drupal_install_site: false
drupal_build_composer_project: false
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
drupal_major_version: 7

vagrant_synced_folder_default_type: ""

vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: ""
    create: true

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  - solr
  # - upload-progress
  - varnish
  - xdebug
  - xhprof

extra_packages: []
 
php_version: "5.6"
php_memory_limit: "256M"
solr_version: "4.5.1"
```
