### ISSUE TITLE
Is it possible to let Drupal VM built multiple Drupal sites (e.g. Drupal 7 and Drupal 8)  with a Drush make file?

### ISSUE THREAD

**Issue by luxio** [geerlingguy/drupal-vm#1336]
Is it possible to let Drupal VM built multiple Drupal sites (e.g. Drupal 7 and Drupal 8)  with a Drush make file?

Or do I have to add the second Drupal Site manually by using a local Drupal code base  as mentioned in the [doc](http://docs.drupalvm.com/en/latest/deployment/local-codebase/)

**Comment by geerlingguy** [comment]
At this time, the actual building of makefiles or composer.json files is restricted to one site/app per Drupal VM instance.

If you're building your own playbook or want to fork Drupal VM to be able to support this, you could do something like (note this is totally untested, just an idea):

```yaml
drupal_sites:
  - drupal_docroot: '/path/to/docroot1'
    drupal_build_makefile: yes
    [...]
  - drupal_docroot: '/path/to/docroot2'
    drupal_build_makefile: yes
    [...]
```

Then in your playbook:

```yaml
  tasks:
    - include_role:
      role: geerlingguy.drupal
      with_items: drupal_sites
```

But I'm closing this issue as that's not something I'd like to _officially_ support, just because of the extra complexity it would introduce (especially as Drupal VM is slowly but surely transforming into a dev tool you would add to a Composer-based project).
