### ISSUE TITLE
Behat @javascript tests aren't working

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#1342]
I have Drupal VM 4.4.5 with ubuntu1404.
I made an upgrade from DVM 4.4.4 then I did `vagrant provision` a couple times.
I used this manual to establish Behat - http://docs.drupalvm.com/en/latest/extras/selenium/ .

When I run a behat scenario with `@javascript` I get following:
```
      Could not open connection: Curl error thrown for http POST to http://test7.drupalvm.dev:4444/wd/hub/session with params: {"desiredCapabilities":{"tags":["drupalvm","PHP 5.6.30-10+deb.sury.org~trusty+2"],"browser":"firefox","ignoreZoomSetting":false,"name":"Behat feature suite","browserName":"firefox"}}
      
      Failed to connect to test7.drupalvm.dev port 4444: Connection refused (Behat\Mink\Exception\DriverException)
```
I read some issues about such problem but I can not find a solution.
1. Why the port 4444 is failed?  It is on firewall_allowed_tcp_ports:`.
2. Why does it try to run firefox? I read now Chrome should work.

Regards, Artu

**Comment by ArtuGit** [comment]
I see the only working solution now is using of PhantomJS as a browser for Mink.
How can I setup it?

I included  `phantomjs` to `nodejs_npm_global_packages`.
What should I fo further?

Why does it fail to connect to port 4444?

**Comment by geerlingguy** [comment]
@ArtuGit - Are you running the `behat` commands inside the VM or on the host? If so, it wouldn't be able to connect through to port 4444 since that's meant to only be accessed inside Drupal VM.

Also, can you share what you have set up in your `behat.yml`.

**Comment by ArtuGit** [comment]
@geerlingguy 
Of course, I am running it inside DVM.

My project `behat.yml`:
```
default:
  suites:
    web_features:
      paths: [ %paths.base%/features/web ]
      contexts:
        - WebContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://test7.drupalvm.dev:4444/wd/hub
      base_url: http://test7.drupalvm.dev
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '/var/www/drupalvm/test7/web'
      region_map:
        content: "#content"
```
