### ISSUE TITLE
Docker error on load

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#1388]
### Issue Type
 Bug Report / Support Request

### Your Environment

```
nerdstein@Adams-MBP-2 box $ docker-compose up -d
Creating network "box_drupalvm" with driver "bridge"
Pulling drupal-vm (drupal-vm:latest)...
ERROR: repository drupal-vm not found: does not exist or no pull access
```

### Your OS
**macOS** 10.12.5

### Full console output

See above

### Summary

I created a config.yml and overrode the following:

```
vagrant_hostname: nerdstein.local
vagrant_machine_name: nerdstein
vagrant_ip: 192.168.88.88


drupal_composer_project_options: "--prefer-source --stability dev --no-interaction"

installed_extras:
  - drush

drush_version: "8.1.11"


vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ../code
    destination: /var/www/drupalvm
    type: nfs
    create: true
```

I have the following docker-compose.yml:

```
version: "3"

services:

  drupal-vm:

    # Switch the image to `geerlingguy/drupal-vm` to use Drupal VM defaults.
    image: drupal-vm
    # Comment out 'image' and uncomment the line below if customizing Drupal VM
    # with a project-specific Dockerfile in the same directory as this file.
    # build: .

    # Set this to your project's machine name (e.g. example-com)
    container_name: nerdstein-d8

    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 8025:8025

    # Not strictly required, but custom DNS settings can help with stability.
    dns:
      - '8.8.8.8'
      - '8.8.4.4'

    # Use of the `delegated` option currently requires the Docker Edge release.
    volumes:
      - ./:/var/www/drupalvm/:rw,delegated

    privileged: true
    command: /lib/systemd/systemd

    networks:
      drupalvm:
        # Set this IP address to something different if you already have another
        # service running on the default IP address. If you change the subnet,
        # you need to also change the bridge network IP and subnet below.
        ipv4_address: 192.168.88.88

networks:

  # This custom network allows Drupal VM to be accessed on an IP address.
  drupalvm:
    driver: bridge
    driver_opts:
      ip: 192.168.88.1
    ipam:
      config:
        - subnet: "192.168.88.0/16"
```

I received the error above after running `docker-compose up -d`
