### ISSUE TITLE
ansible-role-php-versions not using config/config.yml settings.

### ISSUE THREAD

**Issue by gheydon** [geerlingguy/drupal-vm#1413]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VMWare Fusion 8.5
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

### Your OS

 - **macOS** 10.11

### Summary

I have installed drupalvm using composer

```
{
    "require-dev": {
        "geerlingguy/drupal-vm": "^4.5"
    }
}
```
with the following config/config.yml

```
---
vagrant_box: geerlingguy/ubuntu1404
vagrant_hostname: anzrr.dev
vagrant_machine_name: anzrr
vagrant_ip: 0.0.0.0

vagrant_synced_folders:
  - local_path: .
    destination: /var/www/wordpress
    type: nfs
    create: true

# Needs to match with what we have in .env and vagrant_synced_folders.
drupal_core_path: "/var/www/wordpress/web"
drupal_domain: "{{ vagrant_hostname }}"
drupal_db_user: wordpress
drupal_db_password: wordpress
drupal_db_name: wordpress

drupal_deploy: true
drupal_deploy_repo: "git@bitbucket.org:outware/roadrunner-wordpress.git"

# Disable Drupal specific features.
drupal_build_composer_project: false
drupal_install_site: false
configure_drush_aliases: false

# Remove some Drupal extras such as `drupalconsole` and `drush`
installed_extras:
  - adminer
  - mailhog
  - pimpmylog
  - upload-progress
  - xdebug
  - xhprof # use `tideways` if you're installing PHP 7+

php_version: "5"
php_xdebug_idekey: netbeans-xdebug

php_packages:
  - php5-common
  - php5-cli
  - php5-dev
  - php5-fpm
  - libpcre3-dev
  - php5-gd
  - php5-curl
  - php5-imap
  - php5-json
  - php-xml
  - php-mbstring
  - php-sqlite3
  - php-apcu

# Add wp-cli
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: wp-cli/wp-cli, release: '^1.0.0' }
```

If I checkout DrupalVM and then create the config.yml using the above php-versions will using the php_packages variable, but if I create this using composer it will rewrite the php_packages with php{{ php_version }}-nnn

I have run the provisioning with verbose enabled and it is loading the config.yml, but it is not being used when it gets to php-versions.
