### ISSUE TITLE
Apache vhost configuration

### ISSUE THREAD

**Issue by liamhendricks** [geerlingguy/drupal-vm#1416]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

### Your OS
 - **macOS** (version)

### Summary
Hey guys, I am having some trouble setting up apache virtual hosts. I followed the advice given in this issue (https://github.com/geerlingguy/drupal-vm/issues/168), but when I try to access one of the virtual hosts from the browser, I get the chrome error `ERR_ICANN_NAME_COLLISION`. Any host besides `drupalvm.dev` gives this.

The VM builds just fine, no errors. I can access the root host just fine at `drupalvm.dev`, but no other host is accessible. I've probably configured it wrong.

Here is some output:
Relevant snippets from config.yml
```
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "site.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_site_path }}"
```
```
vagrant_synced_folders:
  - local_path: /Users/liamhendricks/localdev/repository/site1/docroot
    destination: /var/www/drupalvm
    type: nfs
    create: true

  - local_path: /Users/liamhendricks/localdev/repository/site2/docroot/
    destination: /var/www/site
    type: nfs
    create: true
```
```
drupal_core_path: "/var/www/drupalvm"
drupal_core_owner: "{{ drupalvm_user }}"
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

drupal_site_path: "/var/www/site"
drupal_site_owner: "{{ drupalvm_user }}"
drupal_site_db_user: site
drupal_site_db_password: site
drupal_site_db_name: site

```
I can `vagrant ssh` into the machine and run `apache2ctl -S`
```
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server drupalvm.dev (/etc/apache2/sites-enabled/vhosts.conf:4)
         port 80 namevhost drupalvm.dev (/etc/apache2/sites-enabled/vhosts.conf:4)
                 alias www.drupalvm.dev
         port 80 namevhost site.drupalvm.dev (/etc/apache2/sites-enabled/vhosts.conf:20)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/lock/apache2" mechanism=fcntl
Mutex watchdog-callback: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used
```

Please let me know if I need to provide some more information. I've never tried to configure drupalvm with multiple sites/hosts so I've probably done something wrong.

Thanks!
