### ISSUE TITLE
Allow multiple pre/post provision task directories

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1437]
### Issue Type

 - Feature Idea

### Summary

Currently we're only allowing users to set one path for pre and post provision tasks. I'm not sure why we did this, but it might be the [vague documentation](http://docs.ansible.com/ansible/playbooks_loops.html#id4).

At least with ansible 2.3.1.0 `with_fileglob` supports both strings and lists. I guess we believed it had to be a list? Both of the following work as expected:

```yaml
    - name: Copy each file over that matches the given pattern
      copy:
        src: "{{ item }}"
        dest: "/etc/fooapp/"
      with_fileglob:
        - "/playbooks/files/fooapp/*"

    - name: Copy each file over that matches the given pattern
      copy:
        src: "{{ item }}"
        dest: "/etc/fooapp/"
      with_fileglob: "/playbooks/files/fooapp/*"
```

I suggest we change how Drupal VM runs the pre/post provision tasks so that user is free to use either a single path as a string or a list to multiple paths.

```yaml
pre_provision_tasks_dir: "{{ config_dir }}/tasks/pre/*.yml" 
post_provision_tasks_dir:
 - "{{ config_dir }}/tasks/post/*.yml" 
 - "{{ config_dir }}/tasks/drupal/*.yml"
