### ISSUE TITLE
msodbcsql/mssql-tools Package is not installing correctly.

### ISSUE THREAD

**Issue by jonnyeom** [geerlingguy/drupal-vm#1442]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
```

### Your OS

 - **Linux** (Ubuntu 16.04)

### Full console output

https://gist.github.com/jonnyeom/6af122d82e4abd24d74a6589e08d674b

### Summary

I ran into this error while provisioning.

I believe the problem is that the **msodbcsql** package and **mssql-tools** needs a **yes** confirmation when getting installed. Microsoft recommends using the `ACCEPT_EULA=Y` flag when installing this package, as shown [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server). 

I may be wrong but hope this helps.

**Comment by oxyc** [comment]
I think this is best installed as a custom [post provision task](http://docs.drupalvm.com/en/latest/extending/scripts/#ansible-task-files).

Something similar to:

```yaml
---
- apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main"
    state: present
  register: odbc_repo

- apt: update_cache=yes
  when: odbc_repo.changed

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - msodbcsql
    - mssql-tools
  environment:
    ACCEPT_EULA: Y

- lineinfile:
    path: /etc/environment
    line: 'PATH="$PATH:/opt/mssql-tools/bin"'
```
