### ISSUE TITLE
Slow Drupal installation behind corporate firewall and proxy

### ISSUE THREAD

**Issue by Fynkymynky** [geerlingguy/drupal-vm#1458]
### Issue Type

 - Support Request

### Your Environment

```
latest ansible , vagrant and virtualbox
```

### Your OS

 - **macOS** (10)

### Summary
The provisioning process is extremely slow behind my corporate firewall, I've set the proxy settings through Vagrant but the whole process is really slow, especially with the downloading and installing of Drupal. Is there a setting where I can speed up the downloading and installing of Drupal?

**Comment by geerlingguy** [comment]
There are a number of things that could contribute to slow speeds. Can you give any benchmarks—e.g. how long is it taking to do a full `vagrant up` or `vagrant provision`? And if you use `composer` on your Mac directly (not via Drupal VM) to run `composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`, how long does that take?

Finally, do you have Drupal VM set to use NFS (the default) for the shared folder?

**Comment by Fynkymynky** [comment]
Hi,

The machine is currently building so I'm unable to give exact benchmark at this time, but it took around 2 hours.

No changes were made to the config.yml file is has

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
```

When running the composer command on my machine outside of the VM I get the following error

```
[Composer\Downloader\TransportException]                                                                                           
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol                                                                
  Failed to enable crypto                                                                                                            
  failed to open stream: operation failed               
```

I've exported all proxy paths to http and https. But it works within the VM just incredibly slowly.
