### ISSUE TITLE
Add PostgreSQL support

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#146]
With https://www.drupal.org/node/2157455 finally having been completed, it would be nice if users could switch from MySQL/MariaDB/Percona to PostgreSQL (at least for Drupal 8) optionally.

I don't currently have a Postgres role, but could add one or find a good one in Galaxy. Besides also installing `php-mysql`, there's not much else that needs to be conditionally changed besides swapping out Posgres for MySQL.

**Comment by gitoutthere** [comment]
This actually what I need at the moment, being able to add geerlingguy.pgsl to playbook along side with the PHP connector

**Comment by gitoutthere** [comment]
I used ANXS.postgresql seems to be working ok

**Comment by geerlingguy** [comment]
@gitoutthere - Could you leave some instructions for what changes you made in this issue, so I can point others interested in trying out Postgres with Drupal here? I'm still planning on adding 'official' support sometime, but would be glad to 'unofficially' support it as best I can for now.

**Comment by gitoutthere** [comment]
@geerlingguy cool I am still trying to wrestle and get my Envs setup. But here is the steps I took to get Postgres working, in your vagrant folder:
1) Add 'ANXS.postgresql' to '/provisioning/requirements.txt'
2) Run `sudo ansible-galaxy install -r provisioning/requirements.txt --force` to install the new plugin.
3) Modify your '/provisioning/playbook.yml' and add `- ANXS.postgresql` to the roles.
4) Override settings on '/config.yml'. Config can be found on https://github.com/ANXS/postgresql

**Comment by JorisVanEijden** [comment]
**ANXS.postgresql** seems to be Ubuntu only.
I've been using **patrik.uytterhoeven.PostgreSQL-For-RHEL6x** for CentOS 5,6 and 7

Would love to see these combined into a **geerlingguy.postgresql** role :+1:

**Comment by geerlingguy** [comment]
@JorisVanEijden - heh, always the optimist! I'll see what I can do, now that everything in Drupal 8 is running and tested with Postgres.

**Comment by JorisVanEijden** [comment]
Well, 13 of the 14 galaxy roles in use here at oneshoe are geerlingguy roles. I'd say our infra has been pretty much geerlinged since buying your book half a year ago :wink:

**Comment by gitoutthere** [comment]
Any of you guys are here at DrupalCon? I would love to catch up with you.

**Comment by geerlingguy** [comment]
@gitoutthere - I wish! Watching presentations remotely, and participating in Twitter, but not much else.

**Comment by kevinquillen** [comment]
I am going to give this a shot this weekend.

**Comment by oxyc** [comment]
It seems `ANXS.postgresql` supports Centos now: https://github.com/ANXS/postgresql/issues/141#issuecomment-171807987

**Comment by oxyc** [comment]
I've got a testable PR for this #490.

**Comment by DougDavenport** [comment]
Greetings,

Wondering what is the status of PostgreSQL?

**Comment by geerlingguy** [comment]
@DougDavenport - This is not a high priority for me right now, though I still do want to add at least minimal support.

I currently don't have any Drupal sites using Postgres, and know _very_ few people who do, so just like with HHVM, it's kind of a niche use case that is more on the back burner for this project.

**Comment by DougDavenport** [comment]
Thanks, we are new to using Drupal and have good experience with Postgres on other projects. I have noticed comments that some Drupal modules are said not to support Postgres. We are flexible, what are the pros/cons of the other DB choices? What do you advise?

**Comment by geerlingguy** [comment]
The Drupal community (and most other PHP CMS communities) has traditionally only supported MySQL (and by extension, MariaDB). While other databases have had varying levels of support, none are as widely used and supported as My/Maria, so some modules and even some older Drupal core components had queries that were either optimized for MySQL or would fail in interesting ways on other relational databases.

With Drupal 8, Postgres support is a lot better, but it's still very slow in the uptake in the Drupal community, so I'm putting this on the backburner, but I definitely want to get to it soon so it's easier for people to compare the same site under Postgres vs. MySQL vs. MariaDB.

**Comment by laceysanderson** [comment]
For what it's worth, PostgreSQL support is very important for those of us who use [Tripal](https://www.drupal.org/project/tripal). Tripal provides support for storing data related to biology/agriculture research in a Drupal website and facilitates storing, organization and analysis of that data. However, it requires PostgreSQL because the community developed schema (used by a host of open-source analysis/viewer programs, not just Tripal) has PostgreSQL-specific features.

As a Tripal developer, I would really like to use and encourage others to use the Drupal VM since most Tripal/Drupal sites (currently 91 instances) will need to develop extensions and customizations but won't have the resources to use/own a dedicated development server.

I'm going to try to get PostgreSQL working as it seems others have earlier in the queue but I have no vagrant experience so any help or guidance would be VERY much appreciated!

**Comment by oxyc** [comment]
@laceysanderson at the moment there's no easy way to add it :/

You would have to cancel and redo a lot of the stuff Drupal VM does. This would be what you have to do at the moment (untested so only usable as a starting point).

Add your own ansible playbook that runs after Drupal VM ([docs](http://docs.drupalvm.com/en/latest/extras/scripts/#ansible-playbooks)):

Create a `Vagrantfile.local` with:

```rb
config.vm.provision 'ansible' do |ansible|
  ansible.playbook = "#{host_config_dir}/local.playbook.yml"
  ansible.galaxy_role_file = "#{host_config_dir}/local.requirements.yml"
end
```

Create a `local.requirements.yml` next to your `config.yml` with:

```yaml
---
- src: ANXS.postgresql
```

Then create a `local.playbook.yml` with:

```yaml
---
- hosts: all
  become: yes

  vars_files:
    - default.config.yml # Not entirely sure these are the paths...
    - config.yml

  pre_tasks:
    - name: Install PHP PostgreSQL dependencies.
      # if you're using Ubuntu 14.04, might be `php7.0-pgsql` or `php-pgsql`, not sure
      apt: name=php5-pgsql state=installed
      when: ansible_os_family == 'Debian'
    - name: Install PHP PostgreSQL dependencies.
      yum: name=php-pgsql state=installed
      when: ansible_os_family == 'RedHat'

  roles:
    - ANXS.postgresql

  tasks:
    - name: Check if site is already installed.
      command: >
        /usr/local/bin/drush status bootstrap
        chdir={{ drupal_core_path }}
      register: drupal_site_installed
      failed_when: false
      changed_when: false
      become: no

    - name: Install Drupal with drush.
      command: >
        /usr/local/bin/drush site-install {{ drupal_install_profile | default('standard') }} -y
        --site-name="{{ drupal_site_name }}"
        --account-name={{ drupal_account_name }}
        --account-pass={{ drupal_account_pass }}
        --db-url=pgsql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ pgsql_databases[0].name }}
        {{ drupal_site_install_extra_args | default([]) | join(" ") }}
        chdir={{ drupal_core_path }}
      notify: restart webserver
      when: "'Successful' not in drupal_site_installed.stdout"
      become: no

    - name: Install configured modules with drush.
      command: >
        /usr/local/bin/drush pm-enable -y {{ drupal_enable_modules | join(" ") }}
        chdir={{ drupal_core_path }}
      when: "'Successful' not in drupal_site_installed.stdout"
      become: no
```

And finally add these to your `config.yml`:

```yaml
postgresql_databases:
  - name: "{{ drupal_mysql_database }}"
    owner: "{{ drupal_mysql_user }}"

postgresql_users:
  - name: "{{ drupal_mysql_user }}"
    pass: "{{ drupal_mysql_password }}"
    encrypted: no

postgresql_user_privileges:
  - name: "{{ drupal_mysql_user }}"
    db: "{{ drupal_mysql_user }}"
    priv: "ALL"

# We have to re-define these tasks as mysql is hardcoded.
install_site: false
```

**Comment by laceysanderson** [comment]
Awesome!! That worked :-) I had managed to get partway there following @gitoutthere's comment on Aug 4, 2015 but I was running into problems forcing the new requirements plus that wouldn't have gotten me the php-pg link. Your recipe @oxyc worked perfectly! I did have to add a local ansible.cfg in order to get past an issue with Ansible 2.1 and the unpriviledged postgres user (issue: https://github.com/ansible/ansible/issues/16048):

Created a `ansible.cfg` with:
```yaml
# This needs to be set in order for postgresql to be installed.
# postgresql installation requires becoming the unpriviledged postres
# use which is known to be a security risk:
#  https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
# As of Jun 2016 it is uncertain how to get around this as determined
# in this discussion: https://github.com/ansible/ansible/issues/16048
[defaults]
allow_world_readable_tmpfiles = TRUE
```

Once I added that and re-provisioned I was able to get a fully installed Drupal site with postgresql backend :-D Thanks!!

**Comment by fubarhouse** [comment]
Off the back of this, I am seriously considering creating a role to suit this purpose.

As far as I'm aware, are these the requirements you're seeking, and if I was to engage in this task would I have your support? I'm a MySQL man, so I wouldn't actually be using this one myself.

* Support for Debian/Ubuntu
* Support for Arch
* Support for RHEL/CentOS

* Installs PostgreSQL
* Passes tests via Travis

**Comment by geerlingguy** [comment]
@fubarhouse - Support for Arch would be optional.

But yes, it would need to be available on Galaxy, and it also should support easy addition of databases / database users (like the `mysql_databases` and `mysql_users` vars in the MySQL role).

**Comment by fubarhouse** [comment]
@geerlingguy You only have Ubuntu and CentOS available via the Hashicorp Atlas, are you able to recommend a box for Arch - perhaps the one used to test support for DrupalVM?

**Comment by geerlingguy** [comment]
I don't currently do any Arch testing—it's not currently supported as a base box for the VM (though some users run it as their _host_ OS).

**Comment by fubarhouse** [comment]
There's a detailed rundown of all the postgresql specific modules on the following page, so as long as there're tasks focused to support it, you should have no issues integrating it.

http://blog.2ndquadrant.com/ansible-loves-postgresql/

**Comment by geerlingguy** [comment]
Note that I'm working on a simpler PostgreSQL role here: https://galaxy.ansible.com/geerlingguy/postgresql/ (most of the other roles I've tried are either crazy-complex, only work on one or two OSes, etc.

**Comment by geerlingguy** [comment]
Current status:

1. For automated builds, everything works up to `drush site-install`; at that point, with the Composer-based installation, we get the error:

```
Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 128
Drush command terminated abnormally due to an unrecoverable error.   [error]
```

2. If I wipe out the Composer-based installation and download Drupal 8.x core manually, then run the GUI installer at http://drupalvm.dev/core/install.php, then I hit the error message: 

```
The bytea_output setting is currently set to 'binary', but needs to be 'escape'
```

I found [this drupal.org issue](https://www.drupal.org/node/926636) (and see [this forum topic](https://groups.drupal.org/node/199783), which tells me I have to run the following query to get the Drupal pgsql database in working order:

```
ALTER DATABASE drupal SET bytea_output = 'escape';
```

(To run that manually, `vagrant ssh` in, enter `sudo su - postgres`, then run `psql`, then run the query.)

After doing that, I get a successful GUI install, and the following in the status report:

  - Database system: PostgreSQL
  - Database system version: 9.5.4

So now I'm going to work on making sure the database is adjusted correctly (but _why_?), and also why Drush + Composer-based install is failing (whereas downloading manually works).

**Comment by geerlingguy** [comment]
See also: [[meta] Remaining Drupal 8 PostgreSQL issues](https://www.drupal.org/node/2564307). It seems that PostgreSQL support in D8 is similar to Nginx... most people use the old stalwart (e.g. Apache, MySQL), and the smaller percentage that do use the alternative (Nginx, PostgreSQL) are forced to work through a lot of problems independently :)

**Comment by geerlingguy** [comment]
Well, would you look at that!

![postgres-install-success](https://cloud.githubusercontent.com/assets/481677/19011315/2e1a772e-8757-11e6-9270-2ae3136f7934.png)

Now just waiting on [build #1009](https://travis-ci.org/geerlingguy/drupal-vm/builds/164203039) to succeed...

**Comment by geerlingguy** [comment]
The build [failed](https://travis-ci.org/geerlingguy/drupal-vm/jobs/164203042) with:

```
InstallerException: Resolve all issues below to continue the
installation. For help configuring your database server, see the
installation handbook</a>, or contact your hosting provider.

The bytea_output setting is currently set to 'hex', but needs to
be 'escape'. Change this by running the following query:
ALTER DATABASE "drupal" SET bytea_output = 'escape';
in /var/www/drupalvm/drupal/web/core/includes/install.core.inc:911
```

But it worked locally. Re-running locally to see if I can reproduce the error :/

**Comment by geerlingguy** [comment]
Hmm... getting that locally too.

**Comment by geerlingguy** [comment]
It seems that global config change won't take effect until a restart of the server, and it feels like a hacky way of going about it anyways; if I want to use that, I'll have to do a `meta: flush_handlers` somewhere in a role, and I hate having to do that.

So instead, I'll add a task right before site install:

```yaml
# See: https://www.drupal.org/node/2569365#comment-11680807
- name: Configure database correctly if using PostgreSQL.
  command: psql -c "ALTER DATABASE {{ drupal_db_name }} SET bytea_output = 'escape';"
  when: "'Successful' not in drupal_site_installed.stdout"
  become: yes
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
```

Running local tests again.
