### ISSUE TITLE
Automatic Virtualhost creation

### ISSUE THREAD

**Issue by kalpit-addweb** [geerlingguy/drupal-vm#1467]
I'm using drupal-vm for local development. and i've added synced folder configuration in vagrantfile by creating html directory in folder and mounted that on box's /var/www/html directory. now i can access all data of host fodler into box.  and by creating virtualhost manually i can access projects in browser.
Now i want something faciltiy like dnsmasq which will automatically crreate virtualhost by appending .dev at the end of project-folder name. for ex, if project name is example than vhost url should be example.dev;
So how i can do that in drupal-vm means how it will automatically create url and add entry in hosts etc/hosts file to access project via browser.
Please guide me in doing that.
I've added this line in Vagrantfile to access data from host to guest:--
==>  config.vm.synced_folder "html/", "/var/www/html"

**Comment by oxyc** [comment]
What I do for one server is to use `vhost_alias` apache mod.

```yaml
apache_vhosts:
  - servername: "drupalvm.dev"
    serveralias: "*.drupalvm.dev"
    documentroot: "/var/www/html"
    extra_parameters: |
          VirtualDocumentRoot /var/www/html/%-2/web


apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  - vhost_alias.load # dynamic virtual hosts with VirtualDocumentRoot

# I use `mod_php` here, not sure if it works with FPM.
php_enable_php_fpm: false
extra_packages:
  - "libapache2-mod-php{{ php_version }}"
```

One downside here is that the hosts won't be added to your `/etc/hosts` file automatically. You could fix this by adding a `Vagrantfile.local` with:

```rb
project_dirs = Pathname.new("#{host_project_dir}/html").children.select { |c| c.directory? }
project_hosts = project_dirs.collect { |p| "#{p.basename}.#{vconfig['vagrant_hostname']}" }

config.hostsupdater.aliases << project_hosts
puts config.hostsupdater.aliases
```
