### ISSUE TITLE
vagrant up remains on 'Generate Drupal project with composer package'

### ISSUE THREAD

**Issue by skorasaurus** [geerlingguy/drupal-vm#1476]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.22r115126
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### Your OS

Ubuntu 16.04; 4.10.0-27-generic 

### Full console output

my sys log: https://gist.github.com/skorasaurus/1f9cea059d6e20dac3c2249d6945b09a

my Vbox log: https://gist.github.com/skorasaurus/e3117c413cb1c4d48520dedb6c64be86

my hardware
https://gist.github.com/skorasaurus/59c747f953182eb7ed98bd36947389eb

### Summary

to reproduce on my system: 
clone drupal-vm 
git checkout 7c05f1ffb1b4c5a794e332a79c6b7d70e4c393bd
vagrant plugin install vagrant-vbguest
cd drupal-vm 
vagrant up

while issuing vagrant up for the first time after cloning the repository; there's no movement for more than 30 minutes at: 
```geerlingguy.drupal : Generate Drupal project with composer package```
Compared to #1460 ; 
My system does not crash and is still very responsive; I can use it for routine tasks, web browsing). 

If I edit my [config.yml](https://gist.github.com/skorasaurus/b804afb287465163932409f269c5356b) to as cited at [NFS shares are slow or hang due to UDP protocol](http://docs.drupalvm.com/en/latest/getting-started/installation-linux/#nfs-shares-are-slow-or-hang-due-to-udp-protocol), I am able to provision an environment after about 20 minutes. 

Possibly related to #1468; there's no package named nfs-utils on my system; I do have nfs-common and nfs-kernel-server both at  ```1:1.2.8-9ubuntu12.1```

**Comment by oxyc** [comment]
Great that TCP works! This is another + for https://github.com/geerlingguy/drupal-vm/issues/1468

- related vagrant issue of tcp vs udp https://github.com/mitchellh/vagrant/issues/2304

20min is still slightly slow but I guess that's because it's HDD rather than SSD.

**Comment by oxyc** [comment]
@geerlingguy I guess we could improve the performance and fix some issues by running `composer create-project` in eg `/tmp` and then moving it to the correct location. I bet this would help with #1309 too.

**Comment by geerlingguy** [comment]
@oxyc - That sounds like a potentially good solution; hopefully it wouldn't introduce any other headaches though. Note that it might also make things slower if you're using native virtualbox synced folders (e.g. Windows)... If you can submit a PR, I could test at least on Ubuntu 16.04 once I get my laptop un-buried.

**Comment by oxyc** [comment]
Shouldn't it be faster with native vbox synced folders too? Im assuming a `mv`, `cp` or `rsync` would be faster than running all the logic of `composer create-project`

**Comment by oxyc** [comment]
Also, by using either `cp -r` or the `synchronize` module we might not need to error out if the directory already exists. The operation could still theoretically be destructive if someone deleted the `drupal/web/index.php` file, and then changed a file that `composer create-project` scaffolds without committing to git. Thoughts?

This would avoid the very common issue that happens when you dont clear out the `drupal/` directory.

**Comment by oxyc** [comment]
Another thing I like about this idea is that the slow task wouldn't be _Generating Drupal project_ anymore, instead something like _Moving Drupal project files into place_. That both splits the longest task into two so the user can see that it's still working, and makes it easier to debug.

**Comment by oxyc** [comment]
On my macbook 12" 1.1ghz with SSD and NFS:

task | duration
------|-------
composer create-project /tmp/drupal-project | 49s
cp -r /tmp/drupal-project /var/www/drupalvm/drupal | 48s
composer create-project /var/www/drupalvm/drupal | 148s

That's quite a significant performance improvement to be honest.

As this would be added to the `geerlingguy.drupal` role but still easier to benchmark using Drupal VM I'll wait with opening up a PR for a bit. Here's a [branch](https://github.com/oxyc/drupal-vm/tree/perf) you can test. The commit
https://github.com/oxyc/drupal-vm/commit/4b1e81fa4777fc83540207ff61642c3f43e0c5a7

**Comment by skorasaurus** [comment]
Hi, 

I just tested it as follows (let me know if I did not do this correctly):

```
git remote add oscar https://github.com/oxyc/drupal-vm.git
git fetch oscar
git checkout -b perf
git pull oscar perf
vagrant halt (I had my current drupal-vm still running)
vagrant destroy 
vagrant up (Started at 852)
```
(the general drupal project with comper package in /tmp/drupal-project started at 9:02)
finished at 9:05

Vagrant up finished in 13 minutes, nearly a 50% improvement :) 

However, when I opened drupalvm.dev; the graphics did not display in chrome or firefox; see 
![selection_040](https://user-images.githubusercontent.com/955351/28318599-651d468a-6b99-11e7-9703-9cd76a7954c0.png)

Here's when I logged into the admin account in drupalvm.dev : 
![selection_041](https://user-images.githubusercontent.com/955351/28318742-dd4dbc84-6b99-11e7-8622-e74e09a823e2.png)
```Refused to execute script from 'http://drupalvm.dev/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.```


Yesterday, drupalvm.dev loaded as expected. 

(Side note, and sorry for side track): Although drupalvm.dev loaded successfully yesterday, I couldn't find my drupal install folder.I specified it [in my config file](https://gist.github.com/skorasaurus/b804afb287465163932409f269c5356b) but it was not there.

**Comment by oxyc** [comment]
The `vagrant_synced_folders` need to list two entries when you switch to nfsv4.

```yaml
vagrant_synced_folders:
  # The default share.
  - local_path: ~/drupal/myvmsite
    destination: /var/www/drupalvm
    type: nfs
    create: true
    options_override:
      nfs_version: 4
      nfs_udp: false

  # Manually specify the /vagrant share to override the defaults
  - local_path: .
    destination: /vagrant
    type: nfs
    options_override:
      nfs_version: 4
      nfs_udp: false
```

The one that points to `/var/www/drupalvm` is the shared folder that is picked up at `http://drupalvm.dev`. As you want to edit the code on your host, and then sync it to where the Apache VirtualHost points, it's ofc required to have it shared.

The second that points to `/vagrant` is used primarily to get Drupal VM's `provisioning/` directory to the VM when the user doesn't have ansible installed and everything is installed from within the VM, rather than from the host. The `config.yml` that you linked, only has this one which is why the install folder wasn't available on your host. @geerlingguy technically we could even drop this when `ansible` is found on the host?

Also @skorasaurus it might be worth checking if it works without specifying the NFS version, and just setting UDP

```yaml
vagrant_synced_folders:
  # The default share.
  - local_path: ~/drupal/myvmsite
    destination: /var/www/drupalvm
    type: nfs
    create: true
    options_override:
      nfs_udp: false

  # Manually specify the /vagrant share to override the defaults
  - local_path: .
    destination: /vagrant
    type: nfs
    options_override:
      nfs_udp: false
```

**Comment by oxyc** [comment]
@skorasaurus I updated my branch with a commit that defaults the `nfs_udp` to `false`. This should fix it without you having to edit `vagrant_synced_folders` at all.

**Comment by oxyc** [comment]
Derp I had a typo that broke it, just pushed another commit.

Also thanks so much for helping test all my ramblings! It really helps out

**Comment by skorasaurus** [comment]
@oxyc To clarify, what and how would you like me to test? 

As I understand: 

Do the following using [this config](https://gist.github.com/skorasaurus/7c02de6ecbe30551dffdcb2d20fb11c4)
```vagrant halt (if I have my current drupal-vm still running)
vagrant destroy 
vagrant up ```
(measure the time it takes, report any errors in output, and check that drupalvm.dev is operating as expected)

and 
repeat above with [this 2nd config](https://gist.github.com/skorasaurus/1479d1b1a3a44e6116295be4c08025b5) based on your [most recent commit](https://github.com/oxyc/drupal-vm/commit/75ce83f825b6008074a08726f073da5ab5a38f8d)?

**Comment by oxyc** [comment]
@skorasaurus you could test:

1. `vagrant halt`
2. `vagrant destroy`
3. `vagrant up`

with this (if you have the most recent commit):

```yaml
vagrant_synced_folders:
  # The default share.
  - local_path: ~/drupal/myvmsite
    destination: /var/www/drupalvm
    type: nfs
    create: true
```

It now defaults to TCP so it should work on all Linux distros, and even making it faster on at least my own macbook.

If if fails (but not otherwise) you can try:

```yaml
vagrant_synced_folders:
  # The default share.
  - local_path: ~/drupal/myvmsite
    destination: /var/www/drupalvm
    type: nfs
    create: true
    options_override:
      nfs_version: 4

  # Manually specify the /vagrant share to override the defaults
  - local_path: .
    destination: /vagrant
    type: nfs
    options_override:
      nfs_version: 4
```

If UDP alone doesn't fix it, then we might have to specify the NFS version as 4. Sadly NFSv4 is not available on macOS so would be preferable if we could use the defaults from upstream Vagrant. But if there's no other choice, we probably need to add some logic that checks if the host OS is linux, and then sets v4 automatically.

---

The other change in my branch is that the Drupal codebase is now built in `/tmp` and then moved over to `/var/www/drupalvm/drupal` rather than being built directly in the shared directory. On my own laptop is decreased the build time from 150s to 100s. I'm guessing it's even more with a HDD.
