### ISSUE TITLE
Can't get remote drush alias to work in playbook

### ISSUE THREAD

**Issue by MichaelMallett** [geerlingguy/drupal-vm#1499]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.6
VirtualBox 5.1.22r115126
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.11.6)

### Summary

When trying to run a post provision playbook to import the database using an alias, I am getting a strange issue with any connection to another machine

```
- name: Check status of UAT site.
  shell: "drush @site.uat status --debug"
  args:
    chdir: "/var/www/site"
  when: not item.stdout
  register: drushoutput
  with_items:
    "{{ dbstatus.results }}"
```

I have ssh'd in and ran the command normally, and it will retrieve the status of the uat site. However the ansible playbook just hangs (and I've not managed to test the limit as I left it for over an hour over lunch), with no output at all. If I change the alias to local, I get the boostrap information back from drupal.

This suggests it's a limitation with ansible shell command? Or some other SSH error (I have disabled StrictHostKey checking).

**Comment by geerlingguy** [comment]
@MichaelMallett - One thing I wonder—do you use SSH to connect through the site.uat alias? If so, and if you're logging into the VM, it might be holding your SSH private key when you log in and run that command. When Ansible runs the task, it might not have your private key available inside the VM; or maybe there's a host key warning (e.g. the Drush command, when run by Ansible, is prompting for a host key acceptance)...

**Comment by oxyc** [comment]
Hmm also the task logic looks rather strange. You are looping over the `dbstatus.results` which I believe has multiple values, causing it to run over and over again.

Should it be like this maybe:

```
- name: Check status of UAT site.
  shell: "drush @site.uat status --debug"
  args:
    chdir: "/var/www/site"
  when: not dbstatus.results.stdout
  register: drushoutput
```
