### ISSUE TITLE
DrupalVM - BLT feature request

### ISSUE THREAD

**Issue by marceldobrica** [geerlingguy/drupal-vm#1513]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.3.2.0
```

### Your OS

 - **Linux** (Ubuntu 16.04LTS)

### Summary

I would like to start a DrupalVM box with nothing inside and to ssh into the box and create a BLT project or a drupal-composer project, or anything i would like, with different drupal_core_path...  or even symfony, magento, etc

It would be nice to have the possibility to run BLT inside DrupalVM - BLT as a composer package - something like http://docs.drupalvm.com/en/latest/deployment/composer-package/ for lightning-project...

**Comment by oxyc** [comment]
> I would like to start a DrupalVM box with nothing inside and to ssh into the box and create a BLT project or a drupal-composer project, or anything i would like, with different drupal_core_path... or even symfony, magento, etc

There are some [docs](http://docs.drupalvm.com/en/latest/other/wordpress-other-applications/) on doing this with Drupal VM as a composer dependency with Wordpress as an example. 

If you just want to build a VM without Drupal being installed create a `config.yml` with:

```yaml
# Disable Drupal specific features.
drupal_build_composer_project: false
drupal_install_site: false
configure_drush_aliases: false

# Disable synced folders
vagrant_synced_folders: []

# Used by the default apache virtual host.
drupal_core_path: "/var/www/magento/web"
```

Not sure if apache can point to directories that do not exist though... You can of course disable (or modify) the virtual hosts with `apache_vhosts: []`.

Alternatively if you want to write code on your machine and sync it to the VM you can create an empty `magento/` directory next to your `Vagrantfile` and then use:

```yaml
# Disable Drupal specific features.
drupal_build_composer_project: false
drupal_install_site: false
configure_drush_aliases: false

# Used by the default apache virtual host.
drupal_core_path: "/var/www/drupalvm/magento"
```
