### ISSUE TITLE
Skip need for vault pass on local dev provision

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#1522]
### Issue Type

 - Bug Report / Support Request
 

### Your Environment

```
Vagrant 1.9.7
VirtualBox 5.1.26r117224
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 25 2017, 15:14:13) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (version)

### Full console output

```
TASK [Include optional configuration files.] ***********************************
ok: [local-misfits] => (item=/Users/iainhouston/WebDev/misfitstheatre.com/vm/config.yml)
failed: [local-misfits] (item=/Users/iainhouston/WebDev/misfitstheatre.com/vm/secrets.yml) => {"ansible_facts": {}, "failed": true, "item": "/Users/iainhouston/WebDev/misfitstheatre.com/vm/secrets.yml", "message": "Decryption failed on /Users/iainhouston/WebDev/misfitstheatre.com/vm/secrets.yml"}
ok: [local-misfits] => (item=/Users/iainhouston/WebDev/misfitstheatre.com/vm/vagrant.config.yml)
	to retry, use: --limit @/Users/iainhouston/WebDev/misfitstheatre.com/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry
```
### Summary

Following "Soup to Nuts" and having added `vm/secrets.yml` deploys to prod just great. But now, doing `vagrant provision` on the local dev site we fail because we have not been given the opportunity to provide vault password as we were when invoking `ansible-playbook` with `--ask-vault-pass` .

But we really need to skip the need for  `secrets.yml` when we're provisioning local dev?

**Comment by iainhouston** [comment]
In `vendor/geerlingguy/drupal-vm/provisioning/vars/main.yml` I changed the `secrets.yml` line as follows: 

```
- name: Include optional configuration files.
  include_vars: "{{ item }}"
  with_fileglob:
    - "{{ config_dir }}/config.yml"
    - "{{ config_dir }}/local.config.yml"
    - "{{ config_dir }}/{{ lookup('env', 'DRUPALVM_ENV')|default(drupalvm_env, true)|default(ansible_env.DRUPALVM_ENV)|default(omit) }}secrets.yml"
    - "{{ config_dir }}/{{ lookup('env', 'DRUPALVM_ENV')|default(drupalvm_env, true)|default(ansible_env.DRUPALVM_ENV)|default(omit) }}.config.yml"
```

I `touch`ed `vm/secrets.yml` so that it was empty and not encrypted in the local `DRUPALVM_ENV` environment .
But for this to work when provisioning the remote prod server this would mean that `composer install` would have to clone `geerlingguy/drupal-vm` to get a modified `vendor/geerlingguy/drupal-vm/provisioning/vars/main.yml` and I am not sure that my submitting this change as a pull request would disrupt others .... anyway, I may try in case it is what would work for all.
