### ISSUE TITLE
Generate a site alias file for DrupalConsole

### ISSUE THREAD

**Issue by jmolivas** [geerlingguy/drupal-vm#1530]
### Issue Type
 - Feature Idea

### Summary
Generate a site alias for DrupalConsole

File path: `{path-to-site}/console/sites/{site-name}.yml`

File contents:
```
dev:
  root: {path-to-site}
  host: {site-name}.dev
  user: vagrant
  extra-options: '-o PasswordAuthentication=no -i ~/.vagrant.d/insecure_private_key'
  type: ssh
```

NOTE: Update docs to reflect this change http://docs.drupalvm.com/en/latest/extras/drupal-console/
