### ISSUE TITLE
Site Install Error - Exception Unmet Dependencies

### ISSUE THREAD

**Issue by rtackett** [geerlingguy/drupal-vm#1554]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.0
VirtualBox 5.1.28r117968
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```
config.yml
```
---
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
vagrant_ip: 0.0.0.0
drupal_build_makefile: true
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"
drush_make_options: "--no-gitinfofile"

drupal_build_composer: false
drupal_build_composer_project: false

drupal_enable_modules: [ "devel", "encrypt", "key", "admin_toolbar", "admin_toolbar_tools", "webprofiler" ]

installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  #- mailhog
  # - memcached
  # - newrelic
  - nodejs
  #- pimpmylog
  # - redis
  - ruby
  # - selenium
  # - solr
  # - tideways
  - upload-progress
  #- varnish
  #- xdebug
  #- xhprof # use `tideways` if you're installing PHP 7+
# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite
  - php-pear
  - libapache2-mod-php5.6
  - libsodium-dev

drush_version: "8.1.13"

php_version: "5.6"
php_memory_limit: "400M"
```
drupal.make.yml
```
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "8.x"

projects:
  # Core.
  drupal:
    version: "8.3.7"
  # Projects
  # Other modules.
  devel: "1.0"
  admin_toolbar: "1.19"
  devel: "1.x-dev"
  encrypt: "3.0-alpha3"
  key: "1.3"
  sodium: "1.0"

defaults:
  projects:
    subdir: "contrib"
```
### Your OS
 - **macOS** (10.13 - High Sierra)

### Full console output
```
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--root=/var/www/drupalvm/drupal/web", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:34.508108", "end": "2017-09-20 16:37:23.091069", "failed": true, "rc": 1, "start": "2017-09-20 16:36:48.582961", "stderr": "Starting Drupal installation. This takes a while. Consider using the \u001b[1;32;40m\u001b[1m[ok]\u001b[0m\n--notify global option.\nexception 'Drupal\\Core\\Config\\UnmetDependenciesException' with       \u001b[31;40m\u001b[1m[error]\u001b[0m\nmessage 'Configuration objects provided by <em\nclass=\"placeholder\">standard</em> have unmet dependencies: <em\nclass=\"placeholder\">core.entity_form_display.user.user.default\n(field.field.user.user.user_picture)</em>' in\n/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98\nStack trace:\n#0\n/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(469):\nDrupal\\Core\\Config\\UnmetDependenciesException::create('standard',\nArray)\n#1\n/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132):\nDrupal\\Core\\Config\\ConfigInstaller->checkConfigurationToInstall('module',\n'standard')\n#2\n/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):\nDrupal\\Core\\ProxyClass\\Config\\ConfigInstaller->checkConfigurationToInstall('module',\n'standard')\n#3\n/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):\nDrupal\\Core\\Extension\\ModuleInstaller->install(Array, false)\n#4 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(1572):\nDrupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array,\nfalse)\n#5 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(662):\ninstall_install_profile(Array)\n#6 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(540):\ninstall_run_task(Array, Array)\n#7 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(117):\ninstall_run_tasks(Array)\n#8 phar:///usr/local/bin/drush/includes/drush.inc(726):\ninstall_drupal(Object(Composer\\Autoload\\ClassLoader), Array)\n#9 phar:///usr/local/bin/drush/includes/drush.inc(711):\ndrush_call_user_func_array('install_drupal', Array)\n#10\nphar:///usr/local/bin/drush/commands/core/drupal/site_install.inc(82):\ndrush_op('install_drupal', Object(Composer\\Autoload\\ClassLoader),\nArray)\n#11\nphar:///usr/local/bin/drush/commands/core/site_install.drush.inc(255):\ndrush_core_site_install_version('standard', Array)\n#12 [internal function]: drush_core_site_install('standard')\n#13 phar:///usr/local/bin/drush/includes/command.inc(422):\ncall_user_func_array('drush_core_site...', Array)\n#14 phar:///usr/local/bin/drush/includes/command.inc(231):\n_drush_invoke_hooks(Array, Array)\n#15 [internal function]: drush_command('standard')\n#16 phar:///usr/local/bin/drush/includes/command.inc(199):\ncall_user_func_array('drush_command', Array)\n#17 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):\ndrush_dispatch(Array)\n#18 phar:///usr/local/bin/drush/includes/preflight.inc(66):\nDrush\\Boot\\BaseBoot->bootstrap_and_dispatch()\n#19 phar:///usr/local/bin/drush/includes/startup.inc(458):\ndrush_main()\n#20 phar:///usr/local/bin/drush/includes/startup.inc(365):\ndrush_run_main(false, '/', 'Phar detected. ...')\n#21 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)\n#22 /usr/local/bin/drush(10): require('phar:///usr/loc...')\n#23 {main}", "stderr_lines": ["Starting Drupal installation. This takes a while. Consider using the \u001b[1;32;40m\u001b[1m[ok]\u001b[0m", "--notify global option.", "exception 'Drupal\\Core\\Config\\UnmetDependenciesException' with       \u001b[31;40m\u001b[1m[error]\u001b[0m", "message 'Configuration objects provided by <em", "class=\"placeholder\">standard</em> have unmet dependencies: <em", "class=\"placeholder\">core.entity_form_display.user.user.default", "(field.field.user.user.user_picture)</em>' in", "/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98", "Stack trace:", "#0", "/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(469):", "Drupal\\Core\\Config\\UnmetDependenciesException::create('standard',", "Array)", "#1", "/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132):", "Drupal\\Core\\Config\\ConfigInstaller->checkConfigurationToInstall('module',", "'standard')", "#2", "/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):", "Drupal\\Core\\ProxyClass\\Config\\ConfigInstaller->checkConfigurationToInstall('module',", "'standard')", "#3", "/var/www/drupalvm/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):", "Drupal\\Core\\Extension\\ModuleInstaller->install(Array, false)", "#4 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(1572):", "Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array,", "false)", "#5 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(662):", "install_install_profile(Array)", "#6 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(540):", "install_run_task(Array, Array)", "#7 /var/www/drupalvm/drupal/web/core/includes/install.core.inc(117):", "install_run_tasks(Array)", "#8 phar:///usr/local/bin/drush/includes/drush.inc(726):", "install_drupal(Object(Composer\\Autoload\\ClassLoader), Array)", "#9 phar:///usr/local/bin/drush/includes/drush.inc(711):", "drush_call_user_func_array('install_drupal', Array)", "#10", "phar:///usr/local/bin/drush/commands/core/drupal/site_install.inc(82):", "drush_op('install_drupal', Object(Composer\\Autoload\\ClassLoader),", "Array)", "#11", "phar:///usr/local/bin/drush/commands/core/site_install.drush.inc(255):", "drush_core_site_install_version('standard', Array)", "#12 [internal function]: drush_core_site_install('standard')", "#13 phar:///usr/local/bin/drush/includes/command.inc(422):", "call_user_func_array('drush_core_site...', Array)", "#14 phar:///usr/local/bin/drush/includes/command.inc(231):", "_drush_invoke_hooks(Array, Array)", "#15 [internal function]: drush_command('standard')", "#16 phar:///usr/local/bin/drush/includes/command.inc(199):", "call_user_func_array('drush_command', Array)", "#17 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):", "drush_dispatch(Array)", "#18 phar:///usr/local/bin/drush/includes/preflight.inc(66):", "Drush\\Boot\\BaseBoot->bootstrap_and_dispatch()", "#19 phar:///usr/local/bin/drush/includes/startup.inc(458):", "drush_main()", "#20 phar:///usr/local/bin/drush/includes/startup.inc(365):", "drush_run_main(false, '/', 'Phar detected. ...')", "#21 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)", "#22 /usr/local/bin/drush(10): require('phar:///usr/loc...')", "#23 {main}"], "stdout": "You are about to create a /var/www/drupalvm/drupal/web/sites/default/settings.php file and DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y", "stdout_lines": ["You are about to create a /var/www/drupalvm/drupal/web/sites/default/settings.php file and DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y"]}

```

### Summary

I am getting an exception during the site install step.  Any ideas?
