### ISSUE TITLE
How to override apache_vhosts and mysql_databases with dynamic values?

### ISSUE THREAD

**Issue by frankhenry** [geerlingguy/drupal-vm#1620]
I've got Drupal VM up and running but now I'm getting greedy and hoping to extend it to create a complete environment by restoring database backups. These tasks will require additional config info beyond what is provided for in `config.yml` and I was hoping to keep all the config info in one place, so I thought I could create my own settings file, create some tasks in `pre-provision.yml` to set some variables, and then use those variables in `config.yml.` Then, in `post-provision.yml,` I could use some more of the variables for tasks such as restoring the databases and creating `settings.php` from a template. I'm new to both Ansible and YAML so I'm not sure if this is even possible. If it is, I'm struggling with the syntax to make it work. 

The standard `config.yml` defines `apache_vhosts` and `mysql_databases` like this:

```
apache_vhosts:
  - servername: "intranet.dev"
    documentroot: "/var/www/intranet.dev/httpdocs"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "extranet.dev"
    documentroot: "/var/www/extranet.dev/httpdocs"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

mysql_databases:
  - name: "intranet_db"
    encoding: utf8
    collation: utf8_general_ci
  - name: "extranet_db"
    encoding: utf8
    collation: utf8_general_ci    
```
I have a `my-settings.yml `that contains this:

```
my_sites:
  - name: "My Intranet"
    env: intranet
    alias: intranet.dev
    docroot: "/var/www/intranet_files/httpdocs"  
    db_name: intranet_db
    db_dump: /srv/dumps/intranet_dump.sql.gz

  - name: "My Extranet"
    env: extranet
    alias: extranet.dev
    docroot: "/var/www/extranet_files/httpdocs"  
    db_name: extranet_db
    db_dump: /srv/dumps/extranet_dump.sql.gz

```
And in my `pre-provision.yml` file I'm doing this:

```
- name: "Include my site-specific info"
  include_vars: 
    file: "my-settings.yml"

- name: "Set my_vhosts_entries variable"
  set_fact: 
    my_vhost_entries: "{{ my_vhost_entries | default([]) +XXX }}"
    with_items: "{{ my_sites }}"

- name: "Set my_db_entries variable"
  set_fact: 
    my_db_entries: "{{ my_db_entries | default([]) + YYY }}"
    with_items: "{{ my_sites }}"

```
This is working to the point where my settings file is being read and the `my_sites` list is available, but I don't know how to use its values to create the `my_vhost_entries` and `my_db_entries` variables. I have fiddled around with all sorts of permutations for `XXX` and `YYY` but I'm clutching at straws and really don't know what to put in. What I'm hoping to end up with is two variables, `my_vhost_entries` and `my_db_entries`, that I can use in `config.yml`, like this:

```
apache_vhosts: {{ my_vhost_entries }}
mysql_databases: {{ my_db_entries }}

```
Is this even possible, and if so, what should I use instead of `XXX` and `YYY` in the pre-provision file above?

Finally, I don't want to push my luck but if someone could suggest the code for a task to restore the databases in `post-provision.yml` that would be greatly appreciated :-)

**Comment by FinBoWa** [comment]
Wouldn't the easiest way be to add `db_dump` or any new "important" fields to each of `mysql_databases`items and create a playbook that can be run independently.  Not only during provision.  

With a task , note following is a pseudo code more or less. 
```
- name: "import database"
  command: >
      "drush @[site].[env] ah-db-import --db={{ item.name }} --drop  --force {{ item. db_dump }}"
    with_items: "{{ mysql_databases }}"
```
Just add new keys to the `mysql_databases` or `apache_vhosts` so that they don't conflict with roles existing parameters. 

I personally use capistrano or shipit js tasks that can be called like `bundle exec cap db:pull` that do various things like, connects to the remote and dumps the database, gets it locally, replaces production urls to development urls, change admin pw to something easier, put payment methods to development mode etc.

**Comment by frankhenry** [comment]
Thanks, such a simple and good idea. It works great except for one tiny problem. It's not possible to keep all of the info in the mysql_databases list. Some values -- server name, alias, and document root -- must be specified in the apache_vhosts list.

**Comment by FinBoWa** [comment]
If you absolutely want to use your own custom list to set the values, then why use the set fact in your set fact to set the. 

Afaik, i mean that I haven't double checked, you can't do this: 

```
apache_vhosts: {{ my_vhost_entries }}
mysql_databases: {{ my_db_entries }}
```

as the config.yml is read quite early, but what you could do in your pre task is to set the fact 'mysql_databases':

```
- name: "Add my db values to the mysql_databases"
  set_fact: 
    mysql_databases: "{{ mysql_databases|default([]) + [ {'db_name': item.name} ] }}"
    with_items: "{{ my_sites }}"
```

previous is totally untested.
