### ISSUE TITLE
Add apache_vhosts_ssl to hosts file as well when using vagrant-hostsupdater 

### ISSUE THREAD

**Issue by sidneygijzen** [geerlingguy/drupal-vm#1623]
### Issue Type
 - Feature Idea

### Your Environment
```
Vagrant 1.8.7
VirtualBox 5.1.30r118389
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/my-username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### Your OS
 - **Linux** (Ubuntu 16.04)

### Summary
I'm starting to work more and more with local SSL-enabled sites in DrupalVM. However when I do a `vagrant up`, and my sites are being added to my hosts file by means of vagrant-hostsupdater, the SSL-enabled sites are unfortunately left out. I.e I have to manually add them to my hosts file.

I did a little digging in `lib/drupalvm/vagrant.rb`, and adding something like
```
aliases += get_apache_vhosts(vconfig.fetch('apache_vhosts_ssl', vconfig['apache_vhosts_ssl']))
```
into the `get_vhost_aliases` function seems to fix it for now. However, I'm a complete Ruby noob :), so I have no clue if this is a 'Ruby correct way' of doing this and whether this covers all edge-cases. Also, perhaps more importantly, if you're willing to consider to add this feature.

**Comment by thom8** [comment]
@sidneygijzen I'd recommend putting the domain in both `apache_vhosts` and `apache_vhosts_ssl` this way the domain will still respond on port 80 (http) then you can set an htaccess redirect to 443 (https) for SSL.

**Comment by sidneygijzen** [comment]
@thom8 That is a great suggestion. Thanks! That indeed solves it.

**Comment by geerlingguy** [comment]
@sidneygijzen - Yeah, I think I'll close this as a won't fix, and recommend the same fix for anyone else who needs 443 domains to show up in the hosts file.

Also, for Nginx, since it's one vhosts list (instead of separate)... it would make it more weird/difficult to support for convenience.

**Comment by oxyc** [comment]
I always define the certifiate keys to `apache_vhosts` and then set `apache_vhosts_ssl` to the same value as the extra parameters are ignored anyways.

With the Ubuntu snakeoil certificates:

```yaml
ssl_certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
ssl_certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

apache_vhosts_ssl: "{{ apache_vhosts }}"
```
