### ISSUE TITLE
Shared directories do not mount after VM reboot

### ISSUE THREAD

**Issue by denics** [geerlingguy/drupal-vm#1629]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
VirtualBox 5.1.30r118389
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/denix/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS High sierra** 

### Summary

Hi guys, this is weird and I do not understand why it is happening. I just discovered because I was trying to install zsh, so I had to reboot and once I logged in again all shared folders are empty (they exist in my host). Here is my version of ```local.config.yml```

```yaml
vagrant_box: ubuntu/trusty64

vagrant_plugins:
 - name: vagrant-vbguest
 - name: vagrant-hostsupdater
 - name: vagrant-proxyconf
 - name: vagrant-auto_network
 - name: vagrant-hostsupdater
 - name: vagrant-hostmanager

vagrant_hostname: vm.dev
vagrant_machine_name: vm
drupal_domain: "{{ vagrant_hostname }}"
# The name of the dump you want to use to build your website. It must be in gzip format.
drupal_db_file: "mydb.sql.gz"

vagrant_ssh_forward: true
# Do not forget to launch:
# ssh-add -K
# to add your private key to the SSH Agent

proxy_http: 'http://proxy.example.com:8080/'
proxy_https: 'http://proxy.example.com:8080/'
proxy_ftp: 'http://proxy.example.com:8080/'
proxy_none: 'localhost,127.0.0.1,.example.com,{{ drupal_domain }}'

vagrant_ip: 0.0.0.0

guest_path: "/var/www/drupalvm"

vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: "/home/vagrant/shared"
    type: nfs
    create: true
    map_uid: 1000
    map_gid: 1000
  - local_path: "./drupal"
    destination: "{{ guest_path }}"
    type: nfs
    create: false
    map_uid: 33
    map_gid: 33

installed_extras:
  - "adminer"
  - "drush"
  - "pimpmylog"
  - "redis"
  - "varnish"

extra_packages:
  - "monit"
  - "munin"
  - "zsh"

drush_version: "8.1.15"
# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: "apache"
# The database system to use. Can be either 'mysql' or 'pgsql'.
drupal_db_backend: "mysql"

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1, 7.2.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "5.6"
php_install_recommends: no
php_memory_limit: "256M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: ""
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"


# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php7.0 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

# Disable Apache package upgrades.
apache_packages_state: installed

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "en.{{ drupal_domain }} fr.{{ drupal_domain }} es.{{ drupal_domain }} ar.{{ drupal_domain }} ru.{{ drupal_domain }} zh.{{ drupal_domain }}"
    documentroot: "{{ guest_path }}/drupal/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_remove_default_vhost: true

apache_mods_enabled:
  - "expires.load"
  - "headers.load"
  - "ssl.load"
  - "rewrite.load"
  - "proxy.load"
  - "proxy_fcgi.load"

# We are building Drupal 7 based on makefile. For Drupal 8 with composer, turn this to false. Read default.config.yml for more info
drupal_build_makefile: true
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"
# We are building Drupal 7 based on makefile. For Drupal 8 with composer, turn this to true. Read default.config.yml for more info
drupal_build_composer: false
drupal_build_composer_project: false
drupal_install_site: false

# Run specified scripts before or after VM is provisioned. Use {{ playbook_dir }}
# to reference the provisioning/ folder in Drupal VM or {{ config_dir }} to
# reference the directory where your `config.yml` is.
pre_provision_scripts: []
# deploy_dev takes 4 arguments. the first is the drupal_domain, the sencond the path to where drupal is installed, the third one is the DB and the last is for the alias
post_provision_scripts:
  - "{{ config_dir }}/scripts/deploy_dev.sh {{ drupal_domain }} {{ guest_path }} {{ drupal_db_file }} {{ vagrant_machine_name }}"

# Other configuration.
dashboard_install_dir: "/var/www/dashboard"
known_hosts_path: "/Users/denix/.ssh/known_hosts"
hostname_configure: true
hostname_fqdn: "{{ vagrant_hostname }}"
ssh_home: "{{ drupal_core_path }}"
```
