### ISSUE TITLE
Postgres Driver Support

### ISSUE THREAD

**Issue by boybe** [geerlingguy/drupal-vm#1645]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 1.9.3
VirtualBox 5.1.18r114002
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides

PHP 7.0.18 (cli) (built: Apr 11 2017 14:25:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18, Copyright (c) 1999-2017, by Zend Technologies

```

### Your OS

 - **macOS Sierra** (10.12.6)

### Summary

I need to connect my DrupalVM-powered Drupal 7 site to a tableau server and I'm having difficulty finding and installing the necessary postgres driver to make that happen. I'm not looking to change my Drupal database from MySQL to Postgres (which I believe is the purpose of your [geerlingguy.postgresql](https://galaxy.ansible.com/geerlingguy/postgresql/) ansible role), but rather, to connect to a tableau server that is running Postgres. I was wondering if there are any ansible roles available that I could use to do that; my assumption is that success would be the PHP Info "PDO drivers" section reporting "pgsql" and a new entry for "PDO Driver for Postgres" (or something similar).  Thank you very much for any information (and for DrupalVM).

**Comment by boybe** [comment]
I ending up solving my issue by adding this to my playbook.yml:
```
- name: adding postgres to enable tableux connection
  hosts: webservers
  roles:
  - geerlingguy.postgresql
  - geerlingguy.php
  - geerlingguy.php-pgsql
```
Thanks!
