### ISSUE TITLE
Can't disable xdebug with Beetbox vm

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1649]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.0
VirtualBox 5.1.30r118389
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dane/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

### Your OS
 - **Linux** (Ubuntu 17.10)

### Summary
When I use Beetbox as a base box, I'm not able to disable xdebug in the VM.

My `box/config.yml` is as follows:
```
# Update the hostname to the local development environment hostname.
vagrant_hostname: local.foo.com
vagrant_machine_name: foo

# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 192.168.23.47

vagrant_box: beet/box
workspace: "/beetbox/workspace/{{ php_version }}"

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "BLTed 8"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/foo
    type: nfs

drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/foo"
drupal_core_path: "/var/www/foo/docroot"
ssh_home: /var/www/foo

drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - drush

php_version: "7.1"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 0
php_xdebug_remote_connect_back: 0
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"

post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
```
As you can see, xdebug should be disabled. But in the VM, there still exists the file `/etc/php/7.1/cli/conf.d/20-xdebug.ini` with the following contents:
```[XDebug]
zend_extension="/usr/lib/php/7.1/modules/xdebug-2.5.0.so"

xdebug.coverage_enable=1
xdebug.default_enable=1

xdebug.remote_enable=1
xdebug.remote_connect_back=1
xdebug.remote_host=10.0.2.2
xdebug.remote_port=9000
xdebug.remote_log=/tmp/xdebug.log
xdebug.remote_autostart=false

xdebug.idekey="PHPSTORM"

xdebug.max_nesting_level=256
```

This has always worked fine with the Ubuntu base box, it only seems to be a problem with Beetbox.

Apologies if this would be better addressed in a different issue queue.
