### ISSUE TITLE
provide SSL termination in front of Varnish

### ISSUE THREAD

**Issue by John-B** [geerlingguy/drupal-vm#1717]
### Issue Type

 - Feature Idea

### Your Environment

```
 -prod
```

### Your OS

 - Debian stable

### Summary

For provisioning production servers we need an SSL termination (probably nginx) in front of Varnish.
EDIT - I have decided to use Apache as both SSL terminator and Varnish backend, following this tutorial: https://bash-prompt.net/guides/apache-varnish/ -- this option could be added as an option to the nginx and / or apache roles.

**Comment by geerlingguy** [comment]
Please see/follow/add feedback to: https://github.com/geerlingguy/drupal-vm/issues/1251

Basically, I want to add some form of SSL support, but I don't know yet if it will be just on the Apache/Nginx layer (for simplicity) or if it will be termination in front of Varnish (more complex, wouldn't be as useful for local development at least w/r/t Certbot).

Aside: Drupal VM's primary purposes is still local development environments—adding complex features and architecture like SSL termination with Apache or Nginx in front of Varnish in front of Apache or Nginx is something that I might not be willing to add; it would be better to either fork Drupal VM for your infrastructure and make the changes yourself, or to build out your infrastructure from the base roles you need and work from that angle.

**Comment by joestewart** [comment]
@John-B This change of the extra_parameters may suffice for local development needs.
```
# Enable SSL Support on the Drupal site vhosts.
# See https://github.com/geerlingguy/ansible-role-apache for additional options.
# Update the file paths below if you are using a custom SSL certificate.
apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    # certificate_chain_file: "/path/to/certificate_chain.crt"
    # extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    # Disable the default extra_paramaters above and enable the verison below
    # for Varnish support. Make sure to enable Varnish in the installed_extras
    # section below.
    extra_parameters: |
      ProxyPreserveHost On
      ProxyPass / http://127.0.0.1:81/
      RequestHeader set X-Forwarded-Port "443"
      RequestHeader set X-Forwarded-Proto "https"

apache_mods_enabled:
  - expires.load
  - headers.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  - proxy_http.load
```
