### ISSUE TITLE
Add ability to provide custom shell scripts to run after provisioning

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#174]
It would be great if a user could add a custom Ansible tasks file (or maybe even extra roles, and we add the `roles` directory to `.gitignore`), that would be run if present, ignored if not present.

Maybe call it `extra_tasks.yml` and have it included from the project root directory (if present). This isn't supported OOTB by Ansible, but this might be a viable approach (default to an empty file if the extra tasks file isn't present): http://stackoverflow.com/a/29583251/100134

**Comment by geerlingguy** [comment]
This will need a documentation page, since usage will not be 100% intuitive/discoverable.

**Comment by geerlingguy** [comment]
I did a good deal of testing for this on Ansible 2.0.0 (still not the stable release yet), and it looks like the following code should do the trick, since 2.x includes files during playbook runs, and doesn't precompile everything:

```yaml
    # Include extra tasks file if it's present.
    - name: Check if extra_tasks.yml is present.
      stat: path=extra_tasks.yml
      register: extra_tasks_file
      connection: local

    - include: extra_tasks.yml
      when: extra_tasks_file.stat.exists
```
