### ISSUE TITLE
Local path empty

### ISSUE THREAD

**Issue by Michel-Settembrino** [geerlingguy/drupal-vm#1758]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 2.0.3
VirtualBox 5.2.10r122088
ansible 2.5.1
  config file = None
  configured module search path = [u'/Users/Michel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

### Your OS

 - **macOS** (10.13.4)

### Full console output

/

### Summary

My goal is to have a new Drupal 8 site created trough composer.
I created a config.yml file to do some changes.
One of the changes is the local path set to ./_sources/top-voixoff.be.git

My local folder ./_sources/top-voixoff.be.git get's created but empty.
And when I use my browser to see the site, I'm getting a site without css applied.

This is the config.yml I use:
```
vagrant_hostname: localhost.top-voixoff
vagrant_machine_name: drupalvm_top-voixoff
vagrant_ip: 192.168.88.89

vagrant_synced_folders:
  - local_path: ./_sources/top-voixoff.be.git
    destination: /var/www/drupalvm_top-voixoff
    type: nfs
    create: true

drupal_build_composer_project: true
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

drupal_install_site: true

installed_extras:
  - adminer
  - drush
  - mailhog
  - pimpmylog
  - varnish

```
