### ISSUE TITLE
Nginx needs to be restarted after Vagrant VM restarts under Ubuntu 16.04

### ISSUE THREAD

**Issue by Jasper-Grasmaijer** [geerlingguy/drupal-vm#1762]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.4
VirtualBox 5.2.10r122088
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jazzper/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

### Your OS
 - **Linux** (Ubuntu 16.04)

### Full console output
https://gist.github.com/Jasper-Grasmaijer/09d1d7af835c4a9bd8dd73492b865cb2.js
(No errors)

### Summary
I followed https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod to set up my local environment but with nginx instead of apache (see config files at the end).
Upon vagrant up the whole website gets set up but after vagrant halt and vagrant up there is a problem with nginx:

```
jazzper@jazzper-ideapad:~/WebDev/Sites/ksro$ vagrant ssh
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-62-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
You have new mail.
Last login: Mon Apr 30 04:43:15 2018 from 10.0.2.2

vagrant@local:/var/www/ksro/web$ service nginx status
* nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; disabled; vendor preset: 
   Active: inactive (dead)
     Docs: man:nginx(8)
lines 1-4/4 (END)
```

When I do a "sudo service nginx restart" everything is working (website, dashboard etc.)

config.yml:
```yaml
---
# Composer project settings.
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_dependencies: []

# Drupal install settings.
drupal_site_name: "Khaosanroad Online"
drupal_core_path: "/var/www/ksro/web"
drupal_install_site: true
drupal_major_version: 8

drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/15"
    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron --quiet"

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: nginx

# Other overrides.
php_version: "7.2" # ideally PHP 7.2, which is supported as of Drupal 8.5.0
php_sendmail_path: "/usr/sbin/sendmail -t -i"
installed_extras:
  - drush

# Other secure defaults.
dashboard_install_dir: ''

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443" #https
firewall_log_dropped_packets: true`
```

vagrant.config.yml:
```yaml
---
# Local Vagrant options.
vagrant_hostname: local.khaosanroadonline.com
vagrant_machine_name: local-khaosanroadonline
vagrant_ip: 192.168.88.12

# Configure the synced folder.
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/ksro
    type: nfs

# Undo some of the extra-hardened security settings in config.yml.
drupal_account_pass: admin
drupal_db_password: drupal
mysql_root_password: root
drupal_db_name: ksro

php_sendmail_path: "/opt/mailhog/mhsendmail"
installed_extras:
  - drush
  - mailhog
  - pimpmylog
  - adminer

dashboard_install_dir: /var/www/dashboard
extra_security_enabled: false

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
firewall_log_dropped_packets: false`
```
