### ISSUE TITLE
Build a prod environment: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}

### ISSUE THREAD

**Issue by Jasper-Grasmaijer** [geerlingguy/drupal-vm#1765]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.4
VirtualBox 5.2.10r122088
ansible 2.5.2
  config file = /home/jazzper/WebDev/Sites/ksro/ansible.cfg
  configured module search path = [u'/home/jazzper/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

### Your OS
 - **Linux** (Ubuntu 16.04)

### Full console output
Sorry I don't have the full console output. I thought the problem was a failing Internet connection (I am in a hostel at the moment). But after running the playbook over and over again I started searching for alternative explanations and stumbled upon:
https://github.com/ansible/ansible/issues/14426
I have (almost) exactly the same. Namely the following error, at random times:
FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}

```
TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
fatal: [80.209.229.201]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}
```

### Summary
I followed https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod to build a production environment but the playbook fails at random times. Running the playbook with "-c paramiko" solves the problem.

### config.yml
```
---
# Composer project settings.
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_dependencies: []

# Drupal install settings.
drupal_site_name: "Khaosanroad Online"
drupal_core_path: "/var/www/ksro/web"
drupal_install_site: true
drupal_major_version: 8

drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/15"
    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron --quiet"

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: nginx

# Other overrides.
php_version: "7.2" # ideally PHP 7.2, which is supported as of Drupal 8.5.0
php_sendmail_path: "/usr/sbin/sendmail -t -i"
installed_extras:
  - drush

# Other secure defaults.
dashboard_install_dir: ''

# Enable a more hardened security configuration.
extra_security_enabled: true
security_autoupdate_blacklist: "linux-image"
security_autoupdate_mail_to: "jazzper23@gmail.com"

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443" #https
firewall_log_dropped_packets: true
```

### prod.config.yml
```
---
# Deploy from the project's Git repository.
drupal_deploy: true
drupal_deploy_repo: "git@bitbucket.org:jazzper23/ksro.git"
drupal_deploy_dir: /var/www/ksro

# Set the domain for this site appropriately.
drupal_domain: "khaosanroadonline.com"
vagrant_hostname: "{{ drupal_domain }}"

nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true
```
