### ISSUE TITLE
Add Basic Auth options

### ISSUE THREAD

**Issue by VincenzoGambino** [geerlingguy/drupal-vm#1770]
### Issue Type
 - Feature Idea
### Your Environment

VPN

### Your OS

Linux

### Summary

I had the needs to deploy the dev server to digital ocean and restrict the access. Basic Auth could be done on .htaccess too but I preferred to have it on the vhost.

I did already implemented this functionality on my DrupalVM clone.

- I have added the role geerlingguy.pip
- Added the role in the playbook
- I have added three new variables on provisioning/roles/geerlingguy.apache/defaults/main.yml
```
# Add Basic Authentication to vhost files. Set to 'true' to add Basic authentication
htpasswd_basic_auth: false
htpasswd_basic_auth_user: dev
htpasswd_basic_auth_password: dev
```
- Added the task on provisioning/roles/geerlingguy.apache/tasks/main.yml

```
- name: Install passlibb with pip
  pip: name=passlib

- name: Creates Basic Authentication htpasswd files
  htpasswd:
    path: /var/www/passwd/.htpasswd
    name: "{{ htpasswd_basic_auth_user }}"
    password: "{{ htpasswd_basic_auth_password }}"
    owner: root
    group: www-data
    mode: 0640
```
- Added code on provisioning/roles/geerlingguy.apache/templates/vhosts.conf.j2
```
{% if vhost.htpasswd_basic_auth is defined and vhost.htpasswd_basic_auth == true %}
    AuthType Basic
    AuthName "Restricted Content"
    AuthUserFile /var/www/passwd/.htpasswd
    Require valid-user
{% endif %}
```
- In config.yml files add htpasswd_basic_auth: true to your vhost
```
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    htpasswd_basic_auth: true
```
Shall I create a Fork and then open a pull request?
