### ISSUE TITLE
[Question] Restarting a Drupal VM with services

### ISSUE THREAD

**Issue by svict4** [geerlingguy/drupal-vm#1780]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.1.1
5.2.12r122591
ansible 2.5.3
```

I am running Drupal 7 with a local codebase.

```yml
# config.yml

vagrant_hostname: redress.test
vagrant_machine_name: redressvm

vagrant_synced_folders:
  - local_path: C:\Users\email\Desktop\coding_projects\redresscheme\docroot
    destination: /var/www/redressvm
    type: nfs
    create: true

drupal_build_makefile: false
drupal_build_composer: false
drupal_build_composer_project: false
drupal_install_site: false

drupal_core_path: "/var/www/redressvm"

vagrant_hostname: "redress.test"
drupal_domain: "{{ vagrant_hostname }}"

installed_extras:
  - adminer
  - drush
  - pimpmylog
  - solr
  - varnish
```

### Your OS

 - **Windows** 10

### Full console output

No problems here:
https://gist.github.com/svict4/81004149d4f2dcbc04077db8b335ba3f

### Summary

Dumb question: what's the magic to restarting/reloading a Drupal VM? I imagine `vagrant up` should work if it's halted/down?

I'm receiving `connection error` and unsure what to check for.
![image](https://user-images.githubusercontent.com/1137112/40396503-b623b6e8-5e70-11e8-976b-170c6b4b9689.png)

Was working _perfectly fine_ just yesterday before shutting down the PC for the night, so I think I'm simply missing a step this morning. I've restarted apache `sudo service apache2 restart` from within the VM and `netsh` shows everything is listening to the forwarded ports.

Am I forgetting to start another service? Tried trawling through the docs couldn't find a reference to booting up a VM again beyond `vagrant up`. There has to be another way than to `vagrant destroy` and re-provision the VM 😆
