### ISSUE TITLE
Xdebug is installed regardless of installed_extras

### ISSUE THREAD

**Issue by TravisCarden** [geerlingguy/drupal-vm#1830]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.3
VirtualBox 5.2.16r123759
ansible 2.6.4
  config file = None
  configured module search path = [u'/Users/travis.carden/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

### Your OS

 - **macOS** 10.13.6

### Full console output

Given this `config.yml`:
```yaml
drupal_build_composer_project: false
drupal_install_site: false
installed_extras: []
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 0
php_xdebug_remote_connect_back: 0
```
I get this output:
```bash
$ vagrant up
$ vagrant ssh -c "php -i | grep 'xdebug support'"
xdebug support => enabled
```

### Summary

Xdebug is installed regardless of whether or not it's included in `installed_extras`. As depicted above, I disabled various related settings "just in case", and it had no effect.

**Comment by TravisCarden** [comment]
I did precisely that, @geerlingguy: `vagrant destroy && vagrant up`.

**Comment by geerlingguy** [comment]
Hmm, let me try to reproduce with a fresh local build, with the `config.yml`:

```yaml
drupal_build_composer_project: false
drupal_install_site: false
installed_extras: []
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 0
php_xdebug_remote_connect_back: 0
```
