### ISSUE TITLE
error when "TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).]"

### ISSUE THREAD

**Issue by kburakozdemir** [geerlingguy/drupal-vm#1831]
### Issue Type

 - Bug Report

### Your Environment

```
Vagrant 2.1.5
VirtualBox 5.2.10_Ubuntur121806
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/burak/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

content of my `config.yml`

```yml
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: drupalvm.local
vagrant_machine_name: drupalvmlocal
vagrant_ip: 192.168.77.77

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/ for more.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

drupal_build_composer_project: true
drupal_install_site: true

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  - upload-progress
  # - varnish
  - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1, 7.2.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.2"

php_packages_extra:
  - php-bcmath #this is needed for commerce/intl
```

### Your OS

 - **Linux** (Ubuntu 18.04 - 4.15.0-36-generic)

### Full console output
[https://gist.github.com/kburakozdemir/37bb1d8d486aa84216ebcb77dc43301e](https://gist.github.com/kburakozdemir/37bb1d8d486aa84216ebcb77dc43301e)

_Don't have the full output console so I pasted the error only_

### Summary
when `vagrant up` during installation exactly while

`TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***`

the error appears.

Few days ago it was working. after searching issues etc., I tried different options (for manual debug :) )

I tried with:
1. master branch (no way)
2. checking out tags/4.9.0 (no way)
3. I also tried with  (no way)
```yml
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
#removed --prefer-dist to try
drupal_composer_project_options: "--stability dev --no-interaction"
```
I tried the combinations of the above with a clean `vagrant up` and they all failed.

4. then i tried with this configuration added to my `config.yml` (this means I removed devel module to install and enabled defaultly).

```yml
drupal_composer_dependencies: []
drupal_enable_modules: []
```
and opps! it worked! I took me 6 hours to find out! :)

I think the reason is the devel module (defaultly installed and enabled), however I didn't inquiry the reason behind the devel module.

As we know the default dvm config has:
```yml
drupal_composer_dependencies:
  - "drupal/devel:1.x-dev"
drupal_enable_modules: [ 'devel' ]
```
