### ISSUE TITLE
Provision fails

### ISSUE THREAD

**Issue by vasike** [geerlingguy/drupal-vm#1838]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.5
VirtualBox 5.2.18r124319
ansible 2.4.3.0
  config file = None
  configured module search path = ['/Users/vasike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.6/bin/ansible
  python version = 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

### Your OS
 - **macOS** (version)

### Full console output
TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***
failed: [drupalvm] (item=drupal/devel:^1.2) => {"changed": false, "item": "drupal/devel:^1.2", "msg": "[ErrorException] Use of undefined constant CURLOPT_HTTPGET - assumed 'CURLOPT_HTTPGET' (this will throw an Error in a future version of PHP)", "stdout": "\n                                                                                                                               \n  [ErrorException]                                                                                                             \n  Use of undefined constant CURLOPT_HTTPGET - assumed 'CURLOPT_HTTPGET' (this will throw an Error in a future version of PHP)  \n                                                                                                                               \n\n", "stdout_lines": ["", "                                                                                                                               ", "  [ErrorException]                                                                                                             ", "  Use of undefined constant CURLOPT_HTTPGET - assumed 'CURLOPT_HTTPGET' (this will throw an Error in a future version of PHP)  ", "                                                                                                                               ", ""]}
	to retry, use: --limit @/Users/vasike/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=248  changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

### Summary
Provision fails
And also the (result) VM seems broken

**Comment by oxyc** [comment]
Which version of Drupal VM are you using? Could you post your `config.yml`? Sounds like `php-curl` is not installed.

**Comment by geerlingguy** [comment]
Yeah, usually this is a result of that extension not being present, see: https://github.com/hirak/prestissimo/issues/145

**Comment by vasike** [comment]
But i didn't have this issue till yesterday. When i updated the VM and tried to provision ....

@oxyc i also tried to add php-curl as php package but it doesn't seems related - it won't change the result.

**Comment by oxyc** [comment]
Could you post your `config.yml`?

**Comment by vasike** [comment]
This is my local.config.yml 
```
# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: nginx

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  - redis
  # - ruby
  # - selenium
  - solr
  - upload-progress
  - varnish
  # xdebug
  # xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1, 7.2.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.1"
#php_version: "5.6"
php_install_recommends: no
php_memory_limit: "1200M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "2024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "800"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php7.0 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

php_packages_extra:
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-zip"
  - "php{{ php_version }}-soap"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ drupalvm_user }}/.composer"
composer_home_owner: "{{ drupalvm_user }}"
composer_home_group: "{{ drupalvm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: platformsh/cli }

# Run specified scripts before or after VM is provisioned. Path is relative to
# the `provisioning/playbook.yml` file.
pre_provision_scripts: []
post_provision_scripts:
  - "../examples/scripts/configure-solr.sh"
  - "../examples/scripts/configure-solr.d7.sh"

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: phantomjs
  - name: gulp
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"

# XDebug configuration. XDebug is disabled by default for better performance.
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 1200

# Elasticsearch configuration
elasticsearch_network_host: 0.0.0.0
elasticsearch_http_port: 9200
```

+ vagrant_synced_folders & nginx_hosts

Any suggestion what i could/should try?
