### ISSUE TITLE
Apache will not start/restart with 'SSLCertificateFile: file '/vagrant/example.crt' does not exist' error

### ISSUE THREAD

**Issue by longlivelance** [geerlingguy/drupal-vm#1862]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
VirtualBox 5.2.22r126460
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/lgeng/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 12 2018, 16:32:54) [Clang 10.0.0 (clang-1000.11.45.5)]
```

### Your OS

 - **macOS** (10.14)

### Full console output

https://gist.github.com/longlivelance/120a4231bd94a65ef31aa21b0aecbcc1

### Summary

Getting an apache failed to start error when trying to create a new DrupalVM. I've searched for similar bugs and loomed through the recommended ones but could not find anything or resolve the issue with those recommendations. I've also spent a lot of time trying to figure this out on my own without any luck. I recently upgraded to Mojave. An old DupalVM I had setup worked after the upgrade, but when I tried to recreate it after doing a `vagrant halt -f` and `vagrant destroy` I begin to get the following error:

```
RUNNING HANDLER [geerlingguy.apache : restart apache] **************************
fatal: [pac12local]: FAILED! => {"changed": false, "msg": "Unable to restart service apache2: Job for apache2.service failed because the control process exited with error code. See \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\n"}
```

Here is the output of the commands asked to run in the error message:

```
vagrant@local:/var/www/pac12/public$ systemctl status apache2.service
* apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           `-apache2-systemd.conf
   Active: failed (Result: exit-code) since Tue 2018-11-13 16:38:43 UTC; 31s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 961 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)
```

```
vagrant@local:/var/www/pac12/public$ journalctl -xe
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
```

Tried above with sudo:

```
-- Unit apache2.service has begun starting up.
Nov 13 16:39:25 local apache2[2552]:  * Starting Apache httpd web server apache2
Nov 13 16:39:25 local apache2[2552]:  *
Nov 13 16:39:25 local apache2[2552]:  * The apache2 configtest failed.
Nov 13 16:39:25 local apache2[2552]: Output of config test was:
Nov 13 16:39:25 local apache2[2552]: AH00526: Syntax error on line 61 of /etc/apache2/sites-enabled/vhosts.conf:
Nov 13 16:39:25 local apache2[2552]: SSLCertificateFile: file '/vagrant/example.crt' does not exist or is empty
Nov 13 16:39:25 local apache2[2552]: Action 'configtest' failed.
Nov 13 16:39:25 local apache2[2552]: The Apache error log may have more information.
Nov 13 16:39:25 local systemd[1]: apache2.service: Control process exited, code=exited status=1
Nov 13 16:39:25 local systemd[1]: Failed to start LSB: Apache2 web server.
-- Subject: Unit apache2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has failed.
-- 
-- The result is failed.
Nov 13 16:39:25 local systemd[1]: apache2.service: Unit entered failed state.
Nov 13 16:39:25 local systemd[1]: apache2.service: Failed with result 'exit-code'.
Nov 13 16:39:25 local sudo[2542]: pam_unix(sudo:session): session closed for user root
Nov 13 16:40:25 local sshd[1709]: Received disconnect from 10.0.2.2 port 51424:11: disconnected by user
Nov 13 16:40:25 local sshd[1709]: Disconnected from 10.0.2.2 port 51424
Nov 13 16:40:25 local sshd[1685]: pam_unix(sshd:session): session closed for user vagrant
Nov 13 16:40:25 local systemd-logind[679]: Removed session 3.
-- Subject: Session 3 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 3 has been terminated.
```

Below is my config overrides for the build:
 
```
# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: local.pac-12.com
vagrant_machine_name: pac12local
vagrant_ip: 19.11.19.7

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/ for more.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ~/Sites/local.pac-12.com
    destination: /var/www/pac12
    type: nfs
    create: true

# The web server software to use. Can be either 'apache' or 'nginx'.
# drupalvm_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
# drupal_db_backend: mysql

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
drupal_build_composer_project: false

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Required Drupal settings.
drupal_core_path: /var/www/pac12/public
drupal_db_user: pac12
drupal_db_password: pac12
drupal_db_name: pac12

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  # - mailhog
  - memcached
  # - newrelic
  - nodejs
  # - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  # - varnish
  # - xdebug
  # - xhprof

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.1"
php_max_input_vars: "4000"
php_max_execution_time: "600"
php_memory_limit: "1024M"
php_opcache_memory_consumption: "512M"

php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  # - "php{{ php_version }}-xdebug"
  # Turning off xhprof as it throws errors with php 7.1
  # Fabian suggested tideways_xhprof - https://pac12.slack.com/archives/CB9S9J2E5/p1535478189000100
  # - "php{{ php_version }}-xhprof"
  - imagemagick

# XDebug configuration.
php_xdebug_version: 2.5.0
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_remote_autostart: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"

# Solr configuration
solr_version: "4.10.4"

# Post-provision scripts.
post_provision_scripts:
  # - "../../pac12scripts/vm-configure-solr-4x.sh"
  - "../../pac12scripts/post-build.sh"

# Set and configure all Apache VirtualHosts needed.

apache_vhosts_ssl:
  -
    servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"


apache_vhosts:
  -
    servername: "{{ vagrant_hostname }}"
    serveralias: "edit.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  -
    servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  -
    servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
```
