### ISSUE TITLE
Unclear where trailing `docroot` is coming from in drush DRUPAL ROOT variable

### ISSUE THREAD

**Issue by broniusfatv** [geerlingguy/drupal-vm#1902]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.2.3
VirtualBox 5.2.26r128414
ansible 2.7.7
  config file = None
  configured module search path = [u'/Users/bronius/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

### Your OS

 - **macOS** 10.14.3 (Mojave)

### Full console output

https://gist.github.com/broniusfatv/acbfc3e605d28f1a1f2de0b78785e983

### Summary

What config is required to:
* Use existing Drupal 7 codebase
* Existing codebase is a subfolder in a repo which I'd like to NFS share as `/var/www/d7project` web root
* For some reason `drush --debug` always shows `/docroot` tacked on to the end of `DRUPAL ROOT`

I am not sure where the trailing `docroot` expectation is coming from as in `DRUPAL ROOT: /var/www/d7project/docroot/docroot/docroot` in the gist above when I sync webroot with host files over nfs like:
```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ~/projects/d7project/docroot
    destination: /var/www/d7project/docroot
    type: nfs
    create: true
```
in `config.yml`.

Note: I don't want `docroot/docroot` or even `docroot`.  I have a `docroot` in my host repo whose contents I *would like to be document / drupal root* as `/var/www/d7project` in the vagrant.  Originally, I had tried just:
```
  - local_path: ~/projects/d7project/docroot
    destination: /var/www/d7project
```
which still gives `DRUPAL ROOT: /var/www/d7project/docroot` (two less `docroot`s) in `drush --debug` when run from within vagrant.  I presume that `drush @d7project` will work from host mac machine once I have this resolved.
