### ISSUE TITLE
composer create-project drupal/recommended-project my-project runs into error

### ISSUE THREAD

**Issue by eigentor** [geerlingguy/drupal-vm#2046]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Drupalvm Version 5.20
Vagrant version 2.2.7
Virtualbox Version 6.0.20 r137117 (Qt5.6.2)
Ansible version 2.9.7

### Your OS

 - **Windows** 10  Pro Version 1903 Build 18362.836

### Full console output

After starting to create a fresh drupal project from drupal/recommended-project running

`composer create-project drupal/recommended-project my-project`

I run into

```
composer create-project drupal/recommended-project my-project
    1/13:       http://repo.packagist.org/p/provider-archived$beea589ae8fd6b04caf1c0ee549f49ae1202aefefc93f9a94e63092dd7ed6d3b.json
    2/13:       http://repo.packagist.org/p/provider-latest$4539509ab20de4cd8e27f1a7f44bb8b986fad18ca8f0ce7bee6666dfef115532.json
    3/13:       http://repo.packagist.org/p/provider-2019-10$17d016ac04270b4ccec878f822df806633210e680d23e91223773a7476fc2928.json
    4/13:       http://repo.packagist.org/p/provider-2015$8e4fdca7fe3200a44decf2957ed0d16cdba0a91ac0a04b0776abb3bbe66babba.json
    5/13:       http://repo.packagist.org/p/provider-2019-07$e6caaa04c574d7af69fcea2a609348eb2326007effb02f1fd344bda94e01dc8b.json
    6/13:       http://repo.packagist.org/p/provider-2020-04$9c84e6a12b5d709b3c25c67e49f40c47fdf2ac19041fcd9395f0cf41d7dcf584.json
    7/13:       http://repo.packagist.org/p/provider-2013$39889488e431198f82366f24d4b180f004da7736a9d8f247d692e2f180d2dbb5.json
    8/13:       http://repo.packagist.org/p/provider-2014$f531fb62fcdcfcbcd019cb7df7e5f2fb4fe860952bac14327cf0da803cffdf47.json
    9/13:       http://repo.packagist.org/p/provider-2016$72528073687616725bf4dc2545df15be8f7292439eea59a7bed3b426e32b4068.json
    10/13:      http://repo.packagist.org/p/provider-2020-01$87da2159a7702f797d9b1bb5b52e173120c3dcbc0838e0faae8e31115e4fa412.json
    11/13:      http://repo.packagist.org/p/provider-2019$c07e756600076bbb7777812537eb93470e0bc4af1f3501adc21a25408559c8df.json
    12/13:      http://repo.packagist.org/p/provider-2017$a37bcaf7aa1681386f75e2e3c3413a0ca1c7a0c6f68a32b65b72a2830f1b66c6.json
    13/13:      http://repo.packagist.org/p/provider-2018$767a721682b30f7de86dcbd26a7e2cde2a6b1e80e45071d19534195038001313.json
    Finished: success: 13, skipped: 0, failure: 0, total: 13
    1/13:       http://repo.packagist.org/p/provider-archived$beea589ae8fd6b04caf1c0ee549f49ae1202aefefc93f9a94e63092dd7ed6d3b.json
    2/13:       http://repo.packagist.org/p/provider-2019-07$e6caaa04c574d7af69fcea2a609348eb2326007effb02f1fd344bda94e01dc8b.json
    3/13:       http://repo.packagist.org/p/provider-latest$4539509ab20de4cd8e27f1a7f44bb8b986fad18ca8f0ce7bee6666dfef115532.json
    4/13:       http://repo.packagist.org/p/provider-2015$8e4fdca7fe3200a44decf2957ed0d16cdba0a91ac0a04b0776abb3bbe66babba.json
    5/13:       http://repo.packagist.org/p/provider-2013$39889488e431198f82366f24d4b180f004da7736a9d8f247d692e2f180d2dbb5.json
    6/13:       http://repo.packagist.org/p/provider-2019-10$17d016ac04270b4ccec878f822df806633210e680d23e91223773a7476fc2928.json
    7/13:       http://repo.packagist.org/p/provider-2014$f531fb62fcdcfcbcd019cb7df7e5f2fb4fe860952bac14327cf0da803cffdf47.json
    8/13:       http://repo.packagist.org/p/provider-2020-04$9c84e6a12b5d709b3c25c67e49f40c47fdf2ac19041fcd9395f0cf41d7dcf584.json
    9/13:       http://repo.packagist.org/p/provider-2016$72528073687616725bf4dc2545df15be8f7292439eea59a7bed3b426e32b4068.json
    10/13:      http://repo.packagist.org/p/provider-2020-01$87da2159a7702f797d9b1bb5b52e173120c3dcbc0838e0faae8e31115e4fa412.json
    11/13:      http://repo.packagist.org/p/provider-2019$c07e756600076bbb7777812537eb93470e0bc4af1f3501adc21a25408559c8df.json
    12/13:      http://repo.packagist.org/p/provider-2017$a37bcaf7aa1681386f75e2e3c3413a0ca1c7a0c6f68a32b65b72a2830f1b66c6.json
    13/13:      http://repo.packagist.org/p/provider-2018$767a721682b30f7de86dcbd26a7e2cde2a6b1e80e45071d19534195038001313.json
    Finished: success: 13, skipped: 0, failure: 0, total: 13
Creating a "drupal/recommended-project" project at "./my-project"
Installing drupal/recommended-project (8.8.6)
  - Installing drupal/recommended-project (8.8.6): Downloading (100%)
Created project in /var/www/drupal-sites/test/test-composer/my-project
    1/17:       https://packages.drupal.org/8/drupal/provider-2016-4$d1e39b502f8a618c4fa44b26ee595b702b0da2f43eba22a656cc1adde0d0d716.json
    3/17:       https://packages.drupal.org/8/drupal/provider-2016-1$81eb6550cd83f95e428410d35d65dba5f7d6ca0b55d2da40969c8eb29af21b5c.json
    3/17:       https://packages.drupal.org/8/drupal/provider-2017-4$c3498800b002f256dd02f21c2f4fcb0b8aa01abbd572132e9d766c9e129a34d4.json
    4/17:       https://packages.drupal.org/8/drupal/provider-2016-3$2a507d52ff9075aaa220790bc47c7d145f72b38d1ad8473feca37d48a678a178.json
    5/17:       https://packages.drupal.org/8/drupal/provider-2017-1$bf40ae7dea17e793e6317be1337de70b381185791ecd4c3b8efffc759271f9e8.json
    6/17:       https://packages.drupal.org/8/drupal/provider-2017-2$87d8a19beaf77aeb2ebf1c8be43426f2737df0092ad02c46c5bb1ee7be2cfbe6.json
    7/17:       https://packages.drupal.org/8/drupal/provider-2018-1$4c096cbecca1d633542e13db3e0c1d39eda0652e4e72642072ac5de12ea88d9a.json
    8/17:       https://packages.drupal.org/8/drupal/provider-2017-3$3b9d202f37a91bc9fc30e3fb3daf60afb9f1a8ff0344092e5c419ec7a39fdd4f.json
    9/17:       https://packages.drupal.org/8/drupal/provider-2018-2$24c6ba374aa97d97823691b467f8ebc738459bedd52d6f281fc294b04b75fc1c.json
    10/17:      https://packages.drupal.org/8/drupal/provider-2018-4$1e59a6c86a5a05aa1cb4de10bfe447a67203d1259378a3073d4098461c493ed1.json
    11/17:      https://packages.drupal.org/8/drupal/provider-2018-3$4ed4b279320e650cb2522a5e20a940767452a52818786367e23c3a824d11d8a3.json
    12/17:      https://packages.drupal.org/8/drupal/provider-2019-4$24f3a854aac4180af0e1c43538a18367e5b1a58a8d85511545612e2a43d79b1d.json
    13/17:      https://packages.drupal.org/8/drupal/provider-2019-1$04a753a98f7830de3fbea121439646ce37eb3a8456eaf2472b76921b46b35ac0.json
    14/17:      https://packages.drupal.org/8/drupal/provider-2019-3$a90c33c503c38a1fdc12c3f2e8648b5c769ed0053e859254197d7bbdf431bc9d.json
    15/17:      https://packages.drupal.org/8/drupal/provider-2020-1$7fb2c36d6ae9589d91b2f2d3a0932621c085af35ff455a0025b62442da1df1fa.json
    16/17:      https://packages.drupal.org/8/drupal/provider-2019-2$c0785535711edccee4a989445d9b247cc8f34b8c72dc2e231397e69d414ef849.json
    17/17:      https://packages.drupal.org/8/drupal/provider-2020-2$54ef6d9ee2d92bea20176a9121dd47a364ab4556cb772c9cc2da5834ca0a69e3.json
    Finished: success: 17, skipped: 0, failure: 0, total: 17
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
    1/3:        https://codeload.github.com/drupal/core-recommended/legacy.zip/361d61f272767e0e34f8ac8c7a51e7c14e387714
    2/3:        https://codeload.github.com/drupal/core-project-message/legacy.zip/10be18c6a401de8e243777de6a74cb45a7ecacad
    3/3:        https://codeload.github.com/drupal/core/legacy.zip/a5daf2aa45bbc72da72e1e64d5261f746ffb508c
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Package operations: 56 installs, 0 updates, 0 removals
  - Installing drupal/core-composer-scaffold (8.8.6): Loading from cache
  - Installing drupal/core-project-message (8.8.6): Loading from cache
  - Installing composer/installers (v1.7.0): Loading from cache
Plugin installation failed (include(/var/www/drupal-sites/test/test-composer/my-project/vendor/composer/installers/src/Composer/Installers/Plugin.php): failed to open stream: No such file or directory), rolling back
  - Removing composer/installers (v1.7.0)


  [RuntimeException]
  Could not delete /var/www/drupal-sites/test/test-composer/my-project/vendor
  /composer/installers/src/Composer:


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

### Summary

It appears to be a composer problem.

Normal working with the VM works alright. If I work on already created projects, composer install and also core updates run smoothly. 

Only when trying to create a fresh drupal project from drupal/recommended-project running

`composer create-project drupal/recommended-project my-project`

I run into the above error every time.

Normally the "could not delete xy" means there is a composer timeout. But I have set composer timeout to a very high value and the error happens very fast, so this is not it, for normally a timeout happens only after a long time indicating it is really a problem.

I have tried to use a lower Virtualbox version as recommended in some tickets, but to no avail.
It would be a shame to go back to an older Virtualbox version, because this new version runs so much faster.

Anybody seen this and got an idea?
I saw somebody had a similar issue here
https://github.com/geerlingguy/drupal-vm/issues/1421
but no solution.

**Comment by eigentor** [comment]
I run Drupalvm a bit in a special way: I do not install drupal with the machine but create the drupal projects in subfolder seperately. I install all the drupal installatsions later. Thus I have modified config.yml quite a bit. Maybe this configuration does not play well with the newest Drupalvm and vagrant versions. For better understanding here my complete config.yml. After the application-jjv.test there are normally a lot more vhosts that I have left out for privacy reasons.
```

---
# Available `vagrant_box` values include:
#   - geerlingguy/drupal-vm (pre-provisioned, based on Ubuntu 18.04)
#   - geerlingguy/centos8
#   - geerlingguy/centos7
#   - geerlingguy/debian10
#   - geerlingguy/debian9
#   - geerlingguy/ubuntu1804
#   - geerlingguy/ubuntu1604
vagrant_box: geerlingguy/drupal-vm

vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: drupalvm-0520.test
vagrant_machine_name: drupalvm-0520
vagrant_ip: 192.168.88.92

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/ for more.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: drupal-sites
    destination: /var/www/drupal-sites
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 7000
vagrant_cpus: 2

# Ensure vagrant plugins are installed.
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater

ansible_python_interpreter: python3

# Minimum required versions.
drupalvm_vagrant_version_min: '2.2.0'
drupalvm_ansible_version_min: '2.8'

# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
drupal_db_backend: mysql

# Set this to 'false' if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
drupal_build_makefile: false
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"
drush_make_options: "--no-gitinfofile"

# Set 'drupal_build_makefile' to 'false' and this to 'true' if you are using a
# composer based site deployment strategy.
drupal_build_composer: false
drupal_composer_path: "{{ config_dir }}/drupal.composer.json"
# drupal_composer_install_dir: "/var/www/drupalvm/drupal"
drupal_composer_dependencies:
  - "drupal/devel:^1.2"

# Set this to 'true' and 'drupal_build_makefile', 'drupal_build_composer' to 'false'
# if you are using Composer's create-project as a site deployment strategy.
drupal_build_composer_project: false
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Required Drupal settings.
drupal_core_path: "/var/www/drupal-sites"
drupal_core_owner: "{{ drupalvm_user }}"
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal
drupal_db_host: localhost

# Settings for installing a Drupal site if 'drupal_install_site:' is 'true'.
drupal_major_version: 8
# drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin

# Additional arguments or options to pass to `drush site-install`.
drupal_site_install_extra_args: []

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: true
drush_aliases_host_template: "templates/drupalvm.aliases.drushrc.php.j2"
drush_aliases_host_template_yml: "templates/drupalvm.aliases.yml.j2"
drush_aliases_guest_template: "templates/drupalvm-local.aliases.drushrc.php.j2"
drush_aliases_guest_template_yml: "templates/drupalvm-local.aliases.yml.j2"

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  #- servername: "{{ drupal_domain }}"
  #  serveralias: "www.{{ drupal_domain }}"
  #  documentroot: "{{ drupal_core_path }}"
  #  extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  #########################################
  ##################  Jobs ################
  #########################################

  - servername: "application-jjv.test"
    serveralias: "www.application-jjv.test"
    documentroot: "/var/www/drupal-sites/jobs/application-jjv"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  
apache_packages_state: latest
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - headers.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"
    is_php: true

nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_vhost_template: "templates/nginx-vhost.conf.j2"

# MySQL databases and users.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

# PostgreSQL databases and users.
postgresql_users:
  - name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"

postgresql_databases:
  - name: "{{ drupal_db_name }}"
    owner: "{{ drupal_db_user }}"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  - tideways
  # - upload-progress
  - varnish
  - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

firewall_enabled: true
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# PHP Configuration. Currently-supported versions: 7.2, 7.3, 7.4.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.2"
php_install_recommends: no
php_memory_limit: "500M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_post_max_size: "1000M"
php_upload_max_filesize: "1000M"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php7.0 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ drupalvm_user }}/.composer"
composer_home_owner: "{{ drupalvm_user }}"
composer_home_group: "{{ drupalvm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }

# Run specified scripts before or after VM is provisioned. Use {{ playbook_dir }}
# to reference the provisioning/ folder in Drupal VM or {{ config_dir }} to
# reference the directory where your `config.yml` is.
pre_provision_scripts: []
post_provision_scripts: []
  # - "{{ playbook_dir }}/../examples/scripts/configure-solr.sh"

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php
mysql_max_allowed_packet: 1000M

# Node.js configuration (if enabled above).
# Valid examples: "6.x", "8.x", "10.x", etc.
nodejs_version: "10.x"
nodejs_npm_global_packages:
  - name: npm
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ drupalvm_user }}"
ruby_install_gems: []

# Varnish Configuration (if enabled above).
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_version: 2.9.5
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: no
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"

# Java configuration.
java_packages:
  - "{{ 'openjdk-8-jdk' if ansible_os_family == 'Debian' else 'java-1.8.0-openjdk' }}"

# Solr configuration.
solr_version: "7.7.2"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.53.0

# Docker configuration.
docker_container_name: drupal-vm
docker_image_name: drupal-vm
docker_image_path: ~/Downloads

# Other configuration.
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts
hostname_configure: true
hostname_fqdn: "{{ vagrant_hostname }}"
ssh_home: "{{ drupal_core_path }}"

```
