### ISSUE TITLE
Apache Alias in config.yml?

### ISSUE THREAD

**Issue by solomonrothman** [geerlingguy/drupal-vm#2049]
There is no documentation on aliases, should these be added directly to the VM or is there a way in the config.yml to easily accomplish this?

### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

**Comment by eigentor** [comment]
Directly adding them inside the VM is no Alternative for you? I think aliases and stuff are some of the few things that do not have to be done through config.yml
e.g. I set Composer timout and memory limit directly inside bash.profile.

**Comment by phizev** [comment]
The syntax you are using is not supported in any manner. Using `extra_parameters` documented 
 in the [ansible-role-apache](https://github.com/geerlingguy/ansible-role-apache) role in the config.yml should allow you to add anything to the virtual host.

Example from the documentation:
```yaml
  - servername: "www.local.dev"
    serveralias: "local.dev"
    documentroot: "/var/www/html"
    extra_parameters: |
      RewriteCond %{HTTP_HOST} !^www\. [NC]
      RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
