### ISSUE TITLE
GuestAdditions seems to be installed (6.1.16) correctly, but not running.

### ISSUE THREAD

**Issue by caschbre** [geerlingguy/drupal-vm#2125]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.14
VirtualBox 6.1.16r140961
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/caschbre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
```

### Your OS

 - **Linux** (version)

### Full console output

https://gist.github.com/caschbre/750cf29520ab1ad4276d6e67848b9664

### Summary

I recently rebuilt my local Drupal 7 installation which already had drupalvm configured in the repo.  I was previously using an older version of drupalvm so I updated to the most recent and then ran vagrant up.  Everything seems to have provisioned and I'm able to access my local site.  However every time I do a vagrant up I noticed that I'm seeing "GuestAdditions seems to be installed (6.1.16) correctly, but not running."

One change I did make to my local config.yml was to add the following to eliminate using vagrant-hostsupdater.

```
vagrant_plugins:                                                                                                                                                                                                                                                                      
  - name: vagrant-vbguest                                                                                                                                                                                                                                                             
  - name: vagrant-cachier                                                                                                                                                                                                                                                             
  # - name: vagrant-hostsupdater
```
