### ISSUE TITLE
Provisioning fails with Ansible failed to complete successfully error

### ISSUE THREAD

**Issue by dottodot** [geerlingguy/drupal-vm#2149]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.14
VirtualBox 6.1.16r140961
ansible 2.10.5
```

### Your OS

 - **macOS** 10.15.7

### Full console output

```
vagrant provision
vagrant up --provision
```

https://gist.github.com/dottodot/52f17abc702e7d536d5a0e381a3e53ad

Config

```
vagrant_synced_folders:
  - local_path: ~/Projects/example
    destination: /var/www/drupalvm/example
    type: nfs

drupal_install_site: false

mysql_databases:
  - name: example
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: root
    host: "%"
    password: root
    priv: "drupal.*:ALL"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "example.test"
    documentroot: "/var/www/drupalvm/example/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_vhosts_ssl:
  - servername: "example.test"
    documentroot: "/var/www/drupalvm/example/web"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/drupalvm/example/web"

installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+

  # XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_version: 2.9.5
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: VSCODE
php_xdebug_max_nesting_level: 256
php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"
php_xdebug_remote_port: 9969
```

### Summary

I'm new to drupalvm and not sure if it always had the error but noticed it when I tried adding ssl which I couldn't get to work. So I ended up using `vagrant destroy` which got the ssl working. However I then went to add xdebug and got the same issue and xdebug isn't working.

I can access my site though.
