### ISSUE TITLE
Archlinux host. Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by korzh-nick** [geerlingguy/drupal-vm#2160]
### Issue Type
 - Bug Report / Support Request

### Your Environment
linux 5.11.15.arch1-2
docker 1:20.10.6-1
docker-compose 1.29.1-1
dbus 1.12.20-1
dbus-glib 0.112-1

### Your OS

 - **Linux** Archlinux

### Full console output

root@7579bc3d9031:/# systemctl
Failed to connect to bus: No such file or directory

### Summary

After a recent update (not updated for a long time), systemctl stopped starting in the container. It turns out that drupalvm in docker does not work in archlinux now. The configuration is standard. 

```yaml
---
version: "3"

services:

  drupal-vm:

    ports:
      - 8001:80
      - 443
      - 3306
      - 8025:8025

    dns:
      - '8.8.8.8'
      - '8.8.4.4'

    volumes:
      - ./:/var/www/drupalvm/:rw,delegated
      - /var/lib/mysql
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    privileged: true
    command: /lib/systemd/systemd

    networks:
      drupalvm:
        ipv4_address: 184.168.89.89

networks:

  drupalvm:
    driver: bridge
    driver_opts:
      ip: 184.168.89.1
    ipam:
      config:
        - subnet: "184.168.89.0/16"

```
