### ISSUE TITLE
Malformed Ansible Version

### ISSUE THREAD

**Issue by philip-elevated** [geerlingguy/drupal-vm#2166]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.16
VirtualBox 6.1.22r144080
ansible [core 2.11.1]
  config file = None
  configured module search path = ['/Users/chris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/chris/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.1
  libyaml = True
```

### Your OS
 - **macOS** (version)

### Full console output
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/chris/Sites/devdesktop/alliedtel-dev2/Vagrantfile
Line number: 0
Message: ArgumentError: Malformed version number string [core
```

### Summary
I cannot seem to run `vagrant up` with newest version of Ansible. It appears as if the version number is displayed in brackets now?

**Comment by philip-elevated** [comment]
I've tried using Ansible installed via `pip3` as well as Ansible installed via HomeBrew.

**Comment by geerlingguy** [comment]
It looks like the error is showing you have an issue with the Vagrantfile?

```
Path: /Users/chris/Sites/devdesktop/alliedtel-dev2/Vagrantfile
Line number: 0
Message: ArgumentError: Malformed version number string [core
```

The first line there?

**Comment by philip-elevated** [comment]
@geerlingguy - I'm using a Composer managed version of DrupalVM, so my Vagrantfile simply references that and custom config.

Vagrantfile:
```
# The absolute path to the root directory of the project.
ENV['DRUPALVM_PROJECT_ROOT'] = "#{__dir__}"

# The relative path from the project root to the VM config directory.
ENV['DRUPALVM_CONFIG_DIR'] = "settings"

# The relative path from the project root to the Drupal VM directory.
ENV['DRUPALVM_DIR'] = "vendor/geerlingguy/drupal-vm"

# Load the real Vagrantfile
load "#{__dir__}/#{ENV['DRUPALVM_DIR']}/Vagrantfile"
```

Custom config
```
##
# DrupalVM Overrides
# - 01 - Vagrant Settings
# - 02 - Drupal Settings
# - 03 - Installed Extras
# - 04 - PHP Settings
##

# 01 - Vagrant Settings
vagrant_project_name: ats
vagrant_ip: 192.168.87.87
vagrant_hostname: 'ats.dvm'
vagrant_machine_name: '{{ vagrant_project_name }}'
vagrant_synced_folders:
  - local_path: .
    destination: '/var/www/{{ vagrant_project_name }}'
    type: nfs
    create: true

# 02 - Drupal Settings
drupal_composer_install_dir: '/var/www/{{ vagrant_project_name }}'
drupal_build_composer_project: false
drupal_install_site: false
drupal_core_path: '{{ drupal_composer_install_dir }}/docroot'

# 03 - Installed Extras
installed_extras:
  - adminer
  - drush
  - mailhog
  - memcached
  - varnish
  - xdebug

# 04 - PHP Settings
php_version: "7.4"
php_memory_limit: "512M"

```
