### ISSUE TITLE
excluded_paths only for rsync?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2191]
On Windows 10 as a host:
```
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
    excluded_paths:
      - .github
      - docs
      - examples
      - drupal/web/sites/default/files
      - tmp

```

Is there any way to use excluded_paths on `type: nfs`  synced folders?
How?
If some folders are excluded (e.g. twig cache) Drupal should run faster on actions like cacheclear.
