### ISSUE TITLE
VM not starting on vagrant up

### ISSUE THREAD

**Issue by rhuffstedtler** [geerlingguy/drupal-vm#231]
I think the issue is occuring when it is trying to setup the shared folders. It just hangs.

This is on Windows7, VBox 5.0.2, vagrant 1.7.4.

Trying to use the example config and make files, with one small change. This is my 
vagrant_synced_folders config:

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: D:/Sites/drupalvm
    destination: /var/www
    id: drupal
    type: smb
    create: true
```
Last few lines of output when running vagrant up --debug are:
DEBUG host: Searching for cap: nfs_prune
DEBUG host: Checking in: windows
 INFO nfs: Host doesn't support pruning NFS. Skipping.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SyncedFolderCleanup
:0x3df9c20>
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\
v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "$PSVersionT
able.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 2
