### ISSUE TITLE
Problems with changing sync folder

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#258]
Hello,

Based on the issues described in #245 I ended up using `rsync` as my sync method, worked great. I set up an entry that looked like this:

``` yml
  - local_path: ~/src/example/docroot
    destination: /var/www/example
    type: rsync
    id: example
```

Everything works great, `vagrant rsync-auto` works like a charm.

Then I realized I'd actually like to sync the entire `~/src/example` directory, because `~/src/example/tests` has a bunch of useful stuff. So, I changed the entry to this:

``` yml
  - local_path: ~/src/example
    destination: /var/www/example
    type: rsync
    id: example
```

And adjusted my vhost entry to point to `~/src/example/docroot`.

`vagrant reload --provision` then updated my directories & vhost correctly (or so I thought -- I could access the site without issue anyway). But then I ran `vagrant rsync-auto`, and saw these two entries:

```
==> drupalvm: Rsyncing folder: /home/kosta/src/example/docroot/ => /var/www/example
==> drupalvm: Rsyncing folder: /home/kosta/src/example/ => /var/www/example
```

So it looks like the old entry is hanging around somewhere.

As an experiment, I set entirely new values for `destination` and `id` (e.g. `/var/www/testing`) but still running into the same problem.

I guess I could do `vagrant destroy` but I don't want to have to re-import all my VM databases again, since I've got 5 loaded up there already.

Any suggestions on what I could try next?

**Comment by geerlingguy** [comment]
@kostajh - That seems like it would be a Vagrant or local environment issue—typically when I change the synced folders, it picks up the changes correctly after a `reload`. Can you paste in the entire synced folders configuration? Maybe one of your other entries is causing this issue.

Another thing to try is quitting Terminal and starting again. Maybe there's some environment variable that's stuck throwing Vagrant `rsync` for a loop.

**Comment by kostajh** [comment]
Here's my [config.yml](https://gist.github.com/febbbfec32210c8305eb)

I already checked `ps aux | grep rsync` to look for any stale processes, no luck there. I guess I can always try restarting the host to see what happens!

**Comment by kostajh** [comment]
Restarting the host didn't solve my problems. The initial `vagrant reload --provision` rsyncs the directories as I'd like them to be. But then `vagrant rsync-auto` loads stale configuration issues. Do you have any ideas where `vagrant rsync-auto` might be loading these stale configuration entries from?

Here's the synced folder config:

``` yaml
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  # work
  - local_path: ~/src/test
    destination: /var/www/etest
    type: rsync
    id: etest
  - local_path: ~/src/anothertest
    destination: /var/www/anothertest
    type: rsync
    id: anothertest
  # personal
  - local_path: ~/src/fbn/public_html
    destination: /var/www/fbn
    type: rsync
    id: fbn
```

And when I do `vagrant reload --provision` I see:

```
==> drupalvm: Rsyncing folder: /home/kosta/src/test/ => /var/www/etest
==> drupalvm: Rsyncing folder: /home/kosta/src/anothersite/ => /var/www/anothersite
==> drupalvm: Rsyncing folder: /home/kosta/src/fbn/public_html/ => /var/www/fbn
```

But then I fire up `vagrant rsync-auto`:

```
  ((2.1.0)) $ vagrant rsync-auto
==> drupalvm: Doing an initial rsync...
==> drupalvm: Rsyncing folder: /home/kosta/src/test/drupal/ => /var/www/test
==> drupalvm: Rsyncing folder: /home/kosta/src/test/ => /var/www/eomega
==> drupalvm: Rsyncing folder: /home/kosta/src/anothersite/ => /var/www/anothersite
==> drupalvm: Rsyncing folder: /home/kosta/src/fbn/public_html/ => /var/www/fbn
==> drupalvm: Rsyncing folder: /home/kosta/src/test/ => /var/www/eomega
==> drupalvm: Watching: /home/kosta/src/fbn/public_html
==> drupalvm: Watching: /home/kosta/src/anothersite
==> drupalvm: Watching: /home/kosta/src/test
==> drupalvm: Watching: /home/kosta/src/test
==> drupalvm: Watching: /home/kosta/src/test/drupal
```
