### ISSUE TITLE
drush make hangs when using git as a download type

### ISSUE THREAD

**Issue by levelos** [geerlingguy/drupal-vm#264]
Adding a profile to `drupal.make.yml` causes Ansible to hang at `TASK: [Generate Drupal site with drush makefile.]`. I've tried numerous different profiles, and different download techniques, with the same result. I've also tried calling `drush make` directly using the same make file (with the profile included), and that works fine. Example make file below:

```
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "7.x"

projects:

  drupal:
    version: "7.39"

  commerce_kickstart:
    version: "2.28"
```
