### ISSUE TITLE
Removing apache vhosts from config.yml will fail drush alias creation

### ISSUE THREAD

**Issue by wroxbox** [geerlingguy/drupal-vm#300]
Remove apache_vhosts from config.yml

```
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
```
Change to 
```
nginx_hosts:
  - server_name: "{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true
```
will fail drush alias creation, because the loops need {% for vhost in apache_vhosts %}

This can be fixed by changing two files 
drupalvm-local.aliases.drushrc.php.j2

```
{% for vhost in nginx_hosts %}
$aliases['{{ vhost.server_name }}'] = array(
  'uri' => '{{ vhost.server_name }}',
  'root' => '{{ vhost.root }}',
);
{% endfor %}
```
and drupalvm.aliases.drushrc.php.j2

```
{% for vhost in nginx_hosts %}
$aliases['{{ vhost.server_name }}'] = array(
  'uri' => '{{ vhost.server_name }}',
  'root' => '{{ vhost.root }}',
  'remote-host' => '{{ vhost.server_name }}',
  'remote-user' => 'vagrant',
  'ssh-options' => '-o PasswordAuthentication=no -i ~/.vagrant.d/insecure_private_key',
);
{% endfor %}
```

Also servername should be server_name and documentroot should be root

This could be also done by providing two templates for both servers
```
- name: Configure drush aliases for root user inside VM.
  template:
    src: ../templates/drupalvm-{{ drupalvm_webserver }}-local.aliases.drushrc.php.j2
    dest: "~/.drush/{{ vagrant_machine_name }}.aliases.drushrc.php"
```
when: drupalvm_webserver == 'nginx'
