### ISSUE TITLE
Single mysql user and multiple databases

### ISSUE THREAD

**Issue by jnettik** [geerlingguy/drupal-vm#319]
I wasn't able to find anything on this in the issues or docs, but I need to allow one of my mysql users to have access to two mysql databases. Is there a way to do that in the config file, or is the only way to manually set that up on the VM?

**Comment by geerlingguy** [comment]
Yep! You can do this a few different ways. One of the most common:

```yaml
mysql_databases:
  - name: drupal
  - name: myproject
  - name: anotherproject
  - name: yetanother

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"
  - name: myproject
    host: "%"
    password: secure
    priv: "myproject.*:ALL"
```

...etc. - You can either have one user with rights to all databases, or add a user with access to each database, etc. See the [geerlingguy.mysql role](https://github.com/geerlingguy/ansible-role-mysql) for other MySQL options you can configure in config.yml.
