### ISSUE TITLE
New multisite strategy

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#33]
Currently if you want to install multiple Drupal sites inside the VM, you have to edit a couple things, e.g.:

```yaml
vagrant_synced_folders:
  - local_path: ~/Sites/drupal
    destination: /drupal
    excluded_paths: [".git/"]
    id: drupal
    type: rsync
```

```yaml
apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}
```

...also, the VM installs the site defined in `drupal.make.yml` by default, with no option to disable. It would be much more flexible and simple if there was a way to define multiple Drupal sites, and use a `deployment_strategy` per site (or something like that) to deploy it inside the VM.

That way, I could maybe have one site located at `~/Sites/my-site` which has a `.make.yml` file to install, another site at `~/Sites/company-site` which has a full Drupal codebase and would just need to be synced inside the VM...

I'm trying to think through the best syntax for this that would be the least complex, most flexible, and also not a pain to maintain inside Ansible and Vagrant (e.g. dynamically creating the `apache_vhosts` and `vagrant_synced_folders` variables).

Maybe something like the following:

```yaml
drupal_sites:

  - servername: drupaltest.dev
    local_path: ~/Sites/my-site
    dest_path: /var/www/my-site
    deployment_strategy: drush_make
    makefile: drupal.make.yml
    sync_method: rsync

  - servername: drupaltest.dev
    local_path: ~/Sites/company-site
    dest_path: /var/www/company-site
    deployment_strategy: full_repository
    sync_method: nfs
```

Another potential advantage here is that we might be able to fabricate a Drush alias file for the entire VM from within the Ansible playbook, and either place it in the right place locally/automatically, or stick it inside the VM somewhere and let the user grab it if so desired.

I'd like the default configuration/example still to just install the latest version of Drupal core with a makefile (since that's my preferred method of site development/deployment these days anyways), but if it were this easy to have multiple sites inside one VM, I would be able to use the `drupal-dev-vm` for almost all my Drupal sites (at least all the ones that don't rely on exotic configurations or specific versions of software...).
