### ISSUE TITLE
Update PHP7 docs to mention configuration is specific to Apache/Ubuntu

### ISSUE THREAD

**Issue by illepic** [geerlingguy/drupal-vm#336]
As per #332, the following configuration in the PHP7 docs needs explanation that it specifically works for PHP7 on Apache and Ubuntu 14.04:

```yaml
drupalvm_webserver: apache
...
php_version: "7.0"
php_packages:
  - libapache2-mod-php7.0
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php-gd
  - php-curl
  - php-imap
  - php-json
  - php-opcache
php_mysql_package: php-mysql
php_fpm_daemon: php7.0-fpm
```
