### ISSUE TITLE
PHP7 configuration in docs needs updating for nginx

### ISSUE THREAD

**Issue by illepic** [geerlingguy/drupal-vm#337]
As per #332, the following update fails for Ubuntu + nginx + PHP7:

```yaml
drupalvm_webserver: nginx
...
php_version: "7.0"
php_packages:
#  - libapache2-mod-php7.0 # commented out because apache-specific
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php-gd
  - php-curl
  - php-imap
  - php-json
  - php-opcache
php_mysql_package: php-mysql
php_fpm_daemon: php7.0-fpm
```

**Comment by joestewart** [comment]
The php role was recently updated to allow for overriding php_fpm_daemon.  Be sure to upgrade.
https://github.com/geerlingguy/ansible-role-php/pull/62

The nginx-vhost.conf.j2 template will need a variable substitution for this line:

  "fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;"

https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/templates/nginx-vhost.conf.j2#L35

I had an issue with Drupal console as well but not sure if that is recent issues, my local or what yet.
Also had to disable xdebug, but the Drupal 8 site is now being served by nginx and fpm.

**Comment by illepic** [comment]
@joestewart, any tips on how to upgrade the php role? Is that something that is pulled down automatically if I `git pull` in this repo and then `vagrant provision`? (This is my first foray deep into Ansible).

**Comment by geerlingguy** [comment]
@illepic - Run `sudo ansible-galaxy install -r provisioning/requirements.yml --force` in the same directory as the Vagrantfile.

**Comment by illepic** [comment]
Cheers!

**Comment by illepic** [comment]
A quick note on my local working Ubuntu 14 + PHP7 FPM + nginx config within Drupal VM:

**provisioning/templates/nginx-vhost.conf.j2**
Changed

    fastcgi_pass unix:/var/run/php5-fpm.sock;

to

    fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;

**config.yml**
```yaml
drupalvm_webserver: nginx
...
php_version: "7.0"
# php_version: "5.6"
php_packages:
#  - libapache2-mod-php7.0
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php-gd
  - php-curl
  - php-imap
  - php-json
  - php-opcache
php_mysql_package: php-mysql
php_fpm_daemon: php7.0-fpm
php_extension_conf_path: /etc/php7.0/fpm/conf.d
...
installed_extras:
  - adminer
#  - drupalconsole
  # - mailhog
  # - memcached
  - nodejs
  # - pimpmylog
  # - ruby
  # - selenium
  # - solr
#  - varnish
#  - xdebug
#  - xhprof
```

The first `vagrant up` fails due to Apache not being able to restart. However, if we include the `libapache2-mod-php7.0` package, then the system automatically defaults to Apache. Instead, commenting out this package and allowing the first `vagrant up` to fail and then immediately running `vagrant provision` gets us to a fully working PHP7/nginx state.

You can also see that I'm commenting out most of the extras for the sake of stability. Thank you @geerlingguy and @joestewart for the help.
