### ISSUE TITLE
Switch Apache to use FPM instead of mod_php

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#346]
By default, Apache 2.4 will use mod_php instead of FPM. I'd like to have Apache use FPM instead, to ensure extra consistency with Nginx and better overall performance.

**Comment by geerlingguy** [comment]
Steps to manually switch (at least on Ubuntu 14.04):

  1. `sudo apt-get install -y libapache2-mod-fastcgi`
  2. `sudo nano /etc/apache2/mods-enabled/fastcgi.conf`, and add the following inside:

      <IfModule mod_fastcgi.c>
        AddType application/x-httpd-fastphp5 .php
        Action application/x-httpd-fastphp5 /php5-fcgi
        Alias /php5-fcgi /usr/lib/cgi-bin/php5-fcgi
        FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -socket /var/run/php5-fpm.sock -pass-header Authorization
        <Directory /usr/lib/cgi-bin>
          Require all granted
        </Directory>
      </IfModule>

  3. `sudo a2enmod actions`
  4. `sudo service apache2 restart`

If it were just Ubuntu 14.04, I'd be adding the support immediately.

**Comment by geerlingguy** [comment]
It's actually much simpler, it seems... adding the line below will proxy requests through PHP-FPM in each Drupal site virtualhost:

```yaml
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "unix:/var/run/php5-fpm.sock|fcgi://localhost{{ drupal_core_path }}"
```

And as long as we have Apache 2.4 (e.g. use the below task to set it to 2.4 on Ubuntu 12.04), we can just enable mod_proxy_fcgi, and the above proxypass works wonderfully:

```yaml
- name: Add repository for Apache 2.4 on Ubuntu 12.04.
  apt_repository: repo='ppa:ondrej/apache2'
  when: ansible_distribution_version == "12.04"
```

I'm updating the freshly-renamed `geerlingguy.apache-php-fpm` role now, and will rename it on galaxy or delete/re-add it...
