### ISSUE TITLE
Selenium Question(s)

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#367]
I followed the docs on installing Selenium for DrupalVM, my config.yml for Behat looks correct. Upon executing (from PHPStorm, which is executing it remotely), it times out after 60 seconds and says it could not connect to port 7055 (not sure where it is getting that from). The config.yml is set to 4444.

If I were to get it running, is there a way to make it take screenshots on error?

I want a way where I can run Behat (which I can do with the goutte driver, without using Selenium) - but have the option to view what is happening from the browser so I can investigate when a test fails.

It's been a very long time since I have ran Selenium interactively, and want to get the option to do that again. With Behat it is possible to setup multiple profiles now, granting much more flexibility, and I have found that the best way to test AJAX functionality is with Selenium while watching it actually do it in a browser.

**Comment by geerlingguy** [comment]
@kevinquillen - Yes, you can get it working inside Drupal VM with the ability to do screenshots through the phantomjs driver... but I usually recommend people either set up CI with that level of detail/automation on a separate server (e.g. Jenkins) or on their host machine, since it will use an _actual_ browser instance, like FireFox. Drupal VM is much better imo for building the tests with a headless browser, though you can get it working either way (if you want screenshots).

I'll leave this ticket open in case anyone else wants to chime in with particular tips/tricks.

**Comment by kevinquillen** [comment]
I'll try again. I ran a selenium server on my host machine, told Behat that the selenium2 wd_host was 127.0.0.1:4444/wd/host. It just seemed to hang there.

Otherwise, everything else works great, I just want to be able to watch it execute in the browser on occasion.

**Comment by kevinquillen** [comment]
Here is an error I get when using @javascript to run scenarios, on the remote machine:

```
Could not open connection: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
r GMPProvider
1452182489157	addons.manager	DEBUG	Provider finished startup: GMPProvider
1452182489157	addons.manager	DEBUG	Starting provider: PluginProvider
1452182489157	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1452182489158	addons.manager	DEBUG	Provider finished startup: PluginProvider
1452182489158	addons.manager	DEBUG	Completed startup sequence
1452182489269	DeferredSave.extensions.json	DEBUG	Save changes
1452182489269	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"i6-vQYnZ7XYe","location":"app-profile","version":"2.46.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"descriptor":"/tmp/anonymous2640324584280819823webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1452182488000,"updateDate":1452182488000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8445045,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1452182489269	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1452182489275	DeferredSave.extensions.json	DEBUG	Save changes
1452182489275	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"i6-vQYnZ7XYe","location":"app-profile","version":"2.46.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous2640324584280819823webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1452182488000,"updateDate":1452182488000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8445045,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1452182489343	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1452182489343	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1452182489343	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1452182489403	DeferredSave.extensions.json	DEBUG	Starting write
1452182489528	addons.repository	DEBUG	No addons.json found.
1452182489529	DeferredSave.addons.json	DEBUG	Save changes
1452182489530	DeferredSave.addons.json	DEBUG	Starting timer
1452182489539	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1452182489539	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1452182489539	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1452182489543	DeferredSave.extensions.json	DEBUG	Write succeeded
1452182489543	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1452182489584	DeferredSave.addons.json	DEBUG	Starting write
1452182489599	DeferredSave.addons.json	DEBUG	Write succeeded
```

behat.yml:

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MarkupContext
    testmodule_features:
      paths:    [ %paths.base%/modules/testmodule/features ]
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MarkupContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://local.d8contrib:4444/wd/hub
      base_url: http://local.d8contrib
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '/var/www/docroot'
      region_map:
        content: "#content"
        highlighted: '.highlighted'
```

The default api driver works fine.

**Comment by kevinquillen** [comment]
This is odd... So, going off of that, I added this to drupalvm config.yml for firewall allowed ports:

```
  - "7055"
```

I also changed the selenium version to 2.48.2, which seems to be the latest stable release. Re provisioned, and now it works. I can run scenarios with selenium, or mix and match with the default driver or selenium.

This was necessary for what I was testing with BigPipe and all caching enabled in D8.

**Comment by geerlingguy** [comment]
Ah, I should've thought of that. The default set of allowed ports blocks the ports used for Selenium, so that makes sense. Let's add that to the docs (and/or open up that port in the default example config).

**Comment by kevinquillen** [comment]
So, back to the original issue now that that works... I added a new profile in my behat.yml:

```
hostmachine:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MarkupContext
    testmodule_features:
      paths:    [ %paths.base%/modules/testmodule/features ]
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MarkupContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
      base_url: http://local.d8contrib
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '/Users/kevinquillen/Servers/d8contrib/docroot'
      region_map:
        content: "#content"
        highlighted: '.highlighted'
```

I run this command in terminal, on my machine:

```
$ vendor/bin/behat -c behat.yml --profile hostmachine
```

I also started a selenium server on the host.

What I expect to happen is that Behat connects to the local selenium, opens a browser and I can watch it run through the scenarios.

Instead, this error pops up:

```
[PDOException]                              
SQLSTATE[HY000] [2002] Operation timed out 
```

The settings.php file has the right MYSQL connection, so I am not sure where it is failing at the moment. No activity occurs in the terminal window running selenium either.
