### ISSUE TITLE
Setup for writable files/folders

### ISSUE THREAD

**Issue by mroest** [geerlingguy/drupal-vm#373]
Hi,

How to setup the drupalvm for writable files/folders like sites/default/files or configuration/features export through the Drupal CMS UI?

I am using apache and sites/default/files is now owned by vagrant. Apache is unable to write in sites/default/files

**Comment by geerlingguy** [comment]
Can you give details on how you have synced folders configured in `config.yml`? For local development (since the site won't be on a shared/public server), I sometimes resort to chmod-nuking the files folder in a pinch (e.g. `sudo chmod -R 777` inside the VM on the `files` folder).

See also: http://docs.drupalvm.com/en/latest/extras/syncing-folders/

If there are more notes that could be added to that page to help make things more clear, please let me know.

**Comment by joshrickert** [comment]
I ended up fixing this with the vagrant-bindfs plugin. Some more details over in #284.

**Comment by geerlingguy** [comment]
Thanks, in that case I'll give a little more priority to #284.

**Comment by oxyc** [comment]
With https://github.com/geerlingguy/drupal-vm/pull/293 you can solve this using rsync as well (although you need custom scripts for pulling the generated code back to the host machine).

The docs are here http://docs.drupalvm.com/en/latest/extras/syncing-folders/#overriding-defaults. Depending on how granular you want to get with the permissions you could even go nuts with something like:

```yaml
vagrant_synced_folders:
  - local_path: docroot
    destination: /var/www/drupal
    type: rsync
    create: true
    excluded_paths: ['.git/', 'sites/default/files/', 'sites/all/modules/features']
    rsync_args: [
      "--verbose", "--archive", "--delete",
      "--chmod=u=rwX,go=rX", # 644 for files, 755 for directories
      "--owner", "--group", # required for the following command
      "--usermap=*:vagrant", "--groupmap=*:vagrant",
    ]
  - local_path: docroot/sites/default/files
    destination: /var/www/drupal/sites/default/files
    type: rsync
    create: true
    rsync_args: [
      "--verbose", "--archive", "--delete",
      "--chmod=gu=rwX,o=rX", # 664 for files, 775 for directories
      "--owner", "--group", # required for the following command
      "--usermap=*:vagrant", "--groupmap=*:www-data",
    ]
  - local_path: docroot/sites/all/modules/features
    destination: /var/www/drupal/sites/all/modules/features
    type: rsync
    create: true
    rsync_args: [
      "--verbose", "--archive", "--delete",
      "--chmod=gu=rwX,o=rX", # 664 for files, 775 for directories
      "--owner", "--group", # required for the following command
      "--usermap=*:vagrant", "--groupmap=*:www-data",
    ]
```

Personally I pull in files using a `Makefile` https://github.com/geerlingguy/drupal-vm/issues/261#issuecomment-144270339
