### ISSUE TITLE
Apache/PHP connection not working in 2.1.2 on Windows 7

### ISSUE THREAD

**Issue by itsgreggmarshall** [geerlingguy/drupal-vm#387]
I have a feeling there is some interaction with the configuration using 2.1.2 (required to have get past the ansible_local issue #372 on Windows 7.  While the build completes with no errors reported

     drupalvm: localhost                  : ok=198  changed=99   unreachable=0 failed=0

When I visit drupalvm.dev on my local machine I get the PHP listing instead of executed.  SSHing into the server shows index.php is executable.  And PHP -v gives 

     PHP 5.6.17-3+deb.sury.org~trusty+1 (cli)
     Copyright (c) 1997-2015 The PHP Group
     Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
         with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
         with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

Not sure what to look for, right now drupal-vm is pretty much a black box.

**Comment by geerlingguy** [comment]
@itsgreggmarshall - Try setting up your virtualhost like the updated example and see if that works:

https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L79-L83

**Comment by claudfernandes** [comment]
This is what I did to work

```
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "unix:/var/run/php5-fpm.sock|fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "adminer.drupalvm.dev"
    documentroot: "/opt/adminer"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "unix:/var/run/php5-fpm.sock|fcgi://127.0.0.1:9000/opt/adminer"

  - servername: "xhprof.drupalvm.dev"
    documentroot: "/usr/share/php/xhprof_html"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "unix:/var/run/php5-fpm.sock|fcgi://127.0.0.1:9000/usr/share/php/xhprof_html"


  - servername: "pimpmylog.drupalvm.dev"
    documentroot: "/usr/share/php/pimpmylog"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "unix:/var/run/php5-fpm.sock|fcgi://127.0.0.1:9000/usr/share/php/pimpmylog"
```
