### ISSUE TITLE
FPM ProxyPassMatch syntax with apache_vhosts_ssl for SSL support

### ISSUE THREAD

**Issue by tripper54** [geerlingguy/drupal-vm#415]
Hi,

I'm having trouble getting FPM working on an SSL apache host. Here are the relevant entries from my config:

````
apache_vhosts_ssl:
  - {
    servername: "mysite.vm",
    #serveralias: "www.mysite.vm",
    documentroot: "/var/www/mysite",
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/mysite"
    certificate_file: "/var/www/certs/server.crt",
    certificate_key_file: "/var/www/certs/server.key"
   }

````

This generates a 'found character that cannot start any token while scanning for the next token' syntax error on the "extra_parameters" line. I copied those 2 lines from the apache_vhosts section of my config. If I remove them FPM is not invoked, ie php is not processed.

Can anyone tell me what I'm doing wrong?

**Comment by geerlingguy** [comment]
Can you put the `extra_parameters` line as the last line in that configuration? Otherwise, with YAML syntax formatting, this will break since there's no comma at the end of the extra_parameters definition, and you're using the bracketed object syntax (`{}`).

A more common/compact definition would be:

```
apache_vhosts_ssl:
  - servername: "mysite.vm",
    #serveralias: "www.mysite.vm"
    documentroot: "/var/www/mysite"
    certificate_file: "/var/www/certs/server.crt"
    certificate_key_file: "/var/www/certs/server.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/mysite"
```

**Comment by tripper54** [comment]
Thanks for the quick reply! 

I tried your suggested definition, and got a "did not find expected key while parsing a block mapping" error on the - servername line.

I moving extra_parameters to the end of my bracketed definition, and still got a 'found character that cannot start any token while scanning for the next token' error on the extra_parameters line.

My amended definition:

````

apache_vhosts_ssl:
  - {
    servername: "mysite.vm",
    #serveralias: "www.mysite.vm",
    documentroot: "/var/www/mysite",
    certificate_file: "/var/www/certs/server.crt",
    certificate_key_file: "/var/www/certs/server.key",
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/mysite"
   }

````

Thanks again for taking the time to help this newb :)

**Comment by geerlingguy** [comment]
Oops, I left in one extra comma - since my example doesn't use the bracketed syntax, that's what broke it. Try this:

```yaml
apache_vhosts_ssl:
  - servername: "mysite.vm"
    #serveralias: "www.mysite.vm"
    documentroot: "/var/www/mysite"
    certificate_file: "/var/www/certs/server.crt"
    certificate_key_file: "/var/www/certs/server.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/mysite"
```
