### ISSUE TITLE
Make drush optional

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#449]
Would you be up for making the drush installation/configuration optional? My reasoning is that at work, we use Drupal VM on projects other than Drupal. Mainly Wordpress, and it fits perfectly. Drush is really the only non-optional installation step that's not useful for general php projects. https://github.com/generoi/bedrock/blob/genero/config/drupal-vm.config.yml

If we end up merging https://github.com/oxyc/drupal-vm/commit/8265f232e457d5ab4282c49777d0542a313d84fa that `vars/main.yml` could be a good spot to place the default variable if we want to "hide" the functionality.

**Comment by geerlingguy** [comment]
I think this is a good idea... but I'd like to fix up my `geerlingguy.drupal` role so it can be used (maybe within a loop even) to do Drupal installs instead of all the custom stuff in task includes in Drupal VM.

I'm thinking if we can define a list of `drupal_sites` (default to just the one), and that loop can be passed to the included role that allows install by makefile or composer, that kind of setup would be by far the nicest/most streamlined.

There are a few other architectural changes that would need to be made, but it could make Drupal VM a lot more flexible—and offer a great solution to other users who just want a good `geerlingguy.drupal` role to use.

**Comment by itsgreggmarshall** [comment]
I like the idea of having multiple Drupal sites, I was going to open an issue to request it (since I support about 40 Acquia Cloud sites, something DD2 does do well).

**Comment by oxyc** [comment]
Related to supporting multiple site installations #181, #33, #10.

**Comment by oxyc** [comment]
One issue that will come up once we do this is that the you would need to use arrays to reference the drupal variables in `apache_vhosts` and `nginx_hosts`.

```yaml
apache_vhosts:
  - servername: "{{ drupal_sites[0].drupal_domain }}"
    documentroot: "{{ drupal_sites[0].drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_sites[0].drupal_core_path }}"
```

This will break https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L35:L40 as it does not support arrays at the moment.

Maybe we can somehow use `with_items` for the webserver roles as well?
