### ISSUE TITLE
yo install not happening 

### ISSUE THREAD

**Issue by prathyushmr** [geerlingguy/drupal-vm#452]
the yo installation getting skipped 
config.yml  
nodejs_version: "4.*"
nodejs_npm_global_packages:
  - name: "yo"

**Comment by oxyc** [comment]
The `4.*` needs to be `4.x`, otherwise it should work. Does your config look like this:
```yaml
nodejs_version: "4.x"
nodejs_npm_global_packages:
  - name: "yo"
```
