### ISSUE TITLE
Creating the share folder on the host if it does not exist

### ISSUE THREAD

**Issue by prics** [geerlingguy/drupal-vm#48]
I think it will be a good idea to have a create key for share folder like this in config.yml
```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: ~/Sites/drupalvm
        destination: /var/www
        id: drupal
        type: nfs
        create: TRUE
```
and in Vagrantfile to do it like this
```
 for synced_folder in vconfig['vagrant_synced_folders'];
        config.vm.synced_folder synced_folder['local_path'], synced_folder['destination'],
            type: synced_folder['type'],
            rsync__auto: "true",
            rsync__exclude: synced_folder['excluded_paths'],
            rsync__args: ["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"],
            id: synced_folder['id'],
            create: synced_folder['create']
  end
```
