### ISSUE TITLE
Installing ChromeDriver on VM

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#481]
Following these instructions I was able to get Selenium & the Chrome Driver to work with my Behat Tests on the VM

```
sudo apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo dpkg -i google-chrome*.deb
sudo apt-get install -f
sudo apt-get install xvfb
sudo apt-get install unzip

wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
chmod +x chromedriver

sudo mv -f chromedriver /usr/local/share/chromedriver
sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
sudo apt-get install python-pip
```
source: http://christopher.su/2015/selenium-chromedriver-ubuntu/

I'm wondering if it would be helpful to turn this into an ansible recipe? I found this url but this is a bit over my head..

http://coryklein.com/ansible/2015/10/09/using-ansible-to-install-google-chrome.html

May try to figure this out but thought I'd ask first to see if anyone thinks this is a really bad idea for some reason. I'm was tried installing the firefox browser too but was getting weird selenium errors when trying to run my behat tests

Here's my behat.yml file for reference: 
```yaml
default:
  formatters:
    pretty: true
    progress: true
  gherkin:
    filters:
      tags: "~@skip"
  suites:
    default:
      contexts:
        - behatch:browser
        - behatch:debug
        - behatch:system
        - behatch:json
        - behatch:table
        - behatch:rest
        - behatch:xml
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Sanpi\Behatch\Extension: ~
    Behat\MinkExtension:
      base_url: http://ss.vm
      browser_name: 'chrome'
      goutte: ~
      selenium2:
        wd_host: "http://127.0.0.1:4444/wd/hub"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: '@ss.vm'
      drupal:
        drupal_root: '/var/www/ss/docroot'
      selectors:
        message_selector: '.messages'
        error_message_selector: '.messages.messages-error'
        success_message_selector: '.messages.messages-status'
```

Here's the Behatch feature > Scenario I was testing from within PHPStorm
```
Feature: Homepage
  In order to make sure the homepage isn't jacked
  As a anonymous website user
  I need to see a few key things

  # Requires chrome driver installed based on these instructions
  # http://christopher.su/2015/selenium-chromedriver-ubuntu/
  # included in post-install.sh now though
  @javascript
  Scenario: Behatch Browser Test
    Given I am on the homepage
    When I hover "#block-bartik-branding"
    Then I should see the text "Home"
```

And here's the working output
```
ssh://vagrant@192.168.88.88:22/usr/bin/php /home/vagrant/.phpstorm_helpers/behat.php --format PhpStormBehatFormatter --config /var/www/ss/btests/behat.yml /var/www/ss/btests/features/Homepage/Homepage.feature:30
Testing started at 3:27 PM ...

1 scenario (1 passed)
3 steps (3 passed)
0m5.30s (29.47Mb)

Process finished with exit code 0
```
