### ISSUE TITLE
Second site added to vm is using default vm database instead of its own?

### ISSUE THREAD

**Issue by mischacolley** [geerlingguy/drupal-vm#485]
Any ideas what I may have messed up with here? I appreciate that its not much info to go on. I've followed the instructions in http://docs.drupalvm.com/en/latest/deployment/local-codebase/ to add an existing site but I'm having a lot of difficulty getting it working. I can access drupalvm.dev fine but when I access mysite.dev its just hitting the same db? I've a second synced folder for my site, set both build_makefile and install_site to false and added my site as the second apache_vhosts and added the db for my second site. I've previously had this all working fine so feel like I've probably done something stupid. Anything obvious I should check or try?

**Comment by oxyc** [comment]
Do you mind posting your `config.yml`? Might help to figure out the problem.

**Comment by mischacolley** [comment]
Thanks. Doing more tests its like the document root for the second site just isn't getting picked up. If I go to `coronis.dev` its appears to be serving `drupalvm.dev`. I've tried reload and vagrant destroy etc but no luck fixing it. 

```yml

---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: drupalvm.dev
vagrant_machine_name: drupalvm
vagrant_ip: 192.168.88.88

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  - local_path: ~/Sites/drupalvm
    destination: /var/www/drupalvm
    type: nfs
    create: true
  - local_path: ~/Sites/coronis_site
    destination: /var/www/coronis_site
    type: nfs

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: apache

# Set this to false if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_makefile: false
drush_makefile_path: ../../drupal.make.yml

# Set this to false if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Settings for building a Drupal site from a makefile (if 'build_makefile:'
# is 'true').
drupal_major_version: 7
drupal_core_path: "/var/www/drupalvm/drupal"
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin
drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: drupal

# Additional arguments or options to pass to `drush site-install`.
drupal_site_install_extra_args: []

# Cron jobs are added to the root user's crontab. Keys include name (required),
# minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []
  # - {
  #   name: "Drupal Cron",
  #   minute: "*/30",
  #   job: "drush -r {{ drupal_core_path }} core-cron"
  # }

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_local_drush_aliases: true

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"
  
  - servername: "coronis.dev"
    documentroot: "/var/www/coronis_site"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"

apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"

nginx_remove_default_vhost: true

# MySQL Databases and users. If build_makefile: is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: "{{ drupal_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci
    
  - name: "coronis"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"

  - name: "root"
    host: "127.0.0.1"
    password: "root"
    priv: "coronis.*:ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - drupalconsole
  - mailhog
  - memcached
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  - varnish
  - xdebug
  - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - unzip

# `nodejs` must be in installed_extras for this to work. Valid examples: "0.10",
# "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages: []

# `ruby` must be in installed_extras for this to work.
ruby_install_gems_user: "{{ vagrant_user }}"
ruby_install_gems: []

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

drush_version: "master"
drush_keep_updated: true
drush_composer_cli_options: "--prefer-dist --no-interaction"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
firewall_log_dropped_packets: false

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0.
php_version: "5.6"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php5 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# Run specified scripts after VM is provisioned. Path is relative to the
# `provisioning/playbook.yml` file.
post_provision_scripts: []
  # - "../examples/scripts/configure-solr.sh"

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# Varnish Configuration.
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256

# Solr Configuration (if enabled above).
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.46.0

# Other configuration.
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts

```

**Comment by oxyc** [comment]
You should change this:
```yaml
  - servername: "coronis.dev"
    documentroot: "/var/www/coronis_site"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"
```
to
```yaml
  - servername: "coronis.dev"
    documentroot: "/var/www/coronis_site"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/coronis_site"
```

Then it should work

**Comment by mischacolley** [comment]
Thanks @oxyc ! That did the trick and I was up and running for a while. Unfortunately now I'm getting a constant 503 error. Could it be related to this? drupalvm.dev is fine. The site I'm working on is pretty massive and resource hungry so I've pushed the PHP memory limit up and tried disabling some of the installed extras but no lock. I've barely made any code edits to the site and I've reverted them all incase some bad code was causing it but no luck. Logs show "AH01067: Failed to read FastCGI header" and "AH01075: Error dispatching request to : " . I'm running out of ideas so wondering if you can think of anything else I should try.

**Comment by oxyc** [comment]
Same if you restart php-fpm: `service php5-fpm restart`?

Try disabling opcache by editing `/etc/php5/fpm/conf.d/05-opcache.ini` and setting `opcache.enable=0`.

You could also try raising the timeout by setting:
```
 ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/coronis_site timeout=60"
```

Unfortunately I'm quite new to PHP-FPM myself so not sure I can be to much help.

**Comment by mischacolley** [comment]
Yep same if I restart php-fpm. `opcache.enable=0` didn't appear to do anything and I'd already tried raising the timeout.

**Comment by geerlingguy** [comment]
Can you also increase the memory available inside the VM, setting `vagrant_memory` to 2048 or even 3072?

**Comment by mischacolley** [comment]
Yep tried that but still getting the 503 error. Any other ideas? I've managed to get the site up with kalabox (still with some out of memory errors but working) so I know there are defiantly no code issues so its some configuration with this VM. I've tried vagrant destroy etc but no luck. What could I do to start from scratch? What do I need to make sure is removed for a clean slate?

**Comment by mischacolley** [comment]
Ok so I finally solved this!!! Updating incase anyone else struggles with a series of seemingly similar issues. Basically three issues here.

- No 1. Was solved with the ProxyPassMatch update. Thanks for that!

Then once the site was working I started getting memory errors and then around the same time the 503 error. 

- No 2. I believe increasing both the `PHP memory limit` and probably also `vagrant_memory` sorted out the memory errors right away.

I couldn't tell though because I was still getting the 503 and it seemed like it was related.

I was abel to get the site working on a different VM with similar specs which was strange and I also reverted all my code changes with git so I thought I had confirmed no files where causing the issue. Wrong! One of the things I did between issue 1 and 2 was switch the codebase over to a `gulp` workflow and thus ran `npm install`. `node_modules` is git ignored so I missed that this stayed the same when I reverted my code and honestly I never thought to check something like that. Didn't know it could be an issue. I only found it because after repeatedly tweaking and rebuilding the vm I started combing through the code base piece by piece until I found and removed `node_modules` and it started working. That combined with noticing that I got `Segmentation fault: 11` when trying to clear the cache with drush led me to [this](http://drupal.stackexchange.com/questions/126880/how-do-i-prevent-drupal-raising-a-segmentation-fault-when-using-a-node-js-themin).

- No 3.  So I removed `node_modules` and added `"scripts": {
  "postinstall": "find node_modules/ -name '*.info' -type f -delete"
}` to `package.json` and re-ran `npm install` and life is good again.

**Comment by nkgokul** [comment]
```
I have added an apache vhosts entry for commerce.dev but when I visit commerce.dev on my host browser I am being redirected to the default drupal instance. Am I missing anything here?

# Apache VirtualHosts. Add one for each site you are running inside the VM. For                                                                                                      
# multisite deployments, you can point multiple servernames at one documentroot.                                                                                                     
# View the geerlingguy.apache Ansible Role README for more options.                                                                                                                  
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "Commerce"
    serveralias: "commerce.dev"
    documentroot: "/var/www/commerce_kickstart"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/commerce_kickstart"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ adminer_install_dir }}"

```
