### ISSUE TITLE
vagrant share port issues

### ISSUE THREAD

**Issue by jnettik** [geerlingguy/drupal-vm#487]
I'm trying to use `vagrant share` and am running into issues where DVM doesn't know what to do with the auto-generated URL that it receives. I found this tutorial that says to set each vhost at a unique port: http://www.brownfort.com/2014/10/vagrant-share-for-multiple-sites-in-the-same-vm/

Is this something that is currently possible in the config.yml file? Or is there a better way to do this already in DVM?

**Comment by oxyc** [comment]
If you're using nginx you can set the port
```yaml
nginx_hosts:
  - server_name: "site1.dev"
    root: "/var/www/site1/docroot"
    listen: 80
    is_php: true
  - server_name: "site2.dev"
    root: "/var/www/site2/docroot"
    listen: 81
    is_php: true
```

I do not believe it's possible for apache at the moment though.
