### ISSUE TITLE
Message: (./config.yml): did not find expected key while parsing a block mapping at line 3 column 1

### ISSUE THREAD

**Issue by welly** [geerlingguy/drupal-vm#50]
Hello,

I'm getting the following error when I run vagrant up:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/alastair/dev/experimental/drupal/ajax/Vagrantfile
Message: (./config.yml): did not find expected key while parsing a block mapping at line 3 column 1

A copy of my config.yml is as follows:

```
---
# Vagrant hostname and IP configuration.
vagrant_hostname: ajax.vm
vagrant_ip: 192.168.34.10
vagrant_user: vagrant

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: /Users/alastair/dev/experimental/drupal/ajax
    destination: /var/www
    id: drupal
    type: nfs

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Set this to false if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_from_makefile: true
drush_makefile_path: /vagrant/drupal.make.yml

# Settings for building a Drupal site from a makefile (if 'build_from_makefile'
# is 'true').
drupal_major_version: 7
drupal_core_path: "/var/www/drupal"
drupal_domain: "ajax.vm
drupal_site_name: "AJAX Dev"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_mysql_user: admin
drupal_mysql_password: password

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}
  - {servername: "local.xhprof.com", documentroot: "/usr/share/php/xhprof_html"}

# MySQL Databases and users. If build_from_makefile is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: drupal
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"

# Comment out any extra utilities you don't want to install.
installed_extras:
  - mailhog
  - memcached
  - phpmyadmin
  - xdebug
  - xhprof

# You can configure almost anything else on the server in the rest of this file.
mysql_root_password: root
drush_version: master

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
  - "8080"
  - "8443"

php_memory_limit: "256M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0
```

Any ideas?

Thanks!
