### ISSUE TITLE
connection refused on port 80 errors - drupal vm

### ISSUE THREAD

**Issue by smallela1** [geerlingguy/drupal-vm#546]
Not Found

The requested URL / was not found on this server.

Apache/2.4.18 (Ubuntu) Server at drupalvm.dev Port 80.

This issue is on my Windows 7 machine. I have installed drupal vm, ran vagrant up. I have mounted my drupal folder (pulled from git and ran on Acquia) as local_path under vagrant_sync_folders. Am using the same settings for mysql database on drupalvm as the one I used for local Acquia.

Below is my configuration in config.yml:

```yaml
vagrant_hostname: drupalvm.dev
vagrant_machine_name: drupalvm
vagrant_ip: 192.168.88.88

vagrant_public_ip: ""

vagrant_synced_folders:
  - local_path: C:\Drupal8_Applications\drupaldev
    destination: /var/www/drupalvm
    type: nfs
    create: true

vagrant_memory: 2048
vagrant_cpus: 2

drupalvm_webserver: apache

build_makefile: false
drush_makefile_path: ../../drupal.make.yml

install_site: false

drupal_major_version: 8
drupal_core_path: "/var/www/drupalvm/drupal"
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin
drupal_mysql_user: drupaluser
drupal_mysql_password: 
drupal_mysql_database: drupaldev
```
