### ISSUE TITLE
DrupalVM 2.5.1 Issues with NPM Packages

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#629]
@geerlingguy, Just updated an existing VM to 2.5.1.  Encountering an issue with NPM dependencies.  I'm only including the first node error.  There are more.

> failed: [atf-local] (item={u'name': u'grunt'}) => {"cmd": "/usr/bin/npm install --global grunt", "failed": true, "item": {"name": "grunt"}, "msg": "npm ERR! tar.unpack untar error /home/vagrant/.npm/grunt/1.0.1/package.tgz\nnpm ERR! Linux 4.2.0-27-generic\nnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"install\" \"--global\" \"grunt\"\nnpm ERR! node v0.12.14\nnpm ERR! npm  v2.15.1\nnpm ERR! path /usr/lib/node_modules/grunt\nnpm ERR! code EACCES\nnpm ERR! errno -13\n\nnpm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/grunt'\nnpm ERR!     at Error (native)\nnpm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/grunt']\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   path: '/usr/lib/node_modules/grunt',\nnpm ERR!   fstream_type: 'Directory',\nnpm ERR!   fstream_path: '/usr/lib/node_modules/grunt',\nnpm ERR!   fstream_class: 'DirWriter',\nnpm ERR!   fstream_stack: \nnpm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',\nnpm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',\nnpm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /home/vagrant/npm-debug.log", "rc": 243, "stderr": "npm ERR! tar.unpack untar error /home/vagrant/.npm/grunt/1.0.1/package.tgz\nnpm ERR! Linux 4.2.0-27-generic\nnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"install\" \"--global\" \"grunt\"\nnpm ERR! node v0.12.14\nnpm ERR! npm  v2.15.1\nnpm ERR! path /usr/lib/node_modules/grunt\nnpm ERR! code EACCES\nnpm ERR! errno -13\n\nnpm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/grunt'\nnpm ERR!     at Error (native)\nnpm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/grunt']\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   path: '/usr/lib/node_modules/grunt',\nnpm ERR!   fstream_type: 'Directory',\nnpm ERR!   fstream_path: '/usr/lib/node_modules/grunt',\nnpm ERR!   fstream_class: 'DirWriter',\nnpm ERR!   fstream_stack: \nnpm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',\nnpm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',\nnpm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /home/vagrant/npm-debug.log\n", "stdout": "", "stdout_lines": []}

I have the following in my config.yml. Am I doing something silly? 
```
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - mailhog
  - memcached
  - nodejs
  # - memcached
  # - newrelic
  - pimpmylog
  # - redis
  - ruby
  # - selenium
  # - solr
  - varnish
  - xdebug
  - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages: []

# `nodejs` must be in installed_extras for this to work. Valid examples: "0.10",
# "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages:
 - name: grunt
 - name: grunt-cli
 - name: bower
nodejs_install_npm_user: "{{ drupalvm_user }
```

Thanks!
-Adam
