### ISSUE TITLE
drupalvm installs dev version

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#631]
How do i get drupalvm to install the stable version and not dev version

**Comment by oxyc** [comment]
```yaml
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "8.x"

projects:

  # Core.
  drupal:
    version: 8.1 # Would pick 8.1.1 at the moment

  # Other modules.
  devel: "1.x-dev"
```
