### ISSUE TITLE
All domains lead to nginx welcome page

### ISSUE THREAD

**Issue by nlisgo** [geerlingguy/drupal-vm#664]
I am using version 3.0.0 and setting nginx as my drupalvm_webserver doesn't seem to setup the appropriate nginx vhosts. Switch to apache and it works fine. I would prefer to use nginx though.

The issue was raised before on a previous version: https://github.com/geerlingguy/drupal-vm/issues/486

As far as I can tell it wasn't resolved. The reporter of the issue was able to get around it by changing:

```
nginx_hosts:
  - server_name: "{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true
```

to the hardcoded:
```
nginx_hosts:
  - server_name: "dca13.dev"
    root: "/var/www/drupalcampatlanta"
    is_php: true
```

This represents a bug and if it doesn't work without being hardcoded then the documentation should be amended until it is fixed.
