### ISSUE TITLE
Set up nginx on https

### ISSUE THREAD

**Issue by smithyco** [geerlingguy/drupal-vm#691]
How would you configure the `config.yaml` file to run nginx over port 443 instead of port 80?

I see in the docs that there's instructions for setting that up with the snakeoil cert in Apache:
http://docs.drupalvm.com/en/latest/extras/ssl/

Are the instructions pretty similar for doing this in nginx?

**Comment by geerlingguy** [comment]
See the Ansible role documentation for more info: https://github.com/geerlingguy/ansible-role-nginx

You can set up a server's config like so:

```
nginx_vhosts:
  - listen: "443 default_server"
    server_name: "example.com"
    root: "/var/www/example.com"
```

...something along those lines. Basically, you need to tell Nginx to listen on port 443 instead of 80 (which is the default `listen` directive).
