### ISSUE TITLE
Make sure documentation (and Quick Start guide) are up to date

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#704]
After the major changeover from Drush make to Composer defaults for building the Drupal site, we need to make a pass through the docs and ensure they're correct for both use cases.

See:

  - #699 
  - #506 

Also, as I'm going to include necessary `vagrant-cachier` configuration by default per #702, we need to update the docs relating to that config in the Composer guilde.

cc @oxyc — I'll try to take a pass tonight after finishing up more testing, then if you want to glance through, that would be much appreciated!

**Comment by oxyc** [comment]
I'm signing off for tonight but I can have a look tomorrow. This is going to be another awesome release!

**Comment by geerlingguy** [comment]
Working on this now.

**Comment by oxyc** [comment]
I've got a few additions I can add once you're done.

Eg switch the composer create-project docs to use `lightning-project` as an example:

```yaml
drupal_composer_project_package: "acquia/lightning-project:^8.1.0"
drupal_composer_project_options: "--prefer-dist --stability rc --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
```
