### ISSUE TITLE
Adding a second db removed my first db in config.yml

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#739]
Under 3.1.1, I tried adding a second mysql database and re provisioned.

Here is my config:

```
mysql_databases:
  - name: "{{ drupal_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci

  - name: "velir_d7"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"

  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "velir_d7.*:ALL"
```

When I got into mysql, the original database 'drupal' was gone, and only velir_d7 remained. What did I do wrong?

**Comment by geerlingguy** [comment]
What is the value of `drupal_mysql_database` elsewhere in the config?

**Comment by kevinquillen** [comment]
```
drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: drupal
```

**Comment by kevinquillen** [comment]
Setting the database name to "drupal" instead of use the variable resulted in the same thing. Only the second database was created.

**Comment by kevinquillen** [comment]
Okay, so maybe this is more of a permission issue.

If I log into adminer with root / root, I see both databases. If I log in with drupal / drupal, I do not.

**Comment by oxyc** [comment]
Try with

```yaml
mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"

  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "velir_d7.*:ALL"
    append_privs: yes
```
