### ISSUE TITLE
3.12 Global Node Packages No longer installing

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#744]
After upgrading to the latest version of Drupal VM.  The node global packages no longer seem to install properly. The provision doesn't throw errors but grunt is not part of the global path. 

```
# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages:
  - name: grunt
  - name: grunt-cli
  - name: bower
nodejs_install_npm_user: "root"
npm_config_prefix: "~/.npm-global"
```
