### ISSUE TITLE
Local Drupal Codebase error

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#827]
I have followed the instructions at http://docs.drupalvm.com/en/latest/deployment/local-codebase/ as best I can. 

When I type http://drupalvm.dev/ into Chrome I get "File not found." 

Attached is my config.yml file. Please tell me what I did wrong. My Drupal file structure is at C:\Users\samst\Desktop\Drupal\DrupalVM\web\cb.

Thanks!

[config.zip](https://github.com/geerlingguy/drupal-vm/files/384039/config.zip)

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - I'm assuming that `/var/www/drupalvm/web/cb` on your local host machine (mac or linux?) contains a Drupal docroot, e.g. index.php and all the rest of the files?

Your synced folders look like:

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: /var/www/drupalvm/web/cb 
    destination: /var/www/drupalvm/web/cb 
    type: nfs
    create: true
```

Usually for my local_path, I have something like `~/Sites/sitename`, since I store my local sites in my Sites folder inside my user home folder.
