### ISSUE TITLE
build_makefile is failing - the first other module added isn't found

### ISSUE THREAD

**Issue by rpkoller** [geerlingguy/drupal-vm#858]
Hi... I've downloaded the latest version of DrupalVM... I've added the `config.yml`file; the only thing i've changed was to set `build_composer_project` to false and `build_makefile` to true. Nothing else was changed. `default.drupal.make.yml`I've changed to:

```
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "8.x"

projects:

  # Core.
  drupal:
    version: "8.1.7"
    # Use this if you need a working git repository of Drupal core instead of
    # the latest stable.
    # type: "core"
    # download:
    #   # Drupal core branch (e.g. "6.x", "7.x", "8.0.x").
    #   branch: "8.1.x"
    #   working-copy: true

  # Other modules.
  devel: "1.x-dev"
  paragraphs: "8.x-1.0"
  group: "8.x-1.0-beta2"
  honeypot: "8.x-1.23"
  pathauto: "8.x-1.0-alpha3"
  entity_reference_revisions: "8.x-1.0"
  token: "8.x-1.0-alpha2"
  workbench: "8.x-1.0-alpha2"
  metatag: "8.x-1.0-beta9"
  ctools: "8.x-3.0-alpha26"
  admin_toolbar: "8.x-1.16"
```
Basically just added a few more other modules. When I fire up a fresh machine with `vagrant up`the provisioning fails with the following error: 

```
TASK [Generate Drupal site with drush makefile.] *******************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "make", "-y", "/tmp/drupal.make.yml", "--no-gitinfofile"], "delta": "0:00:00.359594", "end": "2016-08-10 10:37:00.332202", "failed": true, "rc": 1, "start": "2016-08-10 10:36:59.972608", "stderr": " [ok] Beginning to build /tmp/drupal.make.yml.\n [error]  Could not locate paragraphs version 8.x-8.x-1.0. \n [error]  Drush Make failed to download all projects. See the log above for the specific errors. ", "stdout": "Make new site in the current directory? (y/n): y", "stdout_lines": ["Make new site in the current directory? (y/n): y"], "warnings": []}
```

Somehow another `8.x." is prefixed to the version number of the paragraphs modules?! Aside I've checked if my global drush setup works, but looks like it does: 

```
$> drush status
 PHP configuration      :  /etc/php.ini
 PHP OS                 :  Darwin
 Drush script           :  /usr/local/bin/drush
 Drush version          :  8.1.3
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :  /Users/danton/.drush/drupalvm.aliases.drushrc.php
```
```
$> drush dl drupal --drupal-project-rename=example
Project drupal (8.1.8) downloaded to                                [success]
/Users/myuser/sites/drupalvm/drupal/web/example.
Project drupal contains:                                            [success]
 - 1 profile: standard
 - 13 themes: stark, stable, seven, twig, classy, bartik,
testing_multilingual_with_english, testing_multilingual,
testing_config_overrides, testing_config_import,
drupal_system_listing_compatible_test, testing, minimal
 - 66 modules: views_ui, views, user, update, tracker, tour,
toolbar, text, telephone, taxonomy, system, syslog, statistics,
simpletest, shortcut, serialization, search, rest, responsive_image,
rdf, quickedit, path, page_cache, options, node, migrate_drupal_ui,
migrate_drupal, migrate, menu_ui, menu_link_content, locale, link,
language, inline_form_errors, image, history, help, hal, forum,
filter, file, field_ui, field, entity_reference, editor,
dynamic_page_cache, dblog, datetime, contextual,
content_translation, contact, config_translation, config, comment,
color, ckeditor, breakpoint, book, block_content, block, big_pipe,
basic_auth, ban, automated_cron, aggregator, action
```
So not sure where the error is located. Is it a faulty makefile or a bug? On a sidenote since i am rather new to Drupal and that whole configuration process. Is the Drush makefile the best practice for setting up a site or is `build_composer` the recommended way to go with? Best regards r.  

p.s. i am running Ansible 2.1.1.0

**Comment by geerlingguy** [comment]
@rpkoller - Thanks for the detailed issue!

Honestly, either makefile or composer are fine for now; it'll be a year or more before more of the community settles on only using Composer, since there are a few growing pains associated with switching to an all-Composer workflow that are still being sorted out.

For your problem, basically you need to specify versions of modules _without_ the leading `8.x-`, so like:

```yaml
  # Other modules.
  devel: "1.x-dev"
  paragraphs: "1.0"
  group: "1.0-beta2"
  honeypot: "1.23"
  pathauto: "1.0-alpha3"
  entity_reference_revisions: "1.0"
  token: "1.0-alpha2"
  workbench: "1.0-alpha2"
  metatag: "1.0-beta9"
  ctools: "3.0-alpha26"
  admin_toolbar: "1.16"
```

(Also, thanks for using Honeypot ;).

I'm going to close this pre-emptively, hoping that was the issue; let me know if it's not!
