### ISSUE TITLE
Drupal 8 gets installed when trying to install Drupal 7

### ISSUE THREAD

**Issue by shivaray** [geerlingguy/drupal-vm#907]
Hey,

Thanks for drupal-vm, it's a great project and looks like a great alternative to VDD. I'm trying to set up a quick D7 install for some testing, but I have two issues:

1. Even though the installed extras are supposed to be optional, the install fails without `mailhog` and `memcached`. This is not a deal-breaker though it did make me scratch my head a bit. Turning them on seems to resolve the issue.
2. As you can see from the attached `config.yml` and `drupal.make.yml`, I have set everything up for a drupal 7 install according to the documentation. However as you can see from the screenshot at the end, I end up with a D8 install. 

Any ideas on how to fix this? TIA!

# config.yml
```
---
vagrant_hostname: drupal.xyz.abc.com
build_composer_project: false
build_makefile: true
drupal_core_path: "/var/www/drupalvm/drupal"
drupal_major_version: 7

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  # - adminer
  # - blackfire
  # - drupalconsole
  # - elasticsearch
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  # - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - varnish
  # - xdebug
  # - xhprof
```

# drupal.make.yml

```
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "7.x"

projects:

  # Core.
  drupal:
    version: "7.50"
    # Use this if you need a working git repository of Drupal core instead of
    # the latest stable.
    # type: "core"
    # download:
    #   # Drupal core branch (e.g. "6.x", "7.x", "8.0.x").
    #   branch: "8.1.x"
    #   working-copy: true

  # Other modules.
  services: "7.x-3.17"
  devel: "1.x-dev"
```

![image](https://cloud.githubusercontent.com/assets/3980671/18853506/817026cc-8413-11e6-90cb-a585624dd509.png)
