### ISSUE TITLE
Multiple Drupal website configuration fails with "Site not found."

### ISSUE THREAD

**Issue by 1forh** [geerlingguy/drupal-vm#919]
I have followed the [instructions](http://docs.drupalvm.com/en/latest/deployment/local-codebase/#disable-the-composer-project-build-and-site-install) for booting up a VM with multiple Drupal websites. 

I have added my `vagrant_synced_folders` and `apache_vhosts` to my `config.yml`. I then run `vagrant up` and everything seems to go smoothly. Whenever I try to go to `examplesite1.dev`, for example, I get a white page with `Site not found.`

I believe the culprit is in my config setup. 

Here is my config.yml:

```yml
vagrant_box: geerlingguy/ubuntu1604
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_hostname: drupalvm.dev
vagrant_machine_name: drupalvm
vagrant_ip: 10.11.12.14
vagrant_public_ip: ''
vagrant_synced_folders:
  - local_path: ~/Sites/examplesite1.com/www
    destination: /var/www/examplesite1.com
    type: nfs
    create: true
  - local_path: ~/Sites/examplesite2.org/www
    destination: /var/www/examplesite2.org
    type: nfs
    create: true
vagrant_memory: 1024
vagrant_cpus: 1
drupalvm_vagrant_version_min: 1.8.5
drupalvm_ansible_version_min: '2.1'
force_ansible_local: false
drupalvm_webserver: apache
drupalvm_database: mysql
build_makefile: false
drush_makefile_path: '{{ config_dir }}/drupal.make.yml'
drush_make_options: '--no-gitinfofile'
build_composer: false
drupal_composer_path: '{{ config_dir }}/drupal.composer.json'
drupal_composer_install_dir: /var/www
drupal_composer_dependencies:
  - 'drupal/devel:1.x-dev'
build_composer_project: false
drupal_composer_project_package: 'drupal-composer/drupal-project:8.x-dev'
drupal_composer_project_options: '--prefer-dist --stability dev --no-interaction'
install_site: false
drupal_core_path: '{{ drupal_composer_install_dir }}'
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal
drupal_major_version: 7
drupal_domain: '{{ vagrant_hostname }}'
drupal_site_name: Drupal
drupal_install_profile: standard
drupal_enable_modules:
  - devel
drupal_account_name: admin
drupal_account_pass: admin
drupal_site_install_extra_args: []
drupalvm_cron_jobs: []
configure_drush_aliases: true
apache_vhosts:
  - servername: examplesite1.dev
    serveralias: www.examplesite1.dev
    documentroot: /var/www/examplesite1.com
    extra_parameters: >
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{
      drupal_core_path }}"
  - servername: examplesite2.dev
    serveralias: www.examplesite2.dev
    documentroot: /var/www/examplesite2.org
    extra_parameters: >
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{
      drupal_core_path }}"
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
nginx_hosts:
  - server_name: '{{ drupal_domain }} www.{{ drupal_domain }}'
    root: '{{ drupal_core_path }}'
    is_php: true
  - server_name: 'adminer.{{ vagrant_hostname }}'
    root: '{{ adminer_install_dir }}'
    is_php: true
  - server_name: 'xhprof.{{ vagrant_hostname }}'
    root: '{{ php_xhprof_html_dir }}'
    is_php: true
  - server_name: 'pimpmylog.{{ vagrant_hostname }}'
    root: '{{ pimpmylog_install_dir }}'
    is_php: true
  - server_name: '{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}'
    root: '{{ dashboard_install_dir }}'
nginx_remove_default_vhost: true
nginx_ppa_use: true
mysql_databases:
  - name: thermtrol
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: fgcquaker
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: '{{ drupal_db_user }}'
    host: '%'
    password: '{{ drupal_db_password }}'
    priv: '{{ drupal_db_name }}.*:ALL'
postgresql_databases:
  - name: '{{ drupal_db_name }}'
postgresql_users:
  - name: '{{ drupal_db_user }}'
    password: '{{ drupal_db_password }}'
    db: '{{ drupal_db_name }}'
    priv: ALL
installed_extras:
  - adminer
  - drupalconsole
  - mailhog
  - pimpmylog
  - varnish
extra_packages:
  - sqlite
extra_security_enabled: false
drush_version: master
drush_keep_updated: true
drush_composer_cli_options: '--prefer-dist --no-interaction'
firewall_allowed_tcp_ports:
  - '22'
  - '25'
  - '80'
  - '81'
  - '443'
  - '4444'
  - '8025'
  - '8080'
  - '8443'
  - '8983'
  - '9200'
firewall_log_dropped_packets: false
php_version: '7.0'
php_memory_limit: 192M
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_realpath_cache_size: 1024K
php_sendmail_path: /opt/mailhog/mhsendmail
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: '192'
php_opcache_max_accelerated_files: 4096
php_max_input_vars: '4000'
php_enable_php_fpm: true
php_fpm_listen: '127.0.0.1:9000'
composer_path: /usr/bin/composer
composer_home_path: '/home/{{ drupalvm_user }}/.composer'
composer_home_owner: '{{ drupalvm_user }}'
composer_home_group: '{{ drupalvm_user }}'
composer_global_packages:
  - name: hirak/prestissimo
    release: ^0.3
pre_provision_scripts: []
post_provision_scripts: []
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php
nodejs_version: '0.12'
nodejs_npm_global_packages: []
nodejs_install_npm_user: '{{ drupalvm_user }}'
npm_config_prefix: '/home/{{ drupalvm_user }}/.npm-global'
ruby_install_gems_user: '{{ drupalvm_user }}'
ruby_install_gems: []
varnish_listen_port: '81'
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: 127.0.0.1
varnish_default_backend_port: '80'
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
solr_version: 5.5.2
solr_xms: 64M
solr_xmx: 128M
selenium_version: 2.53.0
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts
```

Any help would be appreciated!

**Comment by oxyc** [comment]
You'll need to point ProxyPassMatch to the correct location as well:

```yaml
apache_vhosts:
  - servername: examplesite1.dev
    serveralias: www.examplesite1.dev
    documentroot: /var/www/examplesite1.com
    extra_parameters: >
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/examplesite1.org"
  - servername: examplesite2.dev
    serveralias: www.examplesite2.dev
    documentroot: /var/www/examplesite2.org
    extra_parameters: >
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/examplesite2.org"
```
