### ISSUE TITLE
How can I disable opcache

### ISSUE THREAD

**Issue by subhojit777** [geerlingguy/drupal-vm#977]
I have tried setting

```yml
php_opcache_enabled_in_ini: false
php_opcache_enable: "0"
php_opcache_enable_cli: "0"
```

in the `config.yml` and did `vagrant provision` but still the `opcache` remains enabled.
